### ISSUE TITLE
Not able to slide with data subscribed

### ISSUE THREAD

**Issue by gamboaweb** [zefoy/ngx-swiper-wrapper#101]
I'm trying to create slides dynamically with ngFor:
`<swiper class="swiper-container main-view-slider" [config]="configSwiper">
    <div *ngFor="let a of affirmations" class="swiper-slide" >
      <div data-swiper-parallax="40%" 
      class="background" [ngStyle]="{'background-image':'url(' + a.image.src +')' }">
      </div>
      <div class="slide">
        <div class="title" data-swiper-parallax="13%">
          <h1 class="animated" >
            {{a.text}}
          </h1>
        </div>
  
        <div class="button-container" data-swiper-parallax="33%">
          <div class="holdbutton">
            Affirm
            <span>+1</span>
          </div>
        </div>
      </div>
    </div>
    <div class="swiper-pagination"></div>
</swiper>`
The variable "affirmations" is populated with promise and in the html rendered code you can see that ngFor correctly produced the "swipper-slide" (four of them in this example).
The first slide is correctly shown but I CAN'T swipe the slides??!!
If I make the same example but with affirmations being explicitly declared in the ts file like
`affirmation: any = [
{
image:{clss: "background-image-2", author: "Daniel Roe", src: "assets/img/Daniel-Roe-med.jpg", tmb: "assets/img/Daniel-Roe-tmb.jpg"},
text:"slide 1"
},
{...},
{...},
]`
then it works perfectly...
it's like the promise may be lagging the component...?
Can you help me with this one?

**Comment by sconix** [comment]
When ever you are dealing with dynamically created slides you need to either use observer: true in swiper config (works in most cases detecting element changes) or call the swiper update method manually after the slides have changed.

**Comment by gamboaweb** [comment]
sconix...I really apreciate your reply!
I was thinking calling the method manually.
Could you show me an example...I think it could benefit others having an example here...that could have this problem too.

**Comment by sconix** [comment]
You can call the update via the directiveRef (example has examples for component and directive how to call the api functions). So basically you just call the update function after your async promise finishes, the update is run within timeout so the rendering should have time to take place. But there is no simple example I can make since things like changedetection strategy etc. has an effect when and where to call the update. So you just need to experiment a bit.

**Comment by gamboaweb** [comment]
Ok. thanks a lot you really helped me!
