### ISSUE TITLE
Swiper starting form last slide directive bug

### ISSUE THREAD

**Issue by alexkushnarov** [zefoy/ngx-swiper-wrapper#103]
When I set slidesPerView to 'auto' and set initialSlide to 0, I see swiper stating form the end (directive only)
Can somebody please tell me how to make slider starts form the beginning (I need that slidesPerView to be 'auto'.)
a simple code which shows the issue (taken from original plugin demo http://plnkr.co/edit/5eGsfBasinjUBWYEcNx8?p=preview) :
Plunker which shows the issue - http://plnkr.co/edit/bOg5TvfWIVzva1lckqVh?p=preview (only config was changed)

P.S. In my real project I'm using my own styles and slidesPerView = 'auto' is very important for me to handle responsive design.

**Comment by sconix** [comment]
Thanks for the Plunker example, I will check it tomorrow if its a wrapper bug or something in the Swiper. At least it might be possible to add some workaround since the component works.

**Comment by alexkushnarov** [comment]
Thanks, I appreciate it.
it might be swiper.js, on initialization it call onResize method and it call this code which change the index to the last one.
translated = swiper.slideTo(swiper.slides.length - 1, 0, false, true);
(it is weird that swiper.isEnd is true and  swiper.isBeginning is true too).
https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L3588-L3592

**Comment by sconix** [comment]
You are right that it does seem swiper.js bug, but the thing I am not getting is that why component works.  Most likely the bug is in the Swiper update mechanism not updating the slide states correctly when using observer: true.

**Comment by sconix** [comment]
It seems that there is no easy workaround I could do on the wrapper, specially since I don't quite understand why Swiper still thinks that it is at the end when it runs the update. I will make an issue to Swiper about this and lets hope I get a response from the developer to either fix the issue or to get a clue how I could fix this.

So for now I think your only options is to setIndex to 0 in ngAfterViewInit via the API to go around this issue.

**Comment by sconix** [comment]
Actually other thing you can do is to set the observer to false and call update manually once slides are rendered (in ngAfterViewInit for example).

**Comment by alexkushnarov** [comment]
Ok thanks, will try that

**Comment by alexkushnarov** [comment]
Now I'm updating swiper manually this solution works for me.
Thanks a lot @sconix I appreciate it.

**A Plunker with the fix if somebody facing same issue** 
http://plnkr.co/edit/vXGoZrWTl9IjZcp5UKdQ?p=preview

**Comment by argee84** [comment]
I have the same problem as already described. I use the ngx-swipper-wrapper 6.3.0 version with angular cli 6.0.7. Tested both, component and directive. With same result.
The fix from @alexkushnarov doesn't work for me.
Is there any workaround?

**Comment by sconix** [comment]
You are not updating it in the correct place. The update needs to be called after dom is fully ready for Swiper to work.

**Comment by argee84** [comment]
Thx for the answer.
It's like there's another issue. If I do it exactly like these example https://github.com/nolimits4web/Swiper/blob/master/demos/140-centered-auto.html
the issue popup.

Swiper JS has a problem with dynamic width of the slides. I set it to a fixed width and that solve my problem.

**Comment by HannaBabrouskaya** [comment]
Maybe somebody this will help
if you have slidesPerView: 'auto' in your config and it starts from the last slide, you can add centeredSlides: true this fixed the issue for me

**Comment by MarkHTML** [comment]
I had the same issue with slidesPerView = 'auto' and centeredSlides = true and initialSlide = 1.

In end end it seems I had to slideTo() before and after init() like so:

`
  swiper = new Swiper('.slider', {
            slidesPerView: 'auto',
            centeredSlides: true,
            spaceBetween: 10,
            initialSlide: 1,
            init: false
        });
        swiper.slideTo(1);
        swiper.on('init', function () {
            setTimeout(function() {//hacky fix to prevent swiper bug starting on the last slide!
                swiper.slideTo(1);
            },2000);
        });
        swiper.init();
    }
`
