### ISSUE TITLE
Can't make *ngFor 

### ISSUE THREAD

**Issue by preto89** [zefoy/ngx-swiper-wrapper#104]
Every time i switch to another page and return , the slideshow disapears but if i click on the route again it appears WTF, theres not even one good Carousel for Angular 5, or its is not responsive, or doesnt have custom navigation, or cant read fking data !!! dude fix this shit

this is my swiper
```
   <swiper *ngIf="slides" [config]='config' [(index)]="index"  >
 
        <div class="swiper-slide" *ngFor="let slide of slides">
          <img class="d-block slider-item" src="http://mycoolhiddenip:8880/store/{{slide.imageId}}" alt="{{slide.id}}">
        </div>
        
      </swiper>
```
this is my config
```
export const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
    direction: 'horizontal',
    slidesPerView: 'auto',
    keyboard: true,
    centeredSlides: true,
    loop:true,
    simulateTouch:true,
    speed:1000,
    freeModeMomentum:true,
    followFinger:false,
    observer:true,
    preloadImages:true,
    longSwipesMs:500,
    updateOnImagesReady:true,
    freeModeMinimumVelocity:0.1,
    autoplay: {
        delay: 900,
        stopOnLast: false,
        disableOnInteraction:false
      },
    navigation: {
        nextEl: '.rightRs',
        prevEl: '.leftRs',
    },
    pagination: {
        el: '.swipages',
        clickable: true,
        bulletClass: 'Texttab',
        bulletActiveClass: 'hovered-TextTab',
        totalClass: 'swiperClass',
        renderBullet: function (index, className) {
            return '<li class="nav-item my-auto nav-link slideNav ' + className + '" id="two">' + navItems[i++] + '</li>';
        },
    },
};
```
Slides Array:
```
slides: Slide[] = [
    {
      id: "dsds",
      imageId: '59f7484ac919b73d54700221',
      text: 'Verão Azul'
    },
    {
      id: "dsdsfdf",
      imageId: '5a3a8c6abc695615149f64ef',
      text: 'Verãosa Azul'
    },
    {
      id: "dsds",
      imageId: '59f7484ac919b73d54700221',
      text: 'Verão Azul'
    }, {
      id: "dsdsfdf",
      imageId: '5a3a8c6abc695615149f64ef',
      text: 'Verãosa Azul'
    },
  ];
```

**Comment by sconix** [comment]
Not the best way to start an issue if you are trying to ask for help how to use the library. This library works 100% with Angular 5 we have no issue with the Swiper. If you have trouble then try to replicate the problem with the existing Plunker template so problems due to bad code can be ruled out.

**Comment by preto89** [comment]
So u do a fkin plugin and dont even know how to fix your shit, fkin retarded people man.
Fkin retarded carousel plugins. this library WORKS 0% with Angular 5, if u have static content sure works pretty nice , fkin noob.

**Comment by preto89** [comment]
Did you actualy test this shit with routing and dynamic content? no of course not...

**Comment by sconix** [comment]
We use this very extensively in our application which has dynamic / static / routing etc. pretty much everything and have no issues.
