### ISSUE TITLE
directiveRef instance is getting undefined.

### ISSUE THREAD

**Issue by muhammadali208** [zefoy/ngx-swiper-wrapper#105]
i write my slider directive approach html in *ngIf="recent_uploaded_data_Array" condition. 
i make https call and after call response i want to show the slides. after call when i write this.directiveRef.update.
it gives error Cannot read property 'update' of undefined. w hen i debug the code and found that directiveRef instance is  undefind.

please ans is quickly my project deadline is very near.

**Comment by sconix** [comment]
This is more of an Angular related question. You are trying to  use the directiveRef before its initialized i.e. before angular change detection has picked up the change for the ngIf. So you need to call it most likely inside timeout or use observer etc.
