### ISSUE TITLE
Performance issues in Angular5 application on mobile

### ISSUE THREAD

**Issue by omerlive** [zefoy/ngx-swiper-wrapper#106]
Hi,
I'm using the latest version of Swiper on my Angular 5 application and I have few issues with the swiper behavior:

1. The swiper has a lot of freezing/delay when I touch to swipe.
2. The swipes are not smooth.
3.  Every little/short swipe make the slider move very fast not proportion to the finger's touch.   

My only configuration that is not default is freemode true.
And each swiper-slide has an image with description text.

I will appreciate if you can assist me with those issues,
Thanks in advanced

**Comment by sconix** [comment]
I am not seeing those issues in our application, although we are not using freemode. Are you sure that you don't have some change detection issue in your application that would cause high cpu usage etc? 
Anyway this is just a wrapper library so this don't have any effect on the how the swipes are handled so you might need to report that issue in the Swiper issues.

**Comment by nasserghiasi** [comment]
It's too laggy for me in phone devices!

**Comment by sconix** [comment]
Usually the reason is in you applications change detection firing way too often. For use the Swiper is smooth in the mobile.
