### ISSUE TITLE
events not fired on swiper component

### ISSUE THREAD

**Issue by amr-alamir** [zefoy/ngx-swiper-wrapper#108]
In [this stackblitz](https://stackblitz.com/edit/angular-hyfkw7)  I try to fire `slideNextTransitionStart ` and `slidePrevTransitionStart` events to log a simple text in the console.
the `slideChange` event works fine, but these events don't.

here is the **template**
```html
<swiper [config]="config"
        (slideChange)="onChangeSlide()"
        (slideNextTransitionStart)="onNextSlide()"
        (slidePrevTransitionStart)="onPrevSlide()">

  <h1 *ngFor="let item of items" style="background: green;">
    {{item}}
  </h1>

</swiper>
```

and here is the **.ts file** (excerpt)
```typescript
  onChangeSlide() {
    console.log("change");
  }

  onNextSlide() {
    console.log("next");
  }

  onPrevSlide() {
    console.log("previous");
  }
```

**Comment by sconix** [comment]
It seems that I forgot to rename those events correctly for the component when upgrading to Swiper 4.x. I will release fix today,

**Comment by sconix** [comment]
Version 5.2.1 is now out and should fix that issue, let me know if not.

**Comment by amr-alamir** [comment]
thank you for the quick fix
