### ISSUE TITLE
Can't find some properties (realIndex, activeIndex) of swiper component

### ISSUE THREAD

**Issue by amr-alamir** [zefoy/ngx-swiper-wrapper#109]
In [this stackblitz](https://stackblitz.com/edit/angular-3u85et)  I try to access swiper `realIndex` or `activeIndex` properties, and I got `undefind`

here is the **template**
```html
<swiper #swiper [config]="config"
        (slideChange)="onChangeSlide(swiper)">

  <h1 *ngFor="let item of items">
    {{item}}
  </h1>

</swiper>
```

and here is the **.ts file** (excerpt)
```typescript
  onChangeSlide(swiper) {
    console.log(swiper.realIndex); //logs 'undefined'
  }
```

**Comment by sconix** [comment]
Component nor the directive is not the same as the Swiper instance. You need to call the swiper() through the directive reference to get the swiper instance. From there you get all the information that swiper provides.

**Comment by amr-alamir** [comment]
thank you, I had some trouble setting directive reference, but now it is ok.
here is the **stackblitz** if someone needs it
[https://stackblitz.com/edit/ngx-swiper-wrapper-demo-2x8zbc](https://stackblitz.com/edit/ngx-swiper-wrapper-demo-2x8zbc)
