### ISSUE TITLE
Add stackblitz Demo (with / or as a replacement of  plunker template link)

### ISSUE THREAD

**Issue by amr-alamir** [zefoy/ngx-swiper-wrapper#111]
Plunker template is incomplete or not working, and has issues with adblockers
I suggest adding or replacing with a **stackblitz.io** template

here is a working **stackblitz ngx-swiper-wrapper demo**

[https://stackblitz.com/edit/ngx-swiper-wrapper-demo](https://stackblitz.com/edit/ngx-swiper-wrapper-demo)

and here is **the live demo**

[https://ngx-swiper-wrapper-demo.stackblitz.io](https://ngx-swiper-wrapper-demo.stackblitz.io)
  
  
  N.B. I created a pull request #112 to add this to the readme file

**Comment by sconix** [comment]
Not sure how the Plunker demo is incomplete or not working. I mean its fully working for me and I do use ad blocker. Anyway thanks, I can of course add the stackblitz demo.
