### ISSUE TITLE
Directive loop=true erroneous looping

### ISSUE THREAD

**Issue by amr-alamir** [zefoy/ngx-swiper-wrapper#113]
in [this stackblitz](https://stackblitz.com/edit/angular-cnwc4c) I have **5 slides** and  I used the **directive** with **loop=true**
I got **erroneous** behavior as follows:

- it is ok when going from slide 1 to slide 5
- after slide 5 it bypasses slide 1 and goes directly to slide 2
- when on slide 5 and try to go to previous slide it goes to slide 1 (without animation)
- when on slide 1, it doesn't go to previous slide (not looping backwords)

**template**
```html
<div  class="swiper-container tall" [swiper]="config">
    <div class="swiper-wrapper">
        <div class="swiper-slide green" *ngFor="let slide of slides" >
          {{slide}}
        </div>
    </div>
</div>
```

**component** (excerpt)
```typescript
  @ViewChild(SwiperDirective) directiveRef: SwiperDirective;

  config: SwiperConfigInterface = {
    observer: true,
    loop: true,
    keyboard: true,
    mousewheel: true,
  }
```

**Comment by sconix** [comment]
You need to report it to Swiper issues, this is just a wrapper and does not have any effect on how Swiper works.

**Comment by amr-alamir** [comment]
I updated the [stackblitz](https://stackblitz.com/edit/angular-cnwc4c) and added static slides but unfortunately,  raised another erroneous behavior!!
my problem is that: I have hundreds of large images that I need to swipe and loop. If I loaded all the slides at the start (even without the images), the web page get too heavy, so I decided to load only 5 slides I change the image as I loop and update.
any thoughts or workarounds?

**Comment by sconix** [comment]
If you are using hundreds of images you definitely want to use lazy loading, even without swiper loading so many images at the same time would cause problems. You can also always just render the active slide + few slides around it with simple ngIf stuff. Other than that I am no expert in using the Swiper this is just a wrapper as said (just loads Swiper and passes in the configuration Angular style). In our application we only load 10-30 slides and only some of the have images and only "optimization" needed is the simple ngIf optimization to not render all slides content only visible ones. Although even without the optimization there is no performance issues.
