### ISSUE TITLE
Swiper Object not passed in to events

### ISSUE THREAD

**Issue by wkaskie** [zefoy/ngx-swiper-wrapper#114]
Hi,

i am using the slideChange event like this:

`<swiper [config]="config" (slideChange)="onChange()"`

Normally, the API passes in the swiper object so that you can do things like:
`function onChange(swiper) { actIdx = swiper.activeIndex(); }`

But it appears that nothing is passed in.  Am I doing something wrong or is this a bug?

Thanks,
Wayne

**Comment by sconix** [comment]
That changed with Swiper 4, the swiper object is not anymore passed to events (at least not to all). This wrapper wraps all parameters from Swiper events into the output event so if its not there then Swiper is not sending it. You can get the swiper object easily by saving the reference to the directive.

**Comment by wkaskie** [comment]
Thanks! I didn't realize that had changed with v4. I only just recently upgraded to v4 a few weeks ago.

The good news is that for the specific use-case I mentioned, you guys have that (index) attribute that works perfectly.

Thanks for building this!
