### ISSUE TITLE
Angular error when using the config parameter 'slidesPerGroup' with directive

### ISSUE THREAD

**Issue by gitdisrupt** [zefoy/ngx-swiper-wrapper#118]
Angular version: 5
ngx-swiper version: 5.3.1

When using the directive option:
```
<div class="swiper-container" [swiper]="config" [(index)]="index">
          <div class="swiper-wrapper">
                <div class="swiper-slide"> slide text</div>
                <div class="swiper-slide"> slide text</div>
                <div class="swiper-slide"> slide text</div>
...
```

In my config i am attempting to use the `slidesPerGroup` parameter, and when it is set to any number > 1, paginating causes Angular to throw the following error:

`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'index: 4'. Current value: 'index: 14'`

If i remove the 2-way binding attribute for index:  _[(index)]="index"_ then the instance of the swiper works OK without issue.

I would assume though, if we want the ability to move the swiper to the active index, we need that 2 way binding attribute to be set, so ANY help at all greatly appreciated.

**Comment by sconix** [comment]
Are you changing / setting the value of index manually in the code?

**Comment by gitdisrupt** [comment]
no, the error noted was just using the example you provide on the github info page.

i am working as we speak and about to test setting the active index using the setIndex method you describe in the read me ... so i do not yet know if it works ... ill update this comment shortly ...

**Comment by gitdisrupt** [comment]
OK here is what i found out ... to be specific about what i did to get the error above ...

if i try to bind the index to one property set in my component, for example:
`public myindex:number;`
and then attempt to use your 2-way binding attribute to update it like so:
`<div class="swiper-container" [swiper]="config" [(index)]="myindex">`
As noted above, as soon as i paginate the swiper, i get that `ExpressionChangedAfterItHasBeenCheckedError` error which breaks the swiper instance.

However .... if i remove the short hand and use 2 different properties to track and set the index, then everything works, like so for example:
```
public currentIndex:number;
public setIndex:number;
<div class="swiper-container" [swiper]="config" [index]="setIndex" (indexChange)="updateIndex($event)">
...
updateIndex(val) {
  this.currentIndex = val;
}
```

And finally ... a separate but possibly related problem regarding your directive methods ...

When i add a reference `#mySwiper`using `@ViewChild` to the directive like so:
```
<div #mySwiper class="swiper-container" [swiper]="config">
...
@ViewChild('mySwiper') mySwiper;
```
attempting to fire the setIndex() method does not work, for example, the following:
`this.mySwiper.setIndex(14);`
results in the following error:
`this.mySwiper.setIndex is not a function`

**Comment by gitdisrupt** [comment]
to be specific about what i did to get the error above ...

**First, an important note:** this error _only_ occurs when setting the `slidesPerGroup` to a value greater than 1, like 4 for example. So note, that in my config, i have it set as follows:

```
public config: SwiperConfigInterface = {
                direction: 'horizontal',
                centeredSlides: false,
                slidesPerView: 4,
                slidesPerGroup: 4,
...
```

if i remove the `slidesPerGroup` parameter, then everything i am about to outline below works without any errors.

Ok, so with that set ...

if i then try to bind the index to one property set in my component, for example:
`public myindex:number;`

and then attempt to use your 2-way binding attribute to update it like so:
`<div class="swiper-container" [swiper]="config" [(index)]="myindex">`

As noted above, as soon as i paginate the swiper, i get that `ExpressionChangedAfterItHasBeenCheckedError` error which breaks the swiper instance.

Again, note, that error fires when paginating. In that example, i am not attempting to set the index there at all. 

If i remove the 2-way data binding attribute` [(index)]="myindex"`, then the swiper works when paginating without any errors.

Alternatively .... if i use 2 different properties to track and set the index, and remove the shorthand version of 2-way data binding, then everything also still works, like so for example:
```
public currentIndex:number;
public setIndex:number;
...
<div class="swiper-container" [swiper]="config" [index]="setIndex" (indexChange)="updateIndex($event)">
...
updateIndex(val) {
  this.currentIndex = val;
}
```

And finally ... a separate but possibly related problem which may or may not need to be a seperate issue all together regarding your directive methods ...

When i add a reference `#mySwiper`using `@ViewChild` to the directive like so:
```
<div #mySwiper class="swiper-container" [swiper]="config">
...
@ViewChild('mySwiper') mySwiper;
```
attempting to fire the `setIndex()` method does not work, for example, the following:
`this.mySwiper.setIndex(14);`

results in the following error:
`this.mySwiper.setIndex is not a function`

**Comment by sconix** [comment]
Ok so there might be some issue in the wrapper then, could you try to replicate the issue with the Plunker template to be sure?

About the setIndex you need to reference the directive and not the element, like this: #mySwiper="ngxSwiper"

**Comment by gitdisrupt** [comment]
will do ... update coming...

**Comment by gitdisrupt** [comment]
Well .. looking at your plunker template here :http://plnkr.co/edit/5eGsfBasinjUBWYEcNx8?p=preview

Without changing anything, the directive version is not working?

**Comment by sconix** [comment]
You can add observer: true to the config to make the directive work. I will update the template as soon as I have time.

**Comment by gitdisrupt** [comment]
Thank you! For the time being i have been able to make use of this wrapper without a need for the 2-way binding for the index!

EXCELLENT work, thank you again!

**Comment by Hess-Gregory** [comment]
I have the same problem and I start to pull my hair!

Error : 
```
'swiper' is not a known element:
1. If 'swiper' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.ng(0)
```
ControlAvatarModule :

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ControlAvatarComponent } from './control-avatar.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { ButtonsModule, WavesModule, CardsModule,  ModalModule} from 'angular-bootstrap-md';

import { SwiperModule, SwiperConfigInterface,
    SWIPER_CONFIG } from 'ngx-swiper-wrapper';

const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
    observer: true,
    direction: 'horizontal',
    threshold: 50,
    spaceBetween: 5,
    slidesPerView: 1,
    centeredSlides: true
  };


@NgModule({
  imports: [
    CommonModule,
    NgbModule,
    FormsModule,
    ReactiveFormsModule,
    ButtonsModule,
    WavesModule,
    CardsModule,
    ModalModule,
    SwiperModule
 ],
  declarations: [ControlAvatarComponent],
  exports: [ControlAvatarComponent],
  providers: [

    {
        provide: SWIPER_CONFIG,
        useValue: DEFAULT_SWIPER_CONFIG
      }
  ],
})
export class ControlAvatarModule {}
```
ControlAvatarComponent: 

```
import { AfterViewInit, Component, OnInit, Renderer2 } from '@angular/core';
import { ControlAvatarService } from './control-avatar.service';
import { ActivatedRoute, Router  } from '@angular/router';
import { SwiperComponent, SwiperDirective, SwiperConfigInterface,
    SwiperScrollbarInterface, SwiperPaginationInterface } from 'ngx-swiper-wrapper';

@Component({
  selector: 'app-control-avatar',
  templateUrl: './control-avatar.component.html',
  styleUrls: ['./control-avatar.component.scss']
})

export class ControlAvatarComponent implements OnInit, AfterViewInit {

    disablePicture: any = [];

    public id: string;

public config: SwiperConfigInterface = {
     autoplay: 3000, // Autoplay option having value in milliseconds
     initialSlide: 3, // Slide Index Starting from 0
    slidesPerView: 3, // Slides Visible in Single View Default is 1
    pagination: '.swiper-pagination', // Pagination Class defined
    paginationClickable: true, // Making pagination dots clicable
     nextButton: '.swiper-button-next', // Class for next button
     prevButton: '.swiper-button-prev', // Class for prev button
     spaceBetween: 30 // Space between each Item
   };
```
 avatar.component.html : 
```
  <swiper  [swiper]="config" >
    <div class="swiper-wrapper">
        <div *ngFor="let picture of disablePicture" class="swiper-slide">
            <div class="row send-serve">
                <div class="d1">
                    <div class="flex">
                        <div class="d2 center">
                            <form (ngSubmit)="activate(picture.id)">
                                <img class="pictures2 d-block mx-auto mb-4 image img-fluid"
                                [src]="picture.url"
                                [alt]="picture.description"/>

                                <div class="flex image-list">
                                    <button class="btn btn-success valid-btn" type="button" type="submit">
                                        activer
                                    </button>
                                    <button class="btn btn-danger valid-btn" (click)="delete(picture.id)">
                                        supprimer
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </swiper>
```

**Comment by aarji** [comment]
Try this
```
<swiper [config]="config" [index]="index" (indexChange) = "indexChange($event)">
  <div>slide1</div>
  <div>slide2</div>
  <div>slide3</div>
</swiper>

  index = 0;

  indexChange(e: number): void {
    setTimeout(() => {
        this.index = e;
    });
    // console.log(e)
  }
```
