### ISSUE TITLE
Async datas + slidesPerView + loop = Swiper go crazy

### ISSUE THREAD

**Issue by adrienlamotte** [zefoy/ngx-swiper-wrapper#119]
Hello !

I spent the night trying to fix this... But I couldn't find a way to make this work.

Here is a plunker : http://plnkr.co/edit/EGDkngY7gkWlpU1UDDPa?p=preview
As you can see, the slider go wild ! It starts at the last slide, and doesn't work at all when you try to navigate.

Even without the loop, the slider start at the last slide (but navigation seems ok).

Do you have any idea on how I could fix that ?
Thank you for your help.

**Comment by adrienlamotte** [comment]
@sconix  Thank you for you answer. 
I already tried to update after the slider is rendered, but I does not work...
I saw there is an config option to not init the slider at all (`init: false`). But is there a way to initialize the slider from your wrapper ?

Option 2 : sorry to ask, but do you know any other Angular 5 project (without jQuery) that handle `slidesPerView` like feature ?

**Comment by sconix** [comment]
You can get the Swiper instance through the directive reference calling the swiper() function offered by the directive. With that you can manually init the Swiper or at least in theory, haven't tried.

I am not aware of any good alternatives for Swiper, we would also be using one if there would be pure Angular version :). So far luckily we haven't had to us those features that cause problems (slidesPerView, loop) so thats also one reason why I haven't had to look into this problem more to try to find a workaround for the wrapper or even a bug fix PR for the Swiper.

**Comment by adrienlamotte** [comment]
Thank you @sconix.
I does seems to work like this, with `init:false` in the option :

```
// After you populate your slides array
setTimeout(()=>{
    this.producersSlider.directiveRef.swiper().init();
}, 0);
```

Hope they'll fix that anyway !
