### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by AKlaus** [zefoy/ngx-swiper-wrapper#12]
Thank you for the wrapper. It's a viable alternative to [angular2-swiper](https://github.com/ksachdeva/angular2-swiper).
However, this wrapper seems doesn't a NPM package. Could you please create one or point me to it?

**Comment by sconix** [comment]
The current package is angular2-swiper-wrapper. I am in process of migrating my library names form angular2 -> ngx so that they are less confusing when Angular4 is out. So soon there will be the npm package under this name, but for now you can use the angular2-swiper-wrapper.
