### ISSUE TITLE
Getting error ERROR in Error: Metadata version mismatch for module 

### ISSUE THREAD

**Issue by ishan123456789** [zefoy/ngx-swiper-wrapper#120]
To elaborate here is the error I'm getting:

> ERROR in Error: Metadata version mismatch for module E:/xampp/htdocs/havemybooks/node_modules/ngx-swiper-wrapper/dist/ng
x-swiper-wrapper.d.ts, found version 4, expected 3, resolving symbol ComponentModule in E:/xampp/htdocs/havemybooks/src/
app/component/component.module.ts, resolving symbol ComponentModule in E:/xampp/htdocs/havemybooks/src/app/component/com
ponent.module.ts

My `ng -v` result
`@angular/cli: 1.4.2
node: 6.10.3
os: win32 x64
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4`

**Comment by sconix** [comment]
As the error says version mismatch, read the first couple lines of the readme :)
