### ISSUE TITLE
SSR error - Dom7.css - window is not defined

### ISSUE THREAD

**Issue by stephenlautier** [zefoy/ngx-swiper-wrapper#124]
Hi,

We are using SSR with Swiper, however we are getting the following error:

### Error
![image](https://user-images.githubusercontent.com/3908723/35684865-7392470e-0768-11e8-9d8f-37a2acd2d1da.png)
****

The following is from were its being caused

### Step1
![image](https://user-images.githubusercontent.com/3908723/35684898-8a995b7c-0768-11e8-85bb-35e4121dd427.png)

### Step2
The cause
![image](https://user-images.githubusercontent.com/3908723/35684927-9982f67a-0768-11e8-8168-d9446a6e5eb8.png)

Any way to fix this?

**Angular: 5.2.2**
**ngx-swiper-wrapper: 5.3.1**

**Comment by sconix** [comment]
This is just a wrapper so you need to ask that in the Swiper issues.

**Comment by adrienlamotte** [comment]
Hello @stephenlautier !
I have the same error on SSR... Did you found any workaround ?

**Comment by stephenlautier** [comment]
@sconix I know its a wrapper but I thought it might be in your interest as well since when used with angular's SSR it throws the error. Or someone else might have already fixed it or found a way around it.

@adrienlamotte unfortunately not yet

**Comment by adrienlamotte** [comment]
@stephenlautier I posted a temporary fix here : https://github.com/zefoy/ngx-swiper-wrapper/issues/127
