### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by adrienlamotte** [zefoy/ngx-swiper-wrapper#127]
Hello !

So... As I can read on the Swiper repo issues, they don't care about SSR at all.

Maybe an idea would be to just not initialize Swiper if you're not in a browser... I have made some tries, and it does seems to work. I'd love to have you feedback about that.

It's pretty simple, in `swiper.directive.ts` and `swiper.component.ts` : 
```
  constructor(@Inject(PLATFORM_ID) private platform: Object, ...) {}

  ngAfterViewInit() {
    // If we are not in a browser, don't do anything
    if (!isPlatformBrowser(this.platform)) return false;
    
    // Swiper Init
    ...

   }
```

What do you think ?

**Comment by sconix** [comment]
At least what I see from Swiper code is that it has proper window / document handling for SSR and 4.0 version changelog said to bring SSR support. So I would not say that they don't care about SSR at all. The SSR bugs that has been reported I cannot find a reason for them in the Swiper code, but I haven't tried SSR yet myself to see what is really going on in the Swiper. I would love to get simple reproduction repository so I could have a look myself before adding any quick workarounds.

**Comment by sconix** [comment]
I will include this workaround for next release, but in the meantime if somebody could provide me with minimal SSR reproduction repository/package I would appreciate it.

**Comment by adrienlamotte** [comment]
Hello @sconix,
Sorry, spent the last night on SSR and was a little upset...
I say "_they don't care about_" because SSR subjects are closed often without an answer. That's too bad...
I posted a new issue on Swiper side anyway.

And I created a repo for you to test SSR with your wrapper : https://github.com/adrienlamotte/angular-swiper-ssr-error

Thank you :)

**Comment by sconix** [comment]
Thanks, I will have a look at that in day or two and most likely make a new release during next week with the above fix unless I don't find another solution.

**Comment by sconix** [comment]
I will make a new release with the suggested fix until Swiper is fixed.

**Comment by RuiEEE** [comment]
Is it possible to make a similar fix for the angular 4.x.x versions?

**Comment by sconix** [comment]
I am not too keen on improving old versions but I guess I could since this is so small change.

**Comment by sconix** [comment]
There is now 4.9.0 out with the same fix for the SSR environment.

**Comment by wildlifechorus** [comment]
@sconix Does not work on 4.9.0.

```
node_modules/swiper/dist/js/swiper.js:4497
            var ua = window.navigator.userAgent.toLowerCase();
                     ^

ReferenceError: window is not defined
```

I tried to add more of these but no luck.

```
    if (!isPlatformBrowser(this.platformId)) {
      return false;
    }
```

The issue is probably on the `swiper.directive.ts` since it imports `import * as Swiper from 'swiper';`

And then uses it here:

```
      if (this.runInsideAngular) {
        this.swiper = new Swiper(element, options);
      } else {
        this.zone.runOutsideAngular(() => {
          this.swiper = new Swiper(element, options);
        });
      }
```

@adrienlamotte You have any solution for this? I've been around this for a week now :(

**Comment by adrienlamotte** [comment]
@wildlifechorus sorry I don't have any project with Angular 4 and SSR to test sorry... 
You could make a reproduction repository so we can help you... ?

**Comment by sconix** [comment]
Ok so Swipee 3.x is not SSR friendly as i suspected so you need to update to angular 5.

**Comment by slimge** [comment]
Same with Angular Universal. This is how I fixed ngx-swiper issues:
```
ngAfterViewInit(): void {
    if (isPlatformBrowser(this.platformId)) {
      this.swipeConfig = {
        direction: 'horizontal',
        initialSlide: 0,
        updateOnWindowResize: true,
        preloadImages: false
      };
      this.eventReplayer.replayAll();
      this.cd.markForCheck();
    }
  }
```
I'm using preboot and just replayed All events to the client side.
