### ISSUE TITLE
Can't bind another swiper as control

### ISSUE THREAD

**Issue by raphzandrade** [zefoy/ngx-swiper-wrapper#130]
I am trying to bind two swipers using the directive approach like this: 

`       this.photoSwiper.swiper().params.controller.control = this.thumbSwiper.swiper();
        this.thumbSwiper.swiper().params.controller.control = this.photoSwiper.swiper();
        this.photoSwiper.update();
        this.thumbSwiper.update();` 

Using some logs, i verified that they are being set, but it won't work as expected. 
There's anything i should be aware of or am i doing it wrong? 
Thanks in advance!

**Comment by sconix** [comment]
What is the params there? By looking at the Swiper example I don't see that sort of call used.

**Comment by raphzandrade** [comment]
Oh, you are right. My mistake. 

Doing `this.photoSwiper.swiper().controller.control = this.thumbSwiper.swiper(); ...`  worked just fine!

Thanks :-)
