### ISSUE TITLE
Horizontal bullet pagination on swiper component not working in IE

### ISSUE THREAD

**Issue by artjoman** [zefoy/ngx-swiper-wrapper#131]
When testing Swiper wrapper with IE or Edge browsers, pagination is not working, if following items are selected:
- Pagination
- Horizontal

Swiping over pagination works though, so it seems to be a conflict with 2 added Event listeners ( Touch and Click )

**Comment by sconix** [comment]
There is only click handler in the pagination bullets. Anyway I will have look at what is causing the problem.

**Comment by sconix** [comment]
It seems that the pointer-event styles are handled bit differently by IE. Will have to come up with another way to implement the bullets.
