### ISSUE TITLE
I have integrated this on Angularjs 4

### ISSUE THREAD

**Issue by akhilsahu** [zefoy/ngx-swiper-wrapper#132]
Error 1

Can't find SwiperScrollbarInterface, SwiperPaginationInterface modules in following

`import { SwiperComponent, SwiperDirective, SwiperConfigInterface,
  SwiperScrollbarInterface, SwiperPaginationInterface  } from 'ngx-swiper-wrapper';
`

Cant find    keyboard: true,
    mousewheel: true,
    scrollbar: false,
    navigation: true,
    pagination: false in SwiperConfigInterface 

 `public config: SwiperConfigInterface = {
    direction: 'horizontal',
    slidesPerView: 1,
    keyboard: true,
    mousewheel: true,
    scrollbar: false,
    navigation: true,
    pagination: false
  };`

app.module.ts

`
import { environment } from './../environments/environment';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { APP_BASE_HREF } from '@angular/common';
import {HttpModule} from '@angular/http';
import {RouterModule } from '@angular/router';
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { NavheaderComponent } from './navheader/navheader.component';
import { SliderComponent } from './slider/slider.component';
import {HomeService} from './services/banner/home.service'

import { SwiperModule, SwiperConfigInterface,
  SWIPER_CONFIG } from 'ngx-swiper-wrapper';

const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
  observer: true,
  direction: 'horizontal',
  threshold: 50,
  spaceBetween: 5,
  slidesPerView: 1,
  centeredSlides: true  ,
    scrollbar: false,
    
    pagination: false
};

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    NavheaderComponent,
    SliderComponent
  ],
  imports: [
    BrowserModule,HttpModule,
    RouterModule.forRoot([
    {path:'', component: HomeComponent 
	}
    ]),    SwiperModule 
 
  ],
  providers: [ {
      provide: SWIPER_CONFIG,
      useValue: DEFAULT_SWIPER_CONFIG
    },{
            provide: APP_BASE_HREF,
            useValue: '/' + (window.location.pathname.split('/')[1] || '')
        },
        HomeService 
        ],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**Comment by sconix** [comment]
Those are for 5.x version that uses Swiper 4. The 4.x version uses Swiper 3 so follow the correct documentation.

**Comment by akhilsahu** [comment]
Ok I have tried this but there a issue the slider image does not changes automatically or manually either way it does not change.But as soon as I open console (ctrl+shift+I) it start to work correcly

**Comment by sconix** [comment]
Since you are dynamically changing swiper slides you need to use observer: true config or call update manually after slides are rendered.

**Comment by akhilsahu** [comment]
Thanks that solved the issue
observer: true
