### ISSUE TITLE
when you click on the slide items. how to make a slide transition

### ISSUE THREAD

**Issue by VCodepp** [zefoy/ngx-swiper-wrapper#139]
after clicking on the slide item. resize. the slide automatically switches how it looks to be

**Comment by sconix** [comment]
There is a configuration option in the Swiper for that so have a look at the Swiper documentation, this is only a wrapper library so all Swiper related usage questions are resolved by looking the Swiper documentation.

**Comment by VCodepp** [comment]
Ok thx
