### ISSUE TITLE
Uncaught Module xx not present.

### ISSUE THREAD

**Issue by adshrc** [zefoy/ngx-swiper-wrapper#14]
Hi,

i'm expecting this error, when i try to access to my freshly-built angular2 project. When i remove the `SwiperModule` and the `<swiper></swiper>` directives, everything loads fine - so it is definitely related to the swiper-wrapper.

I'm using the seed from mgechev/angular-seed which uses SystemJS for loading external modules.

The swiper-wrapper is bundled as follows:
```
{
          name: 'angular2-swiper-wrapper',
          path: `${this.NPM_BASE}angular2-swiper-wrapper/bundles/angular2-swiper-wrapper.umd.js`,
          packageMeta: {
            main: '../dist/index.js', //tried almost every file from dist/
            defaultExtension: 'js'
          }
}
```

The interesting thing is that the same error occurs, when i delete the whole package definition.

**Comment by sconix** [comment]
With systemjs you need to use the umd bundles not the dist directory. So either use the minified or not minified bundle.

**Comment by adshrc** [comment]
Sorry, the comment is not clear enough. I tried almost every file from dist and bundles (including `bundles/angular2-swiper-wrapper.umd.js`). It doesn't matter which one I try, the swiper-wrapper won't be loaded.

**Comment by sconix** [comment]
Then you have some other error in your configuration. I will push an update for the example with systemjs config file soon once I get it working. I still have some issue with the latest systemjs version.

**Comment by sconix** [comment]
Basically the correct configuration is for map:
 'angular2-swiper-wrapper': 'node_modules/angular2-swiper-wrapper'

And then for packages:
'angular2-swiper-wrapper': {
main: 'bundles/angular2-swiper-wrapper.umd.js',
defaultExtension: 'js'
}

**Comment by adshrc** [comment]
Thanks to @ruffiem, i found a solution that works:

```
{
  name: 'angular2-swiper-wrapper',
  path: 'node_modules/angular2-swiper-wrapper/bundles/angular2-swiper-wrapper.umd.**min**.js'
}
```
