### ISSUE TITLE
index breaks when using slidesPerGroup

### ISSUE THREAD

**Issue by dolanmiu** [zefoy/ngx-swiper-wrapper#144]
When I group my slides, and set index, there is very unpredictable behavior

Sometimes it goes to second slide, sometimes last slide

Here is my config:

```ts
const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
  direction: 'horizontal',
  slidesPerView: 3,
  slidesPerGroup: 3,
  pagination: {
    el: '.swiper-pagination',
    clickable: true
  },
  spaceBetween: 5,
  watchOverflow: true
};
```

html:

```html
<swiper [(index)]="index">
     ...
</swiper>

```
Please help!

**Comment by sconix** [comment]
I will check it as soon as I have time. In the mean time are you using dynamically generated slides? If you are have you called update after slides are in the DOM (also using observer: true in config might help).

**Comment by dolanmiu** [comment]
Nevermind, turns out it was an error in my app, closing

However, there is another issue, will created new issue
