### ISSUE TITLE
swiper component not be recognized

### ISSUE THREAD

**Issue by vincejordan2** [zefoy/ngx-swiper-wrapper#146]
Hi all:
I  tried to integrate ngx-swiper-wrapper library into my NG 6 project.
But I could not make my application work with it.
I followed the steps described in "Installing and usage":
1. npm install ngx-swiper-wrapper --save
2. In my app.module.ts,  followed with the tutorial, import 'SwiperModule ' and other stuff.
3. In my HTML file, add swiper component like this:
  <swiper class="swiper-container" [config]="config" (indexChange)="onIndexChange($event)">
    <div *ngFor="let slide of slides" class="swiper-slide">
      <div>
        {{slide}}
      </div>
    </div>
  </swiper>
However, my application is still not working, and the errors show like below:

```
>  Can't bind to 'config' since it isn't a known property of 'swiper'. ("
> <div class="content-container">
>   <swiper class="swiper-container" [ERROR ->][config]="config" (indexChange)="onIndexChange($event)">
>     <div *ngFor="let slide of slides" class"): ng:///DashboardModule/LayerOneContainerComponent.html@7:35
> 'swiper' is not a known element:
> 1. If 'swiper' is an Angular component, then verify that it is part of this module.
> 2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
> <div class="content-container">
```

It seems that swiper tag could not be recognized. 
So far, I have not ideas with what steps I might lost to do. If you have any information for this. please let me know. Thanks!

**Comment by vincejordan2** [comment]
sconix : 
Yes, I tried this. But I still could not get this worked.
I have no ideas why my app is failed to integrate ngx-swiper-wrapper.

**Comment by sconix** [comment]
Is it possible that you have some other library or component that also uses swiper as component name? Other than that I am out of ideas, you could try to also look into the example app that is an NG 6 cli project to look for clues about what might be wrong in your setup.

**Comment by vincejordan2** [comment]
I check my app, there is no duplicated name as swiper.
If is possible that I forget to install any dependency library?
I still have no ideas to figure it out

**Comment by sconix** [comment]
Npm takes care of the dependencies. Does your application has multiple modules? If yes then naturally importing the swiper module is not enough, it needs to be exported as well.

**Comment by JerinJ** [comment]
Even i'm getting the same issue. 

Adding to the cause, if i use it as a directive its says `swiper` is not a known component.

**Comment by sconix** [comment]
That just tells that you have not imported the module, i.e. its not available in the module you are trying to use it.

**Comment by JerinJ** [comment]
Issue was resolved when imported explicitly in child modules too. Missed it while adding dependencies.
Thanks @sconix

**Comment by Hess-Gregory** [comment]
I have the same problem and I start to pull my hair!

Error : 
```
'swiper' is not a known element:
1. If 'swiper' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.ng(0)
```
ControlAvatarModule :

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ControlAvatarComponent } from './control-avatar.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { ButtonsModule, WavesModule, CardsModule,  ModalModule} from 'angular-bootstrap-md';

import { SwiperModule, SwiperConfigInterface,
    SWIPER_CONFIG } from 'ngx-swiper-wrapper';

const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
    observer: true,
    direction: 'horizontal',
    threshold: 50,
    spaceBetween: 5,
    slidesPerView: 1,
    centeredSlides: true
  };


@NgModule({
  imports: [
    CommonModule,
    NgbModule,
    FormsModule,
    ReactiveFormsModule,
    ButtonsModule,
    WavesModule,
    CardsModule,
    ModalModule,
    SwiperModule
 ],
  declarations: [ControlAvatarComponent],
  exports: [ControlAvatarComponent],
  providers: [

    {
        provide: SWIPER_CONFIG,
        useValue: DEFAULT_SWIPER_CONFIG
      }
  ],
})
export class ControlAvatarModule {}
```
ControlAvatarComponent: 

```
import { AfterViewInit, Component, OnInit, Renderer2 } from '@angular/core';
import { ControlAvatarService } from './control-avatar.service';
import { ActivatedRoute, Router  } from '@angular/router';
import { SwiperComponent, SwiperDirective, SwiperConfigInterface,
    SwiperScrollbarInterface, SwiperPaginationInterface } from 'ngx-swiper-wrapper';

@Component({
  selector: 'app-control-avatar',
  templateUrl: './control-avatar.component.html',
  styleUrls: ['./control-avatar.component.scss']
})

export class ControlAvatarComponent implements OnInit, AfterViewInit {

    disablePicture: any = [];

    public id: string;

public config: SwiperConfigInterface = {
     autoplay: 3000, // Autoplay option having value in milliseconds
     initialSlide: 3, // Slide Index Starting from 0
    slidesPerView: 3, // Slides Visible in Single View Default is 1
    pagination: '.swiper-pagination', // Pagination Class defined
    paginationClickable: true, // Making pagination dots clicable
     nextButton: '.swiper-button-next', // Class for next button
     prevButton: '.swiper-button-prev', // Class for prev button
     spaceBetween: 30 // Space between each Item
   };
```
 avatar.component.html : 
```
  <swiper  [swiper]="config" >
    <div class="swiper-wrapper">
        <div *ngFor="let picture of disablePicture" class="swiper-slide">
            <div class="row send-serve">
                <div class="d1">
                    <div class="flex">
                        <div class="d2 center">
                            <form (ngSubmit)="activate(picture.id)">
                                <img class="pictures2 d-block mx-auto mb-4 image img-fluid"
                                [src]="picture.url"
                                [alt]="picture.description"/>

                                <div class="flex image-list">
                                    <button class="btn btn-success valid-btn" type="button" type="submit">
                                        activer
                                    </button>
                                    <button class="btn btn-danger valid-btn" (click)="delete(picture.id)">
                                        supprimer
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </swiper>
```

**Comment by sconix** [comment]
The line `<swiper  [swiper]="config" >` does not look correct at all.

**Comment by Hess-Gregory** [comment]
Thanks for the response, but it doesn't help me ...

**Comment by sconix** [comment]
Well see README about how to use the component. There is no input named swiper, its config.

**Comment by Hess-Gregory** [comment]
> Well see README about how to use the component. There is no input named swiper, its config.

I see that you are very kind and very helpful in your answers.
I want to tell you that I have read REDME, and that my code comes in part from REDME, but this document, it seems to be weak in information  !

**Comment by sconix** [comment]
FYI Github issues is not meant to be a support forum, the README has the needed information (I know its not the most informative, but I rather but my limited time towards code than documentation). Also the example app has working example so having the need to tell something that is available in two places and another is something that can be even copy pasted feels bit waste of my time. So I just hope that pointing to right direction is enough reason to re-read your code with extra care, but since that is not the case here is the same info with exact code changes:

Change this line:
<swiper [swiper]="config" >

To:
<swiper [config]="config" >

As said in the README and shown by the example app :)

**Comment by Hess-Gregory** [comment]
I did not invent :
`<div class = "swiper-container" [swiper] = "config" [(index)] = "index">`

Since it comes from the readme, I thought well not to be crazy to invent properties that do not exist, be sure to go see the  [README.md](https://github.com/zefoy/ngx-swiper-wrapper) :

------>

**Swiper directive can be used in correctly structured div element with optional custom 
configuration:**
```
<div  class="swiper-container" [swiper]="config" [(index)]="index">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      Swiper slide content
    </div>
  </div>

  <div class="swiper-scrollbar"></div>
  <div class="swiper-pagination"></div>

  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>
```


That said, I still tried with : `<div  class="swiper-container" [config]="config" [(index)]="index">`

Without any success, it does not take the "config" property, the images do not scroll, and the arrows do not work, the cursor remains blocked on the first image.

It would be interesting for the developer to update his readme because it is incomplete and has obsolete information which misleads us. 
Very little information on this system is available on the discussion forums. I searched on Google for 2 full days, 
I am looking for another alternative because my client needs his finished product in the coming days. 
swiper is really obsolete!

**Comment by sconix** [comment]
In the code you provided you were using component not directive. So very hard to help you if you are pasting different code here that you are using. And also the error you got is nothing to do with this library, its generic error when you do not have Angular modules correctly setup. So you do not need to search for forums specific to this library. The readme is up-to-date and is complete for all the relevant information to this library (it does leave out the general bits that should be familiar to all Angular developers).

**Comment by MobackVijayKumar** [comment]
Correct, As @sconix is saying that only importing SwiperModule is not enough if you're trying to use swiper in feature module, you need to export SwiperModue from app.module.ts and import it in feature module's ts file.

**Comment by DivGen** [comment]
npm uninstall ngx-swiper-wrapper -> npm install ngx-swiper-wrapper@8.0.2
[https://github.com/zefoy/ngx-swiper-wrapper/issues/247](url)
