### ISSUE TITLE
How to use Two-way Control?

### ISSUE THREAD

**Issue by RezaT1994** [zefoy/ngx-swiper-wrapper#148]
I want something like this page:
[https://github.com/nolimits4web/Swiper/blob/master/demos/300-thumbs-gallery.html](https://github.com/nolimits4web/Swiper/blob/master/demos/300-thumbs-gallery.html)

What is the instance that we have to assign to **controller.control**?
I've passed the component instance but I get **Maximum call stack size exceeded** error.

**Comment by sconix** [comment]
You need to use the swiper instance naturally to update the swiper config on the fly and to reference another swiper instance. You can get the swiper instance through the directiveRef.swiper(). See exaple app for more help about getting the swiper instance

**Comment by RezaT1994** [comment]
Thanks @sconix 
Still the Two-way Control is not working. here is my code:

    @ViewChild('bigSlider') bigSlider: SwiperComponent;
    @ViewChild('thumbsSlider') thumbsSlider: SwiperComponent;

    bigSliderConfig: SwiperConfigInterface = {
        slidesPerView: 1,
        pagination: true,
        grabCursor: true,
        observer: true,
        navigation: {
            nextEl: '.btn-Left',
            prevEl: '.btn-Right',
        },
        autoplay: {
                delay: 5000,
                disableOnInteraction: false,
        }
    };

    thumbsSliderConfig: SwiperConfigInterface = {
        slidesPerView: 4,
        pagination: false,
        observer: true,
        centeredSlides: true,
        slideToClickedSlide: true
    };

    constructor() {
        this.bigSliderConfig.controller = {
            control: this.thumbsSlider.directiveRef.swiper()
        };
        this.thumbsSliderConfig.controller = {
            control: this.bigSlider.directiveRef.swiper()
        };
    }

**Comment by sconix** [comment]
You can not do it in constructor. The Angular things are not initialized in constructor phase. Swiper wrapper does the initialization in ngAfterViewInit since Swiper needs DOM to be ready so the Swiper instance is only available at AfterViewInit.

**Comment by RezaT1994** [comment]
Still no luck. when I console the **this.thumbsSlider.directiveRef.swiper()**, it only has **destroyed:true** in it. I put that in **ngAfterViewInit** method

**Comment by sconix** [comment]
That sounds like you are still changing the configuration on the fly that causes Swiper to be destroyed.

**Comment by RezaT1994** [comment]
I declare the swiper config directly in class and added the **control** property to config in **ngAfterViewInit** method. I get **destroyed: true** again. where should i put the config?

**Comment by RezaT1994** [comment]
Thanks man. this worked **this.bigSlider.directiveRef.swiper().controller**

**Comment by katmilk** [comment]
Hi.
Thanks for the tip - the **ngAfterViewInit** did it for me.

However, I now get an error for **swiper.controller.setTranslate is not a function**

My ngAfterViewInit has:

    ngAfterViewInit() {

      this.bigSlider.directiveRef.swiper().controller = {
          control: this.thumbsSlider.directiveRef.swiper()
      };
      this.thumbsSlider.directiveRef.swiper().controller = {
          control: this.bigSlider.directiveRef.swiper()
      };

    }

**Comment by svitch** [comment]
Hi all!

I have the same issue, only difference is I'm trying to set scrollbar to child element of an instance:
```
  @ViewChild('myswiper') myswiper: SwiperComponent;
  ...
  ngAfterViewInit() {
    this.myswiper.directiveRef.swiper().scrollbar = {
      el: this.myswiper.directiveRef.swiper().$el[0].querySelector('.swiper-scrollbar')
    };
    this.myswiper.directiveRef.update();
  }
```
App has a lot of instances of swiper, each instance with it's own scrollbar.
So with default config, only first initialized scrollbar is working while others are not.

Chrome console tells me:
**▸Uncaught TypeError: swiper.scrollbar.setTranslate is not a function**

**Comment by sconix** [comment]
Have you just tried to update the components Swiper config so that Swiper gets re-initialized? Thats how we do it and it works, not sure if Swiper supports dynamically changing scrollbar.

**Comment by svitch** [comment]
@sconix thank you! Yes, it's working now.
I moved from component to directive and attached scrollbar as in demo:
```
constructor() {
  this.config.scrollbar = this.scrollbar;
  this.show = true;
}
```
For this issue:
> App has a lot of instances of swiper, each instance with it's own scrollbar.
> So with default config, only first initialized scrollbar is working while others are not.

I had to change the `scrollbar.el` to id:
```
this.config.scrollbar = {
  el: '#swiper_' + this.item.id + '_scrollbar',
  hide: false,
  draggable: true
};
```

otherwise I had only first initialized scrollbar visible and each swiper attached it's own scrollbar handlers to it. So it was like I move it and each swiper moved along with it.

**Comment by andreyzenkov** [comment]
@sconix @RezaT1994  Please advise, I have tried to update basic example from the package and getting the same problem, as @katmilk. Here the code:
<pre>
import { Component, ViewChild, AfterViewInit } from '@angular/core';
import { SwiperComponent, SwiperConfigInterface } from 'ngx-swiper-wrapper';

@Component({
  selector: 'my-app',
  moduleId: 'src/app/app.component',
  templateUrl: 'app.component.html',
  styleUrls: [ 'app.component.css' ]
})
export class AppComponent implements AfterViewInit {
  public slides = [
    'First slide',
    'Second slide',
    'Third slide',
    'Fourth slide',
    'Fifth slide',
    'Sixth slide'
  ];

  public bigSliderConfig: SwiperConfigInterface = {
    a11y: true,
    direction: 'horizontal',
    slidesPerView: 1,
    pagination: false,
    navigation: true,
    grabCursor: true,
    observer: true,
  };

  public thumbsSliderConfig: SwiperConfigInterface = {
    slidesPerView: 4,
    pagination: false,
    observer: true,
    slideToClickedSlide: true
  };

  @ViewChild('bigSlider') bigSlider?: SwiperComponent;
  @ViewChild('thumbsSlider') thumbsSlider?: SwiperComponent;

  constructor() {}

  ngAfterViewInit() {
    this.bigSlider.directiveRef.swiper().controller = {
      control: this.thumbsSlider.directiveRef.swiper()
    };

    this.thumbsSlider.directiveRef.swiper().controller = {
      control: this.bigSlider.directiveRef.swiper()
    };
  }
}
</pre>
```
<div class="box-container" fxLayout="column" [ngStyle.lt-sm]="'min-height: 800px;'">
  <div class="horizontal-container" fxLayout="row" fxLayout.lt-sm="column" fxLayoutAlign="stretch" fxFlex="auto">
    <div class="vertical-container" fxLayout="column" fxLayoutAlign="stretch" fxFlex="100%">
      <div class="content-container" fxLayout="column" fxLayoutAlign="stretch" fxFlex="auto">
        <swiper #bigSlider class="swiper-container" fxFlex="auto" [config]="bigSliderConfig">
          <div *ngFor="let slide of slides" class="swiper-slide">
            <div fxLayout="column" fxLayoutAlign="center center" fxFlexFill>
              {{slide}}
            </div>
          </div>
        </swiper>
      </div>
      <div class="content-container">
        <swiper #thumbsSlider class="swiper-container" fxFlex="auto" [config]="thumbsSliderConfig">
          <div *ngFor="let slide of slides" class="swiper-slide">
            <div fxLayout="column" fxLayoutAlign="center center" fxFlexFill>
              {{slide}}
            </div>
          </div>
        </swiper>
      </div>
    </div>
  </div>
</div>
```

**Comment by andreyzenkov** [comment]
If assign in this way, all works:
<pre>
ngAfterViewInit() {
    this.bigSlider.directiveRef.swiper().controller.control = this.thumbsSlider.directiveRef.swiper();
    this.thumbsSlider.directiveRef.swiper().controller.control = this.bigSlider.directiveRef.swiper();
}
</pre>

**Comment by kvnol** [comment]
@andreyzenkov Thanks, @andreyzenkov. It's work!

**Comment by Sebiworld** [comment]
If anyone stumbles across this and tries to get controller work with the newest version: I needed to change @andreyzenkov 's ngAfterViewInit-code to get it working:

```typescript
ngAfterViewInit() {
    this.bigSlider.swiperRef.controller.control = this.thumbsSlider.swiperRef;
    this.thumbsSlider.swiperRef.controller.control = this.bigSlider.swiperRef;
}
```
