### ISSUE TITLE
interface SwiperRenderSlideFunction is wrong?

### ISSUE THREAD

**Issue by rayer4u** [zefoy/ngx-swiper-wrapper#149]
I use ngx-swiper-wrapper with 'virtual' feature, there is a problem.

in swiper.interfaces.ts
```
export type SwiperRenderSlideFunction = (index: number) => HTMLElement;
```
in latest swiper [document](http://idangero.us/swiper/api/#virtual) the renderSlide type is "function(slide, index)"

**Comment by sconix** [comment]
It seems that I have missed that change, will release a fix now.
