### ISSUE TITLE
Loop bugged

### ISSUE THREAD

**Issue by papzaktroy** [zefoy/ngx-swiper-wrapper#15]
loop: true seems to work with alot of bugs

**Comment by sconix** [comment]
Those are most likely bugs with the swiper library itself. At least there seems to be few issues open for it regarding loop parameter.

**Comment by papzaktroy** [comment]
I got it to work on the example though, so it seems to be a bug within my application, this is the code:

`<swiper [config]="config">
  <div *ngFor="let movie of top5Movies?.results | slice:0:5; let i = index">
    <div class="hero" [style.background-image]="'url(https://image.tmdb.org/t/p/original'+movie.backdrop_path+')'">
      <div class="row">
        <div class="container">
          <div class="row">
            <div class="content">
              <div class="col-lg-12">
                <h1>{{movie.original_title}}</h1>
                <p>
                  <span class="genre" *ngFor="let id of movie.genre_ids">
                    {{moviesService.getGenre(id)[0]?.name}}
                  </span>
                </p>
                <a class="trailer" (click)="onClickTrailer(movie.id, i)">
                  Watch Trailer <div class="play"><i class="fa fa-play" aria-hidden="true"></i></div>
                </a>
                <p>{{i}}</p>
              </div>
            </div>
            <div class="video" *ngIf="selectedVideo[i] !== undefined">
              <iframe *ngIf="selectedVideo[i] !== undefined" [src]="'http://www.youtube.com/embed/' + selectedVideo[i][0]?.key + '?html5=1&autoplay=1' | safeUrl"></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</swiper>`
