### ISSUE TITLE
can't use it as component to implement scroll container demo of swiper

### ISSUE THREAD

**Issue by RookieLittleFatty** [zefoy/ngx-swiper-wrapper#151]
using the component like that will calculate the height of the content with class 'swiper-slide', but it is equal to the height of wrapper, so  it will be weird, it can scroll by mousewheel, but i can not drag it to bottom. 
![image](https://user-images.githubusercontent.com/32049377/40763949-73090164-64d9-11e8-8e7f-2998a36d51c1.png)
and when i drag it will display like that;
![image](https://user-images.githubusercontent.com/32049377/40763975-9f3e9bcc-64d9-11e8-8ad6-39d3c6841070.png)
Did i make any mistake? can you give me some suggestions?

**Comment by sconix** [comment]
How are you making the slides? If you are using ngFor or other async ways you need to either use observer: true in the config or call update manually for the Swiper once DOM is ready.

**Comment by RookieLittleFatty** [comment]
Thank you for your reply!  Actually i add the observer: true to the config, but it still doesn't work. and to describe the problem, i make a simple demo with angular-cli project.  Since i can't visit plunker because of the network problem, i paste the code of every file. The following link is the swiper demo , which is the effect i want to implement.

http://idangero.us/swiper/demos/160-scroll-container.html

app.module.ts:
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {SWIPER_CONFIG, SwiperConfigInterface, SwiperModule} from 'ngx-swiper-wrapper';


import { AppComponent } from './app.component';
const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
  direction: 'vertical',
  freeMode: true,
  slidesPerView: 'auto'
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    SwiperModule
  ],
  providers: [{provide: SWIPER_CONFIG, useValue: DEFAULT_SWIPER_CONFIG}],
  bootstrap: [AppComponent]
})
export class AppModule { }


app.component.html
<header class="header"></header>
<div class="content">
  <swiper>
    <div>
      <ul class="list">
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
      </ul>
    </div>
  </swiper>
</div>
<footer class="footer"></footer>

app.component.css
.header{
  position: fixed;
  height: 44px;
  left:0;
  right:0;
  top:0;
  background:#ee7700;
  padding:0;
  margin:0;
}
.footer{
  position: fixed;
  height: 50px;
  left:0;
  bottom:0;
  right:0;
  background:#ccc;
}
.content{
  position: absolute;
  left: 0;
  right:0;
  top: 0;
  margin: 44px 0 50px 0;
  bottom:0;
}
.list{
  width: 90%;
  margin: 0 auto;
  padding:0;
}
.list-li{
  height: 96px;
  margin: 10px auto;
  border-radius: 4px;
  background: lightblue;
  list-style: none;
  padding: 20px;
  box-sizing: border-box;
}

**Comment by RookieLittleFatty** [comment]
Thank you for your reply! Actually i add the observer: true to the config, but it still doesn't work. and to describe the problem, i make a simple demo with angular-cli project. Since i can't visit plunker because of the network problem, i paste the code of every file. The following link is the swiper demo , which is the effect i want to implement.

http://idangero.us/swiper/demos/160-scroll-container.html

app.module.ts:
`
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {SWIPER_CONFIG, SwiperConfigInterface, SwiperModule} from 'ngx-swiper-wrapper';


import { AppComponent } from './app.component';
const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
  direction: 'vertical',
  freeMode: true,
  slidesPerView: 'auto'
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    SwiperModule
  ],
  providers: [{provide: SWIPER_CONFIG, useValue: DEFAULT_SWIPER_CONFIG}],
  bootstrap: [AppComponent]
})
export class AppModule { }

`
app.component.html
`
<header class="header"></header>
<div class="content">
  <swiper>
    <div>
      <ul class="list">
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
        <li class="list-li">test</li>
      </ul>
    </div>
  </swiper>
</div>
<footer class="footer"></footer>
`
app.component.css

`
.header{
  position: fixed;
  height: 44px;
  left:0;
  right:0;
  top:0;
  background:#ee7700;
  padding:0;
  margin:0;
}
.footer{
  position: fixed;
  height: 50px;
  left:0;
  bottom:0;
  right:0;
  background:#ccc;
}
.content{
  position: absolute;
  left: 0;
  right:0;
  top: 0;
  margin: 44px 0 50px 0;
  bottom:0;
}
.list{
  width: 90%;
  margin: 0 auto;
  padding:0;
}
.list-li{
  height: 96px;
  margin: 10px auto;
  border-radius: 4px;
  background: lightblue;
  list-style: none;
  padding: 20px;
  box-sizing: border-box;
}

`

**Comment by RookieLittleFatty** [comment]
Thank you for your reply! Actually i add the observer: true to the config, but it still doesn't work. and to describe the problem, i make a simple demo with angular-cli project. Since i can't visit plunker because of the network problem, i paste the code of every file. The following link is the swiper demo , which is the effect i want to implement.

http://idangero.us/swiper/demos/160-scroll-container.html

app.module.ts:
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {SWIPER_CONFIG, SwiperConfigInterface, SwiperModule} from 'ngx-swiper-wrapper';

import { AppComponent } from './app.component';
const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
direction: 'vertical',
freeMode: true,
slidesPerView: 'auto'
};

@NgModule({
declarations: [
AppComponent
],
imports: [
BrowserModule,
SwiperModule
],
providers: [{provide: SWIPER_CONFIG, useValue: DEFAULT_SWIPER_CONFIG}],
bootstrap: [AppComponent]
})
export class AppModule { }

app.component.html
![image](https://user-images.githubusercontent.com/32049377/40777006-0e7bf820-64ff-11e8-9b43-17a7b791ae0a.png)

app.component.css

.header{
position: fixed;
height: 44px;
left:0;
right:0;
top:0;
background:#ee7700;
padding:0;
margin:0;
}
.footer{
position: fixed;
height: 50px;
left:0;
bottom:0;
right:0;
background:#ccc;
}
.content{
position: absolute;
left: 0;
right:0;
top: 0;
margin: 44px 0 50px 0;
bottom:0;
}
.list{
width: 90%;
margin: 0 auto;
padding:0;
}
.list-li{
height: 96px;
margin: 10px auto;
border-radius: 4px;
background: lightblue;
list-style: none;
padding: 20px;
box-sizing: border-box;
}

**Comment by sconix** [comment]
Its rather hard to spot any problems in the code so you would need to replicate it in the stackblitz demo (link in readme) for me to be able to help you more.

**Comment by RookieLittleFatty** [comment]
Sorry, i also can't visit stackblitz, but i put my demo in my github, this is the link: https://github.com/RookieLittleFatty/ngx-swiper-demos
After run that , you may discover that it can't drag to scroll . Did i make any mistake?

**Comment by sconix** [comment]
Your styles are off, as you can see from the swiper demo it overrides the styles for the slide. The slide needs to have height auto and no max-height styles for it to work.

**Comment by RookieLittleFatty** [comment]
I didn't override the slide's height and max-height. All css i had written is in the app.component.css. 
And i  think the height and max-height added by the ngx-swiper-wrapper component.  Or I make a mistake,  maybe i don't get you fully.  Could you please explain it in more detail or tell me what can i do to solve it? 
Thank you very much!

**Comment by RookieLittleFatty** [comment]
Thank you for your help. I've already solve the problem. I knew the problem was about the componet's height and max-height all the time, but i  did't know why and when the component add them, and at the beginning, i didn't kown how to overwrite the css of swiper component in my component. After seaching , i find the way to overwrite them and now it worked. Thank you very much.

**Comment by Topiya** [comment]
Can anyone help me know how to overwrite the css of swiper ?
