### ISSUE TITLE
Pagination bullets don't work using keyboard

### ISSUE THREAD

**Issue by byblik** [zefoy/ngx-swiper-wrapper#153]
Hello! 
I'm stuck with issue raised by your wrapper, not library. 
For pagination I set clickable to "true", but bullets doesn't work correctly with keyboard. 
Let's refer to your demo https://zefoy.github.io/ngx-swiper-wrapper/. User can click on bullets and slider will show appropriate page, good. User also can set focus on a bullet using tab button on keyboard. But he cannot choose an image by pressing Enter.
I looked into swiper library demo http://idangero.us/swiper/demos/  to see how it works there (vertical slider, custom pagination examples). It works fine both with mouse and keyboard. 
Also I noticed that you somehow add span element with swiper-pagination-handle class which seems to ruin this functional. For instance if I render bullet with my own function like it's done in custom pagination example:
```
renderBullet: function (index, className) {
    return '<span class="' + className + '">' + (index + 1) + '</span>';
}
```
then user can choose image using keyboard but somehow he cannot click on bullet any more.

**Comment by sconix** [comment]
The component has custom bullet rendered, if you need the Swiper default one use either the directive or override the bullet rendered in the config. I can have a look at some point if I can make the component bullets work with keyboard, but its not as high priority so for now you need to do one of those I suggested.

**Comment by byblik** [comment]
As I mentioned custom rendered bullet stops working with mouse, though starts working with keyboard.

**Comment by sconix** [comment]
Ok I missed that bit of information, but ok then you might need to use the directive until I have time to check the issues with the components custom rendered settings.

**Comment by byblik** [comment]
@sconix thanks, just managed to make it work using directive. I only had apply default swiper theme.

**Comment by sconix** [comment]
Good to here, I will check the component issue during this month, but can not give any specific date since there is holidays coming up etc. so not sure when I have time to check this, but I will keep the issue open until I have time to fix this.

**Comment by byblik** [comment]
@sconix thanks

**Comment by sconix** [comment]
I just tried the example app and the keyboard control works also with the component. And if you check the example app the keyboard control is a separate configuration from the pagination so did you have your app configured correctly?

**Comment by sconix** [comment]
I added support for a11y config option for the component so when a11y is enabled the component also adds the necessary attributes for the tab focus / enter to work. I will release new version in few minutes.
