### ISSUE TITLE
A problem shows when I use npm install ngx-swiper-wrapper.

### ISSUE THREAD

**Issue by kinmy** [zefoy/ngx-swiper-wrapper#155]
Volumetric volume /work/ dense forest project /token_web/node_modules/ngx-swiper-wrapper/tsconfig.json. Specify "include" path "[" * * / *"] ", "exclude" path for "[". / dist"] ".

**Comment by sconix** [comment]
Are you using unsupported typescript version? You should use the typescript version that Angular supports.

**Comment by kinmy** [comment]
I use typescript^2.7.2

**Comment by sconix** [comment]
Ok, then I have no idea what could be wrong in your setup.

**Comment by kinmy** [comment]
My problem has been resolved! thx for your help!
