### ISSUE TITLE
using ES-module?

### ISSUE THREAD

**Issue by kukac7** [zefoy/ngx-swiper-wrapper#159]
all modules are now included.

https://github.com/zefoy/ngx-swiper-wrapper/blob/a70984a9201db549d47d59011263c42bec08d5f5/src/index.d.ts#L1

can somehow not be solved that only some modules are included?
http://idangero.us/swiper/api/#custom-build

the `dist` file is still too large. 😞

**Comment by sconix** [comment]
I don't know how one could make a angular component that would dynamically import the modules.

**Comment by kukac7** [comment]
> In case you use it as an ES module make sure:
> you have enabled Babel or Buble to transpile it to ES5 syntax,

no old browsers support. 😞
