### ISSUE TITLE
[runInsideAngular]

### ISSUE THREAD

**Issue by papzaktroy** [zefoy/ngx-swiper-wrapper#16]
Anyone has an example for this?

[runInsideAngular]  // Run Swiper function calls inside the angular zone.

**Comment by sconix** [comment]
You just add [runInsideAngular]="true" for the element and then all Swiper initialization etc. will cause angular change detection to be run.

**Comment by papzaktroy** [comment]
Ive tried for a long time, couldnt figure it out do you perhaps have an easy example?

**Comment by papzaktroy** [comment]
Would really help me out here!

**Comment by sconix** [comment]
I mean that you just add it as normal input for the element: <swiper [runInsideAngular]="true" ...>...</swiper>
Works the same when using directive as well.

**Comment by papzaktroy** [comment]
I mean where do i call a swiper function? Normally u call them like this:

mySwiper.slideTo(index, speed, runCallbacks);

But since we don't define the swiper instance i have no clue how to approach it

**Comment by sconix** [comment]
I don't see how that is relevant to your original question :) The runInsideAngular is just a parameter to disable the change detection optimizations of the library.

Your question is more of a basic angular 2 question, but in short you use ViewChild to get the reference to the component and then you can call the functions provided by the component. Under that reference you get also access to the 'swiper' pointer which can be used to call all of the swiper functions etc. Example app uses the ViewChild to control the swiper.

**Comment by papzaktroy** [comment]
Thanks alot, got it working now. Seems like the problem was that my component that i used the swiper in was also named SwiperComponent... Pretty stupid
