### ISSUE TITLE
The incoming swiper parameter is lost as a function of renderCustom

### ISSUE THREAD

**Issue by Akumuliation** [zefoy/ngx-swiper-wrapper#160]
rewrite this:
export declare type SwiperRenderCustomFunction = (current: number, total: number) => string;

to 
export declare type SwiperRenderCustomFunction = ( swiper: object, current: number, total: number ) => string;

**Comment by sconix** [comment]
Thanks it seems that API or at least the docs have changed at some point. I will make the change for the upcoming new release.

**Comment by sconix** [comment]
This is fixed in the soon to be released version.
