### ISSUE TITLE
parameter "pagination"

### ISSUE THREAD

**Issue by ShenAlfred** [zefoy/ngx-swiper-wrapper#162]
I set the parameter pagination, but it never shows.

const SWIPER_CONFIG: SwiperConfigInterface = {
    direction: 'horizontal',
    pagination: {
        el: '.swiper-pagination',
        type: 'bullets',
    }
};

"ngx-swiper-wrapper": "^4.9.0" is used

**Comment by sconix** [comment]
You are using really old version of this wrapper and I believe that version was still using Swiper 3.x so you need to use that configuration format.
