### ISSUE TITLE
Getting error swiper.component.css.map

### ISSUE THREAD

**Issue by ishan123456789** [zefoy/ngx-swiper-wrapper#167]
> ERROR Something went wrong please try again later!
> ERROR { Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'swiper.component.css.map'
> Error: Cannot match any routes. URL Segment: 'swiper.component.css.map'
>     at ApplyRedirects.noMatchError (E:\xampp\htdocs\havemybooks\dist\server.js:146214:16)
>     at CatchSubscriber.selector (E:\xampp\htdocs\havemybooks\dist\server.js:146195:29)
>     at CatchSubscriber.error (E:\xampp\htdocs\havemybooks\dist\server.js:29486:31)
>     at MapSubscriber.Subscriber._error (E:\xampp\htdocs\havemybooks\dist\server.js:20931:26)

Here is my configuration:

```
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/platform-server": "^6.0.0",
    "@angular/pwa": "^0.6.8",
    "@angular/router": "^6.0.0",
    "@angular/service-worker": "^6.0.0",
    "@fortawesome/angular-fontawesome": "0.1.0-10",
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@fortawesome/free-brands-svg-icons": "^5.2.0",
    "@fortawesome/free-solid-svg-icons": "^5.2.0",
    "@ng-bootstrap/ng-bootstrap": "^2.2.2",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "@ngx-share/button": "^6.0.1",
    "@ngx-share/buttons": "^6.0.1",
    "@ngx-share/core": "^6.0.1",
    "@nicky-lenaers/ngx-scroll-to": "^0.6.1",
    "angular-froala-wysiwyg": "^2.8.1",
    "angular-io-slimscroll": "^2.3.3",
    "ngx-swiper-wrapper": "^6.2.1",
    "rxjs": "6.0.0",
    "rxjs-compat": "^6.2.1",
    "ti-icons": "^0.1.2",
    "webpack-cli": "^2.0.14",
    "zone.js": "^0.8.26"
```

**Comment by ishan123456789** [comment]
@sconix  Can you please help this is the only blocker in my project left.
No other component or plugin require or produce a dependency on a map
I'm using https://github.com/angular/universal-starter configuration is exactly the same as this project.

**Comment by sconix** [comment]
Sadly I am not familiar with the universal starter so can not help with its configuration. There is no such file or not any reference to such file in the library so hard to see that the problem would be in the library.

**Comment by ishan123456789** [comment]
Thanks for your response @sconix I found the fault `# sourceMappingURL=swiper.component.css.map`
Please search this line in your package and you'll find it's presence in all the js. So I think the fault is in the plugin but can you please tell how to configure my system to solve the issue.

**Comment by sconix** [comment]
In this package there is no such file. I did check the whole dist folder that is shipped with this package and there is no single reference to swiper.component.css.map. So your build setup must be generating it, why I have no idea.
