### ISSUE TITLE
Lazy Loading of dynamic images not showing with "self component navigation"

### ISSUE THREAD

**Issue by sebslgi** [zefoy/ngx-swiper-wrapper#168]
I'm using Swiper Wrapper with lazy loading in a component that dynamically fetch for images from an API (using a `Resolver`), and I found that when the component updates with new data Swiper reacts making the current image disappear, but never show the new one, leaving the `swiper-lazy-preloader` visible for ever (or at least until you swipe).

I replicate the problem here https://stackblitz.com/edit/swiper-is-too-lazy. If you navigate from `/pics/dogs` to `/pics/cats` (or viceversa) you can see the problem.

I already discarded the routing and resolver side, and I check different Swiper configurations (jic) without any success. My wild guess is that this have something to do with the wrapper using `ngZone.runOutsideAngular` for slide updates, but I don't really know much about that yet.
 
I'm not sure if this is an actual bug in the wrapper, in Swiper, or there is something wrong with my code. Any help will be appreciated.

**Comment by sconix** [comment]
The runOutsideAngular is just to avoid unnecessary Angular change detection calls it does not effect the working of Swiper. The problem is most likely that since the component (and Swiper) is not re-created when the route changes, but its slides does change. Swiper does not like almost anything dynamic which makes it bit difficult to use with Angular.

I was able to make your example work by adding call to Swiper instances lazy.load() to force the loading of the active slide after the slides were updated to the dom:

```
ngOnInit() {
    this.route.data.subscribe(data => {
      this.animalName = data.animal.name;
      this.animalImages = data.animal.images;
      this.cdRef.detectChanges();
      if (this.swiperDirectiveRef.swiper()) {
        setTimeout(() => {
          this.swiperDirectiveRef.swiper().lazy.load();
        }, 0);
      }
      // console.log(this.swiperDirectiveRef);
    });
  }
```

So I would say that this is a "feature" of Swiper that it does not like if the content changes dynamically.

**Comment by sebslgi** [comment]
Sorry for the delay.

Thank you very much for the info and the workaround.

I'm closing the issue as resolved :+1:

**Comment by Salman4code** [comment]
Hi @sconix ,
How can I use swiperDirectiveRef in self component navigation will you please elaborate

**Comment by sconix** [comment]
Not sure what do you mean, there are example in example app if you are asking how to use directive ref.

**Comment by Salman4code** [comment]
Hi @sconix ,
i am using like this


<swiper *ngIf="!commonService.showDefaultImage" class="swiper-container" [config]="config" [(index)]="index" (init)="onIndexChange(productDetail.productMediaImage.length)">
                    <div *ngFor="let productMediaImage of productDetail.productMediaImage" class="position-relative">
                        <figure class="lazy-load-min-height">
                            <div class="img-wrapper swiper-lazy">
                                <img [attr.data-src]="productMediaImage.media_url.web.medium" alt="" class="swiper-lazy img-fluid">
                            </div>
                            <div class="swiper-lazy-preloader"></div>
                        </figure>
                    </div>
                </swiper>

in component
import { SwiperDirective , SwiperConfigInterface }  from 'ngx-swiper-wrapper';
  @ViewChild(SwiperDirective) swiperDirectiveRef: SwiperDirective;
public config:SwiperConfigInterface = {
    observer: true,
    direction: "horizontal",
    mousewheel: false,
    scrollbar: false,
    navigation: false,
    pagination: true,
    preloadImages: false,
    lazy:true
  };
console.log('test',this.swiperDirectiveRef) -----> getting undefined
    this.cdRef.detectChanges();
    if (this.swiperDirectiveRef && this.swiperDirectiveRef.swiper()) {
      setTimeout(() => {
        this.swiperDirectiveRef.swiper().lazy.load();
      }, 0);
    }

but i am getting undefined for this.swiperDircetiveRef

**Comment by sconix** [comment]
Thats not how the referencing works in angular. check the example app carefully how to do it. You are trying to reference a component as a directive.

**Comment by Salman4code** [comment]
Hi @sconix ,
i found workaround for it ,
 <swiper #productWrapper *ngIf="!commonService.showDefaultImage" class="swiper-container" [config]="config" [(index)]="index" (init)="onIndexChange(productDetail.productMediaImage.length)">
  <div *ngFor="let productMediaImage of productDetail.productMediaImage" class="position-relative">    <figure class="lazy-load-min-height"> <img [attr.data-src]="productMediaImage.media_url.web.medium" alt="" class="swiper-lazy img-fluid"><div class="swiper-lazy-preloader"></div></figure></div></swiper>

In component
  @ViewChild('productWrapper') public productWrapper: any;

 if (this.productWrapper.directiveRef.swiper()) {
        setTimeout(() => {
          this.productWrapper.directiveRef.swiper().lazy.load();
        }, 0);
      }
but this code not working on ios devices

**Comment by sconix** [comment]
Thats not workaround thas how it should be done. Well at least almost, you can type the productWrapper to be type of SwiperComponent instead of any. If thats not working on iOS devices I suspect that you have found a Swiper bug.

**Comment by Salman4code** [comment]
Hi @sconix I have tried using  productWrapper as type SwiperComponent but it is not working for iOS devices.
@ViewChild('productWrapper') public productWrapper: SwiperComponent;

is there any other way to do it for iOS devices or any Other method for reinitialised swiper on self component navigation.

**Comment by sconix** [comment]
As I said I think that you have run into Swiper bug so you might need to ask around Swiper isues / forums. Since when calling functions from Swiper instance are not working then this wrapper should not have any effect on that specially if they work on desktop.

**Comment by Salman4code** [comment]
Hi @sconix ,
I solved it for iOS devices by updating swiper like this this.productWrapper.directiveRef.swiper().update();

In component
if (this.productWrapper && this.productWrapper.directiveRef.swiper()) {
      // console.log('test',this.productWrapper.directiveRef.swiper().update())
      setTimeout(() => {
        if (this.commonService.isIosDevice()) {
          this.productWrapper.directiveRef.swiper().update();
        }
        this.productWrapper.directiveRef.swiper().lazy.load();
      }, 0);
    }
