### ISSUE TITLE
Don't resize the images when changing device's rotation

### ISSUE THREAD

**Issue by UlisesCeca** [zefoy/ngx-swiper-wrapper#169]
Hello, I am using this great library for my Ionic App.

I'd like to set a fixed size for the pics and that they don't resize when I rotate the App. Id this possible?

Thanks,

**Comment by sconix** [comment]
That is more of an question to Swiper than for this wrapper. But I don't see why you can not just use css to define the size.

**Comment by UlisesCeca** [comment]
I did. But the swiper container keeps allowing me swiping until where the slides with the original size should be which makes me have a white space without any slide if I swipe alot.

I ended up just using Ionic's slides and making a little workarround, thanks.
