### ISSUE TITLE
SwiperDirective for multiple swipers on one page

### ISSUE THREAD

**Issue by WayneKruger** [zefoy/ngx-swiper-wrapper#171]
Not an issue, just a question:

How do I get a SwiperDirective reference to a specific swiper if there are multiple swipers on one page?

Using:
@ViewChild(SwiperDirective) directiveRef?: SwiperDirective;

it seems to return the first swiper.

**Comment by sconix** [comment]
Better to ask in Angular forums / check Angular documentation since the question is not related to this library. Its possible to name the directives and reference them with name instead of class.

**Comment by WayneKruger** [comment]
Thanks @sconix you are right. Should be quite simple actually. Something in the line of:
@ViewChild('id_of_swiper') directiveRef?: SwiperDirective;

Thanks for the help.

**Comment by WayneKruger** [comment]
FYI, to get a QueryList of all the Swipers on the page, use ViewChildren:

import { ViewChildren, QueryList  } from '@angular/core';

@ViewChildren(SwiperDirective) directiveRef?: QueryList<SwiperDirective>;
