### ISSUE TITLE
swiper-pagination-bullets

### ISSUE THREAD

**Issue by sahilkatia** [zefoy/ngx-swiper-wrapper#173]
Not an issue, just a question

I used swiper inside the wrapper of component and I am trying to set swiper-pagination-bullets outside the swiper-wraper but inside the component wraper.  Also, I am trying to change the color of swiper-pagination-bullets

**Comment by sliceofbytes** [comment]
Here is an example: https://stackblitz.com/edit/github-swiper-custom-pagination
