### ISSUE TITLE
Question - SwiperNavigationInterface

### ISSUE THREAD

**Issue by sam11385** [zefoy/ngx-swiper-wrapper#174]
When attempting to implement the swiper navigation interface on the swiper **component** I cannot get class names to pass in.

**_// component.ts_**
```
public config: SwiperConfigInterface = {
    a11y: true,
    keyboard: true,
    mousewheel: false,
    scrollbar: false,
    slidesPerView: 3,
    navigation: true,
    pagination: false,
    autoplay: false,
    centeredSlides: false,
    loop: false
  };
```

```
public navConfig: SwiperNavigationInterface = {
    nextEl: '.next',
    prevEl: '.prev'
  };
```

_**// component.html**_
```
<swiper [config]="config">
  <div class="slide swiper-slide">slide1</div>
  <div class="slide swiper-slide">slide2</div>
</swiper>
```

Utilizing this way is not passing the class names into the next and previous button. Any tips?

**Comment by sam11385** [comment]
Hmmm, ok. I see now that it just finds it. My apologies. So is there a better way to set the CSS class on the buttons? I am using this as an angular component.

**Comment by sconix** [comment]
You just set them normally in the template, what would be better way than normal HTML?

**Comment by sam11385** [comment]
I don't see where you do that in any of your examples when using the swiper wrapper as a component.

It looks like it is possible as a directive.

**Comment by sconix** [comment]
Sorry missed the fact about being component. Yes with component you can not add custom classes, but the buttons do have prev/next classes so they can be separately styled.

If you for some reason need specific classes you can use the directive and provide fully custom elements.

**Comment by sam11385** [comment]
Ok, so the solution for custom buttons - which most companies will want to fit to their branding - is to use the directive. If you use the component version you must set styles in your global style sheets.

**Comment by sconix** [comment]
You can style both the same way there is no difference in that. You just might need to study a bit how styling works in Angular, but there is no difference with styling between component / directive. Only if you for some reason need specific class names on the elements then you need to use directive.
