### ISSUE TITLE
ngx-swipper pagination not working

### ISSUE THREAD

**Issue by JordyGS** [zefoy/ngx-swiper-wrapper#177]
Hi, I'm using the version **^6.4.0** of swiper and I'm having troubles on implementing the pagination.
I have set the configuration like this:

`swiperConfig:SwiperConfigInterface = {
        observer : true,
        direction : 'horizontal',
        slidesPerView : 1,
        pagination : true
    };`

The dom element is recognized and it removes the hidden attribute from it, but it's not displaying any bullet in pagination, its showing an empty div, what am I missing?

**Comment by yuveliremil** [comment]
Hope this will helpful:

`import { Component, OnInit, Input } from '@angular/core';
import { SwiperConfigInterface, SwiperPaginationInterface } from 'ngx-swiper-wrapper';

@Component({
  selector: 'app-main-carousel',
  templateUrl: './main-carousel.component.html',
  styleUrls: ['./main-carousel.component.scss']
})
export class MainCarouselComponent implements OnInit {
  @Input('slides') slides: Array<any> = [];
 
  public config: SwiperConfigInterface = {};

  private pagination: SwiperPaginationInterface = {
    el: '.swiper-pagination',
    clickable: true
  };
  
  constructor() { }

  ngOnInit() { }

  ngAfterViewInit(){
    this.config = {
      slidesPerView: 1,
      spaceBetween: 0,         
      keyboard: true,
      navigation: true,
      pagination: this.pagination,
      grabCursor: true,        
      loop: false,
      preloadImages: false,
      lazy: true,     
      autoplay: {
        delay: 6000,
        disableOnInteraction: false
      },
      speed: 500,
      effect: "slide"
    }
  }

}`


demo: [http://www.emporium.themeseason.com/](http://www.emporium.themeseason.com/)

**Comment by sconix** [comment]
Yes you need to follow Swiper documentation, the pagination needs to be object not boolean.
