### ISSUE TITLE
Handling scroll events in slides

### ISSUE THREAD

**Issue by DoryZi** [zefoy/ngx-swiper-wrapper#178]
Hi, When I have scrollable content in a slide, I "lock the swiper" but it seems that even then I can't get my content to scroll...How do I prevent the swiper from swallowing scroll events and passing them to the content?

**Comment by sconix** [comment]
Events always propagate to parent. So you need to catch them in you scroll area and stop propagation if you do not want them to  reach Swiper.

**Comment by DoryZi** [comment]
Got it thanks, I have another issue I'll open for it.
