### ISSUE TITLE
disable swiper in vertical scroll changes to first slide

### ISSUE THREAD

**Issue by DoryZi** [zefoy/ngx-swiper-wrapper#179]
I am locking the swiper, using disable property (vertical one) on certain action on the slide itself, however when I do change to disable, it moves back to the first slide for some reason..
Why is that?
How can that be avoided?
Is it a bug?

**Comment by sconix** [comment]
Disable property disables whole Swiper, i.e. unloads the Swiper library so everything will get resetted. For disabling certain Swiper functionality you need to look into Swiper documentation.

**Comment by DoryZi** [comment]
I see so the disable is not free the scrolling it means reset the whole thing to the start correct?

**Comment by sconix** [comment]
Not really, things getting reset is just a side product. Its just to disable the whole Swiper, i.e. unload it completely so naturally its state gets resetted.
