### ISSUE TITLE
Dynamic slider update

### ISSUE THREAD

**Issue by wojtekhorembala** [zefoy/ngx-swiper-wrapper#180]
Hi, I saw one problem here which is very similar to mine, but unfortunately the answer did not help me.

I am downloading data dynamically and the slider does not update, the next button is disabled.

My code:

```
  @ViewChild('swiper') swiper: SwiperComponent;
  config: SwiperConfigInterface;
```

```
    this.config = {
      a11y: true,
      direction: 'horizontal',
      slidesPerView: 4,
      keyboard: true,
      mousewheel: true,
      scrollbar: false,
      navigation: true,
      pagination: false,
      spaceBetween: 20,
      autoplay: true,
      grabCursor: true,
    };
```
I am trying to update the slider when I know there are data for sure

```
    const time = timer(5000);
    time.subscribe(() => {
      this.swiper.directiveRef.update();
      console.log('UPDATE');
    });
```
```

<div #swiper class="swiper-wrapper">
        <a  *ngFor="let item of array" class="swiper-slide">
          <div class="item" >
            <div class="info">
              <h4 class="info-title">text</h4>
              <div class="info-product">
                <img src="assets/location.svg">
              </div>
              <div >...</div>
            </div>
          </div>
        </a>
      </div>
```

` TypeError: Cannot read property 'update' of undefined`

**Comment by wojtekhorembala** [comment]
Ok i add observer to config and this run, but after downloading the data the slider is on the last slide.
Can I set the default slide to the first one?

**Comment by sconix** [comment]
Your swiper reference is pointing to a div which is not a SwiperComponent so thats why you are getting the error. Also I am not seeing your whole swiper related code, but I suspect that you are using directive not the component. So that makes two errors in the code. The observer wont work in all cases and Swiper has a bug that sets the last slide active in some cases. If I remember correctly the component should be able to go around that bug, but not sure. Also calling the update might fix the slide index.

**Comment by chakriramoj** [comment]
> Your swiper reference is pointing to a div which is not a SwiperComponent so thats why you are getting the error. Also I am not seeing your whole swiper related code, but I suspect that you are using directive not the component. So that makes two errors in the code. The observer wont work in all cases and Swiper has a bug that sets the last slide active in some cases. If I remember correctly the component should be able to go around that bug, but not sure. Also calling the update might fix the slide index.

Hi Sconix,

As you said, I am stuck at the bug where swiper sets the last slide active when we call swiper.update() . Could you help me to fix this?
