### ISSUE TITLE
Hi @sconix I have tried using  productWrapper as type SwiperComponent but it is not working for iOS devices.

### ISSUE THREAD

**Issue by Salman4code** [zefoy/ngx-swiper-wrapper#182]
@ViewChild('productWrapper') public productWrapper: SwiperComponent;

is there any other way to do it for iOS devices or any Other method for reinitialised swiper on self component navigation.

_Originally posted by @Salman4code in https://github.com/zefoy/ngx-swiper-wrapper/issue_comments#issuecomment-426513859_

**Comment by sconix** [comment]
If you mean that ViewChild reference is not working on iOS but works on other then you should ask around Angular forums that what is going on. The ViewChild is Angular functionality and is not related in any way to this library.
