### ISSUE TITLE
Pagination -> clickable property not working

### ISSUE THREAD

**Issue by ricchadmin** [zefoy/ngx-swiper-wrapper#184]
Hi,
just wanted to ask, that the clickable property on the pagination object is not working as expect. I've tried also in the StackBlitz app and was the same. Maybe a Swiper issue? 

Regards,

Richard

**Comment by sconix** [comment]
It works in the example Stackblitz app. So can you see if you have something differently. If not then maybe share your Stackblitz code so I can have a look.

**Comment by ricchadmin** [comment]
In the example StackBlitz app tried before. I changed the pagination property to this:
`  private pagination: SwiperPaginationInterface = {
    el: '.swiper-pagination',
    type: 'bullets',
    clickable: false
  };`
After toggling the overlay controls the bullet pagination can be clicked like before.

**Comment by sconix** [comment]
Ah I guess you mean that you can not disable it. That seems to be a bug in the component implementation. I will release a fix next week after my holiday is over. Until that you can use directive which wont have this bug or just prevent the click using css styles.

**Comment by ricchadmin** [comment]
Thank you @sconix, have a nice holiday then. For now I'll disable it via css. After you finish, I'll try it.
