### ISSUE TITLE
How to set the index?

### ISSUE THREAD

**Issue by dineshmaths1** [zefoy/ngx-swiper-wrapper#187]
Hii,

I have lots of swiper-slide am giving at the top side name. If i click slide name i wan to go particular slide name?

**Comment by sconix** [comment]
See the Readme and example app for using the API calls.

**Comment by ikrape** [comment]
I what to get the first element of swipper
I did a swipper delete i maked two div the second is hidden and if i swippe an alert of comfirmation is showing if i press ok it deleted and mu issue is how can i do if i press cancell thxxx

**Comment by sconix** [comment]
Sorry but I do not understand your question nor the description of your setup.
