### ISSUE TITLE
onClick, go to particular slide

### ISSUE THREAD

**Issue by sahilkatia** [zefoy/ngx-swiper-wrapper#188]
am trying by below method, but it says cannot read property 'directiveRef' of undefined
`public goToSlide() {
      this.swiper.directiveRerf.swiper.slideTo(3)
  }`

`@ViewChild('swiper') public swiper: any;`

`
<button (click)="goToSlide()">ChangeSlide</button>`

**Comment by sconix** [comment]
See the example app how to use those references.

**Comment by sahilkatia** [comment]
@sconix , I am trying it from yesterday checked whole documentation, even for swiper also, I know I am making some mistake but not sure where. I would appreciate if you can let me know.

**Comment by sconix** [comment]
Your post is not showing the whole code so I can not say the exact problem. Just copy the code from the example app and look Angular ViewChild example/docs and it will work.
