### ISSUE TITLE
if there are swiper on a page, ngx-swiper-wrapper button-prev/next work wrong

### ISSUE THREAD

**Issue by zhouqiujie** [zefoy/ngx-swiper-wrapper#189]
同一个页面有两个滚动，点击一个滚动swiper的左右方向键 能触发另外一个滚动swiper

**Comment by sconix** [comment]
If I understand the problem then you need to use different classes for the prev and next buttons. You can configure the classes in Swiper config and if there are more than one Swiper on a page you need to use unique class names to avoid problems.

**Comment by zhouqiujie** [comment]
I did use uique class names . my config like this 

```
config: SwiperConfigInterface = {
    direction: 'horizontal',
    slidesPerView: 'auto',
    freeMode: true,
    grabCursor: true,
    initialSlide: 0,
    navigation: {
        nextEl: '.swiper-button-next-pricing',
        prevEl: '.swiper-button-prev-pricing'
    }
  };

```

but your code from `swiper.directive.ts` of lib,  only apply `navgation: true`, like this

```
    if (params.pagination === true) {
      params.pagination = {
        el: '.swiper-pagination'
      };
    }

    if (params.navigation === true) {
      params.navigation = {
        prevEl: '.swiper-button-prev',
        nextEl: '.swiper-button-next'
      };
    }
```

**Comment by sconix** [comment]
Thats only if you use true as the value of navigation. Otherwise the configuration is passed to the Swiper as it is given.

**Comment by zhouqiujie** [comment]
You're right. I made a mistake.  I only configure a unique class name in one  Swiper config and use `navigation:true` in another swiper of the same page. Finally, thank you very much
