### ISSUE TITLE
How to get the swiper object?

### ISSUE THREAD

**Issue by dereklin** [zefoy/ngx-swiper-wrapper#19]
In the swiper's documention, it shows how to get the swiper object:
```
  <script>        
  var mySwiper = new Swiper ('.swiper-container', {
    // Optional parameters
    direction: 'vertical',
    loop: true,
    
    // If we need pagination
    pagination: '.swiper-pagination',
    
    // Navigation arrows
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    
    // And if we need scrollbar
    scrollbar: '.swiper-scrollbar',
  })        
  </script>
```
How to get the this object with the wrapper?

**Comment by sconix** [comment]
Both component and directive exposes the Swiper instance as a public variable 'swiper'.

**Comment by dereklin** [comment]
@sconix Let's say in my app.component.html I put:
```
<swiper [config]="config" (indexChange)="onIndexChange($event)">
  <div>
    Swiper content
  </div>
</swiper>
```
How can I get 'swiper' in app.component.ts?

**Comment by sconix** [comment]
Like with any angular component using the ViewChild to get the reference to the element and from there its exposed as 'swiper'.

**Comment by dereklin** [comment]
@sconix Thanks!
In my component.html:
```
<swiper #swiperWrapper [config]="config" (indexChange)="onIndexChange($event)">
  <div class="swiper-content">
    Swiper content 1
  </div>
  <div class="swiper-content">
    Swiper content 2
  </div>
  <div class="swiper-content">
    Swiper content 3
  </div>
</swiper>
<hr/>
<button (click)="goToSlide2()">Go to slide 2</button>
```
In my component.ts:
``
import { Component, ViewChild, ElementRef } from '@angular/core';

@Component({
    selector: 'swiper-demo',
    templateUrl: 'swiper-demo.component.html',
    styleUrls: ['swiper-demo.component.scss']
})
export class SwiperDemoComponent {
  public config: any;

  @ViewChild('swiperWrapper') public swiperWrapper: any;

  constructor() {
    this.config = {

    };
  }

  public onIndexChange(event) {
    console.log(event);
  }

  public goToSlide2() {
    this.swiperWrapper.swiper.slideTo(1);
  }
}
```

**Comment by AlexLomm** [comment]
There is no `swiper` instance on the swiper component when `console.log`-ing it. See:

![screen shot 2017-10-25 at 2 35 36 pm](https://user-images.githubusercontent.com/11467210/31994475-d4d753ee-b991-11e7-9226-0d9887ddbcb0.png)

Am I missing something?

**Comment by AlexLomm** [comment]
It is present in the `directiveRef`, though. So `swiperWrapper.directiveRerf.swiper` should let you access the instance.

**Comment by mozgor** [comment]
It might have change since previous answer, even if it was very useful to find out the exact path.

Currently, you have to use `swiperWrapper.directiveRef.instance` to access the actual `swiper` object mentionned in Swiper API doc.

**Comment by taumartin** [comment]
First:
`import { SwiperDirective } from 'ngx-swiper-wrapper';`

Then:
`@ViewChild(SwiperDirective) directiveRef?: SwiperDirective;`

Lastly:
`this.directiveRef.swiper();`

**Comment by zzmmbb** [comment]
ionic 4
![image](https://user-images.githubusercontent.com/40230597/54573194-4185a100-4a26-11e9-9d3c-3d3716f9c8c8.png)
![image](https://user-images.githubusercontent.com/40230597/54573204-4a767280-4a26-11e9-850d-eb8ee4485d17.png)
![image](https://user-images.githubusercontent.com/40230597/54573210-4fd3bd00-4a26-11e9-92f3-7c068d4dd1ee.png)

**Comment by falk-stefan** [comment]
How can we do this with v7.0.5? None of the appraoches above seem to work.
