### ISSUE TITLE
ERROR TypeError: Cannot read property 'style' of undefined 

### ISSUE THREAD

**Issue by Waanders** [zefoy/ngx-swiper-wrapper#190]
![image](https://user-images.githubusercontent.com/5529063/47964547-fac97880-e03b-11e8-8dd3-1141c87f7247.png)

The component works fine, but after switching, it complains about the style that cannot be found. I tried to import the css, as mentioned in the README, but it keeps giving the same error.

Any thoughts on what could cause this?

**Comment by Waanders** [comment]
Hi Sconix, 

Not that I am aware of. So I used the component approach, which worked fine, but switched to the directive approach for more control. The slides come from an array that is initalized in the ngOnInit. I initalize the Swiper in ngAfterViewInit. After serving, it immediately shows the "cannot read property 'style' of undefined error. 

I am using Swiper 4.4.1. as a dependency, tried with an older version as well, but to no avail.

**Comment by sconix** [comment]
What do you mean that you initialize Swiper in ngAfterViewInit? If the slides array is updated on ngOnInit then that is most likely the problem. The swiper wrapper initializes in ngAfterViewInit since Swiper needs DOM to be ready, so try moving your slides initialization to the ngAfterViewInit.

**Comment by Waanders** [comment]
Looks like that solved it! Thanks for the help and of course for providing this wrapper!
