### ISSUE TITLE
how to disable change slide index when unshift to array of slides?

### ISSUE THREAD

**Issue by SergeyKatugin** [zefoy/ngx-swiper-wrapper#191]
how to disable change slide index when unshift to array of slides?

And another question, is able to set index slide without animation?

**Comment by sconix** [comment]
When you change the slides Swiper needs to re-initialize it self so the index gets resetted. You can just get/set the index after the change or set the current index in the configuration as initial index before you updated slides. That should work.

The setIndex has the speed parameter.
