### ISSUE TITLE
Not hiding pagination when only 1 page available

### ISSUE THREAD

**Issue by Omi0** [zefoy/ngx-swiper-wrapper#196]
I just read this request https://github.com/nolimits4web/swiper/issues/2572 used watchOverflow property and see no difference... Still 1 page displayed.
Any ideas why it might be?

**Comment by sconix** [comment]
I have no idea, not sure why that would help but on the other hand I am not a Swiper expert. Can not think of any reason at least in this library that would cause that so most likely its Swiper problem. At least you can easily work around that problem by modifying the configuration when updating slides.
