### ISSUE TITLE
pagination doesn't work, config is just as yours.

### ISSUE THREAD

**Issue by keandfan** [zefoy/ngx-swiper-wrapper#198]
just as title mentioned , and other function is ok.

**Comment by sconix** [comment]
Can you be bit more specific. How does it not work, what version, component or directive and also still seeing the full config you are using would help.

**Comment by keandfan** [comment]
I consider that I'm'not expressing it clearly,I don't know why I can't see the pagination when setup it .I start a new project, and I still can't see the pagination,the following is the config and the html.
 
![image](https://user-images.githubusercontent.com/37890226/50193679-9277f180-0372-11e9-9ae0-e2e37f437615.png)

![image](https://user-images.githubusercontent.com/37890226/50193622-5775be00-0372-11e9-8c31-ca6d6ffe01ec.png)
![image](https://user-images.githubusercontent.com/37890226/50193631-66f50700-0372-11e9-88da-29430b0356dc.png)
![image](https://user-images.githubusercontent.com/37890226/50193634-6f4d4200-0372-11e9-9ce0-fae221945ab4.png)
![image](https://user-images.githubusercontent.com/37890226/50193639-77a57d00-0372-11e9-87d7-cfd41856748f.png)
![image](https://user-images.githubusercontent.com/37890226/50193643-7bd19a80-0372-11e9-89ca-0269dd697c06.png)

**Comment by keandfan** [comment]
thank you for you response.

**Comment by charpour** [comment]
I have the same problem. When using the "component" approach the pagination shows up as expected. However, when using the directive, even with correct configuration it won't show up. Not sure why that's happening. On StackBlitz it works fine though if I change the type to 'directive' and enable pagination configuration. Could be related to angular version (using angular 7).

**Comment by sconix** [comment]
Have you noticed that with directive you need to load the Swiper stylesheet yourself? Component includes it automatically, but with directive you need to import the stylesheet in your app code.

**Comment by charpour** [comment]
> Have you noticed that with directive you need to load the Swiper stylesheet yourself? Component includes it automatically, but with directive you need to import the stylesheet in your app code.

Indeed I have included the stylesheet in the scss file of my component, same result unfortunately.

**Comment by sconix** [comment]
If you include it in you components file its bound by the angular view encapsulation. So you need to either turn off encapsulation or load the styles in global styles.
