### ISSUE TITLE
swiper-pagination-clickable

### ISSUE THREAD

**Issue by singhsandeepsln** [zefoy/ngx-swiper-wrapper#204]

**Comment by singhsandeepsln** [comment]
Swiper pagination is not clickable am not receiving class '.swiper-pagination-clickable'

**Comment by sconix** [comment]
You need to configure it to be clickable. See Swiper docs.

**Comment by singhsandeepsln** [comment]
I have added but still i am not receiving that class please see what is the issue

`<swiper *ngIf="type == 'component' && show" class="swiper-container" fxFlex="auto" [config]="config" [disabled]="disabled" (indexChange)="onIndexChange($event)" (swiperTransitionStart)="onSwiperEvent('transitionStart')" (swiperTransitionEnd)="onSwiperEvent('transitionEnd')">
            <div *ngFor="let slide of slides" class="swiper-slide">
               <div fxLayout="column" fxLayoutAlign="center center" fxFlexFill>
                  <img src="{{slide.img}}" alt="image missing">
               </div>
            </div>
            </swiper>`


`  public type: string = 'component';

  public disabled: boolean = false;

  public config: SwiperConfigInterface = {
    a11y: true,
    direction: 'horizontal',
    slidesPerView: 1,
    keyboard: true,
    mousewheel: true,
    scrollbar: false,
    navigation: true,
    
  };
  private pagination: SwiperPaginationInterface = {
    el: '.swiper-pagination',
    clickable: true
  };`

**Comment by sconix** [comment]
I do not see pagination configuration in your config.

**Comment by singhsandeepsln** [comment]
Thanks for the prompt support 
i got your point and simply added following code in config and it working -
`   pagination:  {
      el: '.swiper-pagination',
      clickable: true
    }`
