### ISSUE TITLE
How to place Swiper nav arrows outside the swiper-container??

### ISSUE THREAD

**Issue by singhsandeepsln** [zefoy/ngx-swiper-wrapper#205]
Please suggest...

**Comment by sconix** [comment]
Its matter of applying custom styles. I do not have an example available so you might have better luck asking in some generic coding forums etc. I'll leave this open for a while if somebody happens to have an example around.

**Comment by singhsandeepsln** [comment]
Okay Thanks

**Comment by victorcamargos** [comment]
Just put the elements you want to be the arrows outside and set them as prevEl and nextEl at the navigation config.
`<i class="carousel-previous" role="button" aria-label="Previous slide"></i>
<swiper [config]="config">
</swiper>
<i class="carousel-next" role="button" aria-label="Next slide"></i>
`

`config.navigation: {
    nextEl: '.carousel-next',
    prevEl: '.carousel-previous'
}`

**Comment by sperovic** [comment]
> Just put the elements you want to be the arrows outside and...

That is correct only for one instance within the page. If you have two or more, those arrows will control all instances. 
I am also interested in having this feature next to many others offered that aren't as requested or needed.

**Comment by sconix** [comment]
You can always use different classes for different Swiper instances and then the arrows will only control the one instance.

**Comment by MobackChetanKumar** [comment]
Hi All, help me out on this issue I am using two nested swipers in the same component and the structure and the config created in this way but I am facing an issue like the all the pagination elements get added active class by swiper.
https://stackblitz.com/edit/angular-k4dcxw?file=src%2Fapp%2Fapp.component.html
![image](https://user-images.githubusercontent.com/49486326/56454346-d4d72c80-636c-11e9-8d83-3ec565ac65a8.png)
