### ISSUE TITLE
Keyboard navigation not working as expected on multiple instances

### ISSUE THREAD

**Issue by charpour** [zefoy/ngx-swiper-wrapper#206]
When there are multiple swiper instances on the same page and the user attempts to navigate using the keyboard (i.e. configuration **keyboard: true**), the navigation gets applied to all of the active instances.

I've reproduced the issue on stackblitz: https://stackblitz.com/edit/github-b6ommy
Open the app in a new window and try to slide using the keyboard. You'll notice that all of the swiper instances perform the slide.

Now, if keyboard navigation when having multiple instances makes sense, I don't know. Perhaps if the user has focus on a DOM element that belongs to a swiper instance it does?

**Comment by sconix** [comment]
I do not believe that Swiper supports detecting "active" instance for keyboard navigation. So I would believe that you need to implement that yourself, i.e. when clicking or hovering a swiper you set keyboard navigation on for that component and disable it for others etc.

**Comment by charpour** [comment]
Thanks for the prompt reply. I thought such scenario would be supported like it is for mousewheel. Both scenarios seem to be pretty similar, i.e. an input directed to some html component.
