### ISSUE TITLE
Question: Is it possible to disable the swipe functionality when the image is zoomed?

### ISSUE THREAD

**Issue by Riccardo-Andreatta** [zefoy/ngx-swiper-wrapper#207]
When the image is zoomed it is still possible to swipe to next or previous slide by panning over the image: is it possible to disable this sliding to the next slide but keep the panning functionality and the zoom out functionality (so when I zoom out I can still swipe to the other slides)?

**Comment by Ferie** [comment]
Closed without any answer?

At least, are you planning to insert this feature in a future release?

**Comment by sconix** [comment]
This is just a wrapper. What you were asking is question for Swiper and not for this library.
