### ISSUE TITLE
Swiper has different behaviour when using the '--prod' flag

### ISSUE THREAD

**Issue by Dru-S** [zefoy/ngx-swiper-wrapper#208]
I have the following issue:

I have a swiper which behaviour is correct when I serve my Angular project.
When I build or serve it with the `--prod` flag, the swiper behaviour is no longer correct, ad it's different from the serve without the `--prod` flag.
This happens only with a swiper in the entire app, but I can't figure the problem out.
The only thing I've added, it's a function to hide the slides, adding only a class (in this case `_off`) which only gives `opacity: 0` to the slide.

I cannot provide you a working demo of the project, but I can provide you 2 GIF and the configs.

The correct behaviour is:
![image](https://i.imgur.com/jWcj6mY.gif)

The `--prod` (incorrect) behaviour is:
![image](https://i.imgur.com/mI80dmy.gif)

(The GIFs are a little bit slower than the real video, sorry about that)

My config params are:
```typescript
{
  direction: 'vertical',
  slidesPerView: 1,
  mousewheel: {
    invert: true
  },
  effect: 'coverflow',
  coverflowEffect: {
    rotate: 0,
    stretch: 150,
    depth: 170,
    modifier: 1,
    slideShadows : false
  },
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
  },
}
```

If you need also the "custom" function for the `_off` class, here you are:
```typescript
checkSwiper(index, swiper, visibleSlides) {
  let nodes = swiper.swiperSlides.nativeElement.childNodes;
  let slides = [];
  for(let i = 0; i < nodes.length; i++) {
    if (nodes[i].nodeType != Node.TEXT_NODE && nodes[i].nodeType != Node.COMMENT_NODE) {
      slides.push(nodes[i]);
    }
  }
  // Remove hidden class to all slides before the check
  for(let i = 0; i < slides.length; i++) {
    slides[i].classList.remove('_off');
  }
  // Set hidden class to all slides from the first one to the active one
  for(let i = 0; i < index - visibleSlides; i++) {
    slides[i].classList.add('_off');
  }
  // Set hidden class to all slides from the active one to the end
  for(let i = index + (visibleSlides + 1); i < slides.length; i++) {
    slides[i].classList.add('_off');
  }
}
```

Other useful info:
- @angular/cli: **7.3.3**
- ngx-swiper-wrapper: **7.2.1**
- swiper (if you need also this one): **4.5.0**

I hope someone can help me, because I really can't figure it out.

**Comment by sconix** [comment]
That does seem rather odd. The only thing I can think of is some sort of change detection problem. The only difference between the normal and prod build should be that the extra change detection cycle is dropped off. So I would try adding change detector detectChanges call to the functions that changes the swiper elements.

**Comment by Dru-S** [comment]
@sconix Thank you for your answer, I assume the only thing I have to do is wait for your testing, and a solution or an update of the package.
If there's something I can do in order to help, please tell me!
Thanks!

**Comment by sconix** [comment]
I meant that you need to test it in your app, I do not believe it has nothing to do with this library. To me it sounds like a change detection issue in you application. So I could not even test this without a reproduction.

**Comment by Dru-S** [comment]
Ok, so after a lot of debugging and compiling, I found out what causes the wrong behaviuor:
My old HTML was like:
```html
<swiper
	#swiperRequests
	[config]="requestsSwiperConfig"
	[index]="requestsCard.length - 1"
	(indexChange)="checkSwiper($event, swiperRequests, 2)">
	<div class="swiper-slide" *ngFor="let item of requestsCard.reverse()">
		[...]
	</div>
</swiper>
```

I found out that nothing brake if I remove the `*ngFor` and _copy-paste_ the markup in order to have more slides, so like this:
```html
<swiper
	#swiperRequests
	[config]="requestsSwiperConfig"
	[index]="requestsCard.length - 1"
	(indexChange)="checkSwiper($event, swiperRequests, 2)">
	<div class="swiper-slide">
		[...]
	</div>
	<div class="swiper-slide">
		[...]
	</div>
	<div class="swiper-slide">
		[...]
	</div>
</swiper>
```

In the end, the problem was caused by the `reverse()` function, and using the `slice()` function before the `reverse()` function, solves the problem. The actual solution is the following:
```html
<swiper
	#swiperRequests
	[config]="requestsSwiperConfig"
	[index]="requestsCard.length - 1"
	(indexChange)="checkSwiper($event, swiperRequests, 2)">
	<div class="swiper-slide" *ngFor="let item of requestsCard.slice().reverse()">
		[...]
	</div>
</swiper>
```

I don't know if it's the correct solution, maybe reversing the array in the TS without using the `slice()` works as well, and it's more correct than the actual version.

Anyway, thanks for your time!

**Comment by sconix** [comment]
Ah that kinda makes sense, since in debug mode the change detection is run twice so your array always reverted back to correct order, but with aot the change detection is run once so the every second time you array was in wrong order and caused weirdness on the rendering side. At least I think thats what happened. Anyway good that you got it solved.
