### ISSUE TITLE
"Error: Unexpected value 'SwiperModule' imported by the module 'AppModule'. Please add a @NgModule annotation."

### ISSUE THREAD

**Issue by halben** [zefoy/ngx-swiper-wrapper#21]
I noticed there's no ngModule decorator in the swiper.module.d.ts file. Is that expected and Is there a workaround for this issue?

I am currently using Angular version 4.0.0.

**Comment by sconix** [comment]
We are also using the library with 4.0.0 and there are no errors. Are you using the latest version of this library?

**Comment by halben** [comment]
I'm using v4.0.0 of this library.

**Comment by halben** [comment]
Update: 

So it seems to only be breaking if you are using Angular Universal. ** Bummer since I did make a workaround for SSR DOM Manipulation issue **

**Comment by RichieRock** [comment]
Ok, we'll close this for now. I'm sorry we cannot help with issues with angular universal.

**Comment by sconix** [comment]
Swiper wont play nice with Universal, but I am going to check at some point if there is anything that can be done for that problem.

**Comment by halben** [comment]
I look forward to it. 

One way I got it to work was copy the files in the src directory and moved it over to my project; It worked great without any issue.

**Comment by JatinKukreja18** [comment]
So I got the same error and figured out that it was the import path that was wrong. If you are using auto import then this is bound to happen. Please make sure you use this **import { SwiperModule } from 'ngx-swiper-wrapper';**  as the path. Hope is helps.

**Comment by Sherif-fahd** [comment]
for anguler 8 use this version "ngx-swiper-wrapper": "~5.2.1"
