### ISSUE TITLE
how to set height

### ISSUE THREAD

**Issue by yedajiang44** [zefoy/ngx-swiper-wrapper#210]
my html
```html
<swiper [config]="swiperConfig">
  <div *ngFor="let slide of slides" >
    {{slide}}
  </div>
</swiper>
```
my component
```typescript
import {Component, OnInit, ViewChild} from '@angular/core';
import {
  SwiperConfigInterface,
  SwiperComponent,
} from 'ngx-swiper-wrapper';

@Component({
  selector: 'ngx-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  swiperConfig: SwiperConfigInterface;
  slides = [
    'First slide',
    'Second slide',
    'Third slide',
    'Fourth slide',
    'Fifth slide',
    'Sixth slide'
  ];

  constructor() {
  }

  ngOnInit() {
    this.swiperConfig = {
      height:500,//Does not work
      direction: 'horizontal',
      slidesPerView: 1,
      keyboard: true,
      mousewheel: true,
      navigation: true,
      pagination: true,
      // 开启鼠标的抓手状态
      grabCursor: true,
      loop: true,
      autoplay: true,
      speed: 1000,
    }
  }
}
```
Why do I still have full screen after setting the height?

**Comment by sconix** [comment]
The component has some styling to make generic use cases simpler. So you might need to also modify the styles if you are using a component. The other way is to use the directive that does no have any custom styling.

**Comment by ruisilva450** [comment]
Sorry but why this is close?

@sconix the original swiper has the height implemented and it should be used so that we don't need to set custom styling.

**Comment by sconix** [comment]
As said the directive is the pure Swiper implementation i.e. it won't add any styles. The component does add styles to make the most simplest use cases work more easily. There is no way to make styles work for all cases. 

So if you are only interested getting the pure Swiper styles then just use the directive.
