### ISSUE TITLE
Directive hide navigation

### ISSUE THREAD

**Issue by dottodot** [zefoy/ngx-swiper-wrapper#211]
I'm using the directive as per the instructions and all config options work apart from when I set navigation to false it doesn't hide the navigation.

Also ideally I'd like to hide by breakpoint but that doesn't work either. 

```
sliderConfig: SwiperConfigInterface = {
    loop: true,
    navigation: true,
    breakpoints: {
      480: {
        navigation: false
      }
    }
  };
```
Is there something I have to do to make hiding navigation work?

**Comment by sconix** [comment]
When you are using navigation the configuration is passed directly to the Swiper so this wrapper does not effect that case at all. I must say that we are not seeing the navigation even its disabled. Perhaps you have some style overriding Swiper styles that makes them visible?

**Comment by dottodot** [comment]
Ok so it looks like it only possible by doing the following

```
  <div class="swiper-button-prev" [hidden]="config.navigation === false"></div>
  <div class="swiper-button-next" [hidden]="config.navigation === false"></div>
```
only problem with that is if you want to use breakpoints but I guess that can be handled by subscribing to the breakpoints i.e

```
  this.swiper.S_BREAKPOINT.subscribe(resp => {
      //Do something
    });
```
but that only work for resizing the window. 

So I think the only way to properly sort is just adding some css to hide to nav

**Comment by sconix** [comment]
So you are talking about the component? You said you are using the directive... Anyway you can use the directive so breakpoint configuration will work just fine, with the component you might need to make custom media query styles to hide them.

**Comment by dottodot** [comment]
No I'm using the directive.

```
<div class="featured-banner swiper-container" [swiper]="sliderConfig">
  <div class="swiper-wrapper">
    <div class="swiper-slide" *ngFor="let banner of (banners$ | async)">
    </div>
  </div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>
```

**Comment by sconix** [comment]
Ah sorry I was mistaken that the code you added was from the components template, but I see it was from the example app :)

I must say that I am surprised that Swiper does not control the visibility of those elements so I guess the only way is to style them yourself then.
