### ISSUE TITLE
Custom Animation not possible to add for slider

### ISSUE THREAD

**Issue by vidhyasgr** [zefoy/ngx-swiper-wrapper#212]
I am trying to add custom animation for the slider, but i dont find any documentation to add custom animation.

**Comment by sconix** [comment]
You need to ask in the Swiper issues/forums. This is just a wrapper so getting help here for Swiper related questions is a long shot.

**Comment by vidhyasgr** [comment]
actually in normal Swiper, they have support. But in angular 2+/here we dont have that option in SwiperInterface.

**Comment by sconix** [comment]
It does not need to be in the interface for to be able to use it. Interface is just useful for Typescript typing its not restricting what you can pass to the Swiper. What is the missing option you are talking about? I can add it to the interface as well.
