### ISSUE TITLE
'isAtFirst' and 'isAtLast' not getting set?

### ISSUE THREAD

**Issue by arjun-varrier** [zefoy/ngx-swiper-wrapper#218]
Hello,

I am using ngx-swiper-wrapper to display an array of tiles.

I am trying to hide navigation arrows individually based on the position of the swiper.

On initialization of the page, to hide the left arrow (left nav), I used the 'isAtFirst' property, but, upon logging the property, I noticed that its not getting set. I again logged it inside 'reachBeginning' and 'reachEnd' but there too it was logged as 'undefined'?

This is my component - 

`
import {Component, EventEmitter, Input, OnInit, Output, ViewChild} from '@angular/core';
import {SwiperComponent, SwiperConfigInterface} from 'ngx-swiper-wrapper';

@Component({
	selector: 'si-task-list',
	templateUrl: './task-list.component.html',
	styleUrls: ['./task-list.component.less']
})
export class TaskListComponent implements OnInit {

	@ViewChild('swiper') swiper: SwiperComponent;

	@Input() taskList: any;
	@Input() selectedItem: any;

	config: SwiperConfigInterface = {
		a11y: true,
		direction: 'horizontal',
		slidesPerView: 4,
		scrollbar: false,
		navigation: {
			nextEl: '.sl-next',
			prevEl: '.sl-back'
		},
		pagination: false
	};

	constructor() { }

	ngOnInit() {
		console.log('isAtLast = ', this.swiper.isAtLast);
		console.log('isAtFirst = ', this.swiper.isAtFirst);
	}

	reachBeginning (event) {
		console.log('isAtLast = ', this.swiper.isAtLast);
		console.log('isAtFirst = ', this.swiper.isAtFirst);
		console.log(event);
	}

	reachEnd (event) {
		console.log('isAtLast = ', this.swiper.isAtLast);
		console.log('isAtFirst = ', this.swiper.isAtFirst);
		console.log(event);
	}

}
`

This is my HTML -

`
	<swiper [config]="config" style="width: 100%" #swiper (reachBeginning)="reachBeginning($event)" (reachEnd)="reachEnd($event)">
		<div *ngFor="let task of taskList" class="item" [ngClass]="{'task-active': selectedItem === task.taskId}">
			<span>Date: {{ task.visitDateId }}</span>
		</div>
		<button class="sl-back">
			<img class="pagination-icon prev-arrow" src="assets/images/ic-pagination-previous.svg" alt="">
		</button>
		<button class="sl-next">
			<img class="pagination-icon next-arrow" src="assets/images/ic-pagination-next.svg" alt="">
		</button>
	</swiper>
`

ngx-swiper-wrapper version - 5.2.1

Can you please tell me if I missed something? or are the 'isAtFirst' & 'isAtLast' properties actually not setting?

**Comment by sconix** [comment]
Hard to say what is wrong since you are using so old version. Can be bug in the wrapper or in the Swiper. The isAtLast and isAtFirst will just query the information from Swiper. So you can always try getting the Swiper instance reference and check it from there if that works or not then you know is the fault in Swiper or in the wrapper.

**Comment by arjun-varrier** [comment]
Hey, thanks for the prompt reply. 
I guess it was an issue with that version. I upgraded the version to 7.2.1 and it started working. 
Thank you.
