### ISSUE TITLE
How do I reset config settings?

### ISSUE THREAD

**Issue by ozgurtunc93** [zefoy/ngx-swiper-wrapper#220]
Data changes but scroll position does not change when page parameter changes
[foto1](https://i.hizliresim.com/2OYDpO.png)
change page params
[foto2](https://i.hizliresim.com/LvYBjz.png)

swiper-pagination does not reset
```
export class StoreComponent implements OnInit {

 public landConfig: SwiperConfigInterface = {
    pagination: {
      el: '.swiper-pagination', type: 'progressbar',
      dynamicBullets: true,
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    }
  };
}
```

**Comment by sconix** [comment]
Not sure what you mean by changing page params specially since your images are not accessible. But if you are talking about the slide index just set the index to 0 when you change settings.
