### ISSUE TITLE
Won't compile with Ivy enabled

### ISSUE THREAD

**Issue by nisdec** [zefoy/ngx-swiper-wrapper#226]
# 🐞 bug report

### Affected Package
ngx-swiper-wrapper@8.0.0

### Is this a regression?
It works with Ivy disabled.

### Description
This package doesn't seem to be Ivy "ready". Fails to compile.

## 🔬 Minimal Reproduction
**1. Setup a new Angular 8 project with Ivy enabled**
`ng new test-project --enableIvy=true`

**2. Install ngx-swiper-wrapper**
`yarn add ngx-swiper-wrapper`

**3. Setup ngx-swiper-wrapper in app.module.ts**
<pre>
<code>
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { SwiperModule } from 'ngx-swiper-wrapper';
import { SWIPER_CONFIG } from 'ngx-swiper-wrapper';
import { SwiperConfigInterface } from 'ngx-swiper-wrapper';

const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
  direction: 'horizontal',
  slidesPerView: 'auto'
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    SwiperModule,
  ],
  providers: [
    {
      provide: SWIPER_CONFIG,
      useValue: DEFAULT_SWIPER_CONFIG
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
</code></pre>

## 🔥 Exception or Error
<pre><code>
chunk {0} runtime-es2015.703a23e48ad83c851e49.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.efedd750490b14de3f18.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es2015.66a9e684cc8ebe117187.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.09e2c710755c8867a460.css (styles) 0 bytes [initial] [rendered]
Date: 2019-07-12T09:47:56.846Z - Hash: 162d43f4b27871060cb1 - Time: 5341ms

ERROR in Node does not exist: path_to/node_modules/ngx-swiper-wrapper

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.1
Node: 10.15.3
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
ngx-swiper-wrapper                8.0.0

</code></pre>

**Comment by yuniers** [comment]
@sconix I'm experimenting same issue with same dependencies of @nisdec, I'm using Debian 10. 

Please, can you check why it happens?

**Comment by sconix** [comment]
Sorry I do not have time to look into experimental stuff. I will only look to IVY stuff once its released.

**Comment by MarcoSantino** [comment]
+1

**Comment by abouzarSoleymani** [comment]
i have this problem too ..

**Comment by amalshehu** [comment]
ERROR in Node does not exist: */node_modules/ngx-swiper-wrapper
Any workarounds?

**Comment by petebacondarwin** [comment]
Have you tried with the latest `next` release of Angular. This error should no longer appear.

**Comment by petebacondarwin** [comment]
So with the latest version you get a more insightful error:

```
 ERROR in node_modules/ngx-swiper-wrapper/dist/lib/swiper.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class
```

**Comment by vugar005** [comment]
@petebacondarwin  So I tried with angular 9.0.0-next.1. Now it states another problem.
```
ERROR in The target entry-point "ngx-swiper-wrapper" has missing dependencies:
 - swiper/dist/js/swiper.js
```
I also installed swiper manually by `npm i swiper`. It did not solve the problem. @sconix do you have a solution about this?

**Comment by petebacondarwin** [comment]
@vugar005 please see https://github.com/angular/angular/issues/32097

**Comment by JoostK** [comment]
Hi folks, just wanted to let you know that https://github.com/angular/angular/pull/32181 was just merged and it's expected to be in the next release of Angular `9.0.0-next.3`.

**Comment by nisdec** [comment]
@petebacondarwin @JoostK Thank you guys 👍 . I will close the issue for now since the fix will be released with Angular 9, when Ivy is not anymore considered "experimental".
