### ISSUE TITLE
Cube effect does not work properly

### ISSUE THREAD

**Issue by yestaro** [zefoy/ngx-swiper-wrapper#227]
Try it on https://stackblitz.com/github/zefoy/ngx-swiper-wrapper/tree/master/example
and change the config as 
`  public config: SwiperConfigInterface = {
    effect: 'cube',
    grabCursor: true,
    cubeEffect: {
      shadow: true,
      slideShadows: true,
      shadowOffset: 20,
      shadowScale: 0.94,
    },
    pagination: {
      el: '.swiper-pagination',
      clickable: true
    }
  };`

The slides count is incorrect, and third slide position become to first. something wrong.
try to rotate and only work on first time.

**Comment by sconix** [comment]
This is just a wrapper so if you are sure that you have called update after dynamic DOM changes then its a bug in Swiper.

**Comment by yestaro** [comment]
Hi, thanks for your reply, I am sure it's not a bug in swiper. 
I have test on pure js version swiper, and inspect the element as below
`<div class="swiper-wrapper" style="transform-origin: 50% 50% -150px; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(0deg);">`

also test ngx-swiper-wrapper on stackblit, the element as below
`<div class="swiper-wrapper" style="transform-origin: 50% 50% -161px; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(-540deg);">`

with the same config, just initialize, but their **rotateY()** is different. 

and I don't understand **called update after dynamic DOM...**, after read the documentation, seems update() provided by the directive. But I use it in COMPONENT USAGE

**Comment by yestaro** [comment]
Update my test result. It worked on DIRECTIVE USAGE, but failed on COMPONENT USAGE.

**Comment by sconix** [comment]
The API provided by the directive is accessible for the component as well. Since you had success with directive I will have a look if there is something that the component can do for this. Can you say the version you are using since if its the latest I am suspecting that this could be also a bug due to the Angular 8 changes regarding ViewChild usage.

**Comment by yestaro** [comment]
I am using Angular 8.0.1, and "ngx-swiper-wrapper": "^8.0.0", test on chrome 75.0.3770.100

**Comment by sconix** [comment]
At the first look not sure if there is anything I can do for this. It seems that the ng-content projection is causing problems for the cube effect. So for now the only way might be to use the directive.

**Comment by sconix** [comment]
Found the real issue in the component, will be releasing a bug fix that fixes this issue.
