### ISSUE TITLE
Multiple sliders on the same page

### ISSUE THREAD

**Issue by thecoconutstudio** [zefoy/ngx-swiper-wrapper#232]
I have two sliders on the page, they both work independently fine when swiping but when using the controls

```
  <div class="controls">
        <div class="position">
          {{currentSlide}} / {{slides.length }}
        </div>
        <div class="swiper-button-prev"><img src="/assets/img/gallery-arrow-left.svg"></div>
        <div class="swiper-button-next"><img src="/assets/img/gallery-arrow-right.svg"></div>
      </div>
```

They both move at the same time

**Comment by sconix** [comment]
You should see the Swiper documentation about how to tell them to use different controls by providing different class configuration for them.

**Comment by sanctus671** [comment]
You might need to make sure you are calling the specific slider. Give each slider container a unique ID and call it like so in your ts file:

```
    public scrollNext(id){
        const swiper = document.querySelector("#" + id + " .swiper-container");
            swiper["swiper"].slideNext();
    }
```
