### ISSUE TITLE
Not able to use swiper component and directive inside same component

### ISSUE THREAD

**Issue by NishadAbdul** [zefoy/ngx-swiper-wrapper#239]
Hi,

First of all, I am new to angular and using swiper too..

I am unable to use the ngx-swiper-wrapper component and directive within a single screen. For. e.g. Home component and inside it a router-outlet is defined which will render the screen based on the route change.

Home component has a swiperwith coverflow effect and child has a normal gallery slide. Swiper on home screen works well but other one fails. Any help would be appreciated?

Home.component.ts & html

`public homeConfig: SwiperConfigInterface = { keyboard: { enabled: true, }, hashNavigation: true, preventClicks: false, effect: 'coverflow', coverflowEffect:  { rotate: 0, stretch: 0, depth: 100, modifier: 6, slideShadows : true, }, direction: 'horizontal', slidesPerView: 'auto', centeredSlides: true, initialSlide: 3, slideToClickedSlide: true, grabCursor: true, simulateTouch: true };`

```
<swiper [config]="homeConfig" [useSwiperClass]="swiper" >[(index)]="activeIndex">
<div *ngFor="let list of lists" [attr.data-hash]="'/'+list.url">
              <i class="{{list.icon}} fal" aria-hidden="true"></i>
              <h5>{{list.title}}</h5>
            </div>
</swiper>
```

Child.component.ts

```
public childConfig: SwiperConfigInterface = {
    slidesPerView: 4,
    navigation: true,
    breakpoints: {
      1200: {
          slidesPerView: 3
      }
    }
  };
```

 `<div class="swiper-container open_account_wrp" [swiper]="childConfig">sliders goes here</div>`

Is this due to parent SwiperConfigInterface conflicting with the child one?

**Comment by sconix** [comment]
It should be perfectly fine to use both on the same component. So what do you mean the other one fails?

The only thing to remember when using multiple swiper instances is that for the control blocks you need to use different classes. Swiper uses classes to find the components so if same class names are used for both then problems occure.

**Comment by NishadAbdul** [comment]
Issue got resolved after setting observeParents as true. Thanks for the feedback @sconix
