### ISSUE TITLE
Problem with Subpixel

### ISSUE THREAD

**Issue by nischi** [zefoy/ngx-swiper-wrapper#243]
Hi,

We have a problem with some supixels on .swiper-wrapper. Swiper use here 100% for the width, which is fine. Thats exactly 833.5px for example, depends on screen of course.

So but the width they give to .swiper-slide is always a int instead of float. Which means 834px.

That ends that after 10 slides we miss 5px. Which cut the content.

**Normal:**
![image](https://user-images.githubusercontent.com/2036054/70322106-7abaa700-1829-11ea-848a-0dd5a13899d8.png)

**Cutted**
![image](https://user-images.githubusercontent.com/2036054/70322109-7d1d0100-1829-11ea-85f4-7c4e144fb063.png)

My suggestion are that we use floating pixels for .swiper-slide

**Comment by sconix** [comment]
This is just a wrapper for Swiper so this won't have anything to do with the slide sizes. So this should be directed to the Swiper itself.

**Comment by nischi** [comment]
Okay I will add it there. Thanks.

**Comment by nischi** [comment]
swiper/issues#3392
