### ISSUE TITLE
Lazy loading not working in angular 8.

### ISSUE THREAD

**Issue by sean-medialab** [zefoy/ngx-swiper-wrapper#249]
Configs:

    direction: 'horizontal',
    slidesPerView: 1,
    scrollbar: false,
    navigation: {
      prevEl: '.left-arrow',
      nextEl: '.right-arrow'
    },
    pagination: true,
    preloadImages: false,
    lazy: {
       loadPrevNext: true,
       loadPrevNextAmount: 1
    },
    loop: true
  
Relevant html:

   <div class="swiper-wrapper">

       <div class="swiper-slide" *ngFor="let image of images">
             <img [attr.data-src]="image.FullUrl">
                <div class="swiper-lazy-preloader swiper-lazy-preloader-white">
        </div>
    </div>

Only one image shows and swiper just swipes first image and doesn't load anymore. Just shows background of swiper.

**Comment by ahmadmi** [comment]
for me too.

**Comment by sean-medialab** [comment]
@sconix I've updated both ngx-swiper-wrapper package and my application to angular 9. 

The image below is my configuration in my app.module.ts:
![image](https://user-images.githubusercontent.com/60228260/74157020-876ec900-4be5-11ea-879a-fa5bbdb0fc05.png)

Below is the html (I am using the directive):
![image](https://user-images.githubusercontent.com/60228260/74157155-ca30a100-4be5-11ea-93a9-6a1fe77158b1.png)

This image is what the slider looks like in my application:
![image](https://user-images.githubusercontent.com/60228260/74157216-e6344280-4be5-11ea-9813-c18156030010.png)

The image src never seems to get updated. Do I need to wire those events up myself?

**Comment by sconix** [comment]
Sorry, can't help you there. I have not used the lazy feature of Swiper so I have no idea how its supposed to work. Since you are using the directive it really should not be any different from what you would do with Swiper.
