### ISSUE TITLE
Should this be a dev dependency?

### ISSUE THREAD

**Issue by picosam** [zefoy/ngx-swiper-wrapper#25]
Hello, in the Installation section in your readme file, you state the following:
`npm install ngx-swiper-wrapper --save-dev`
What happens when we `ng build --prod` later, won't this package be missing?

**Comment by sconix** [comment]
No, the dev depencies in npm have nothing to do with the environment used in the angular-cli build. I.e. dev dependencies are usually installed if you plan to do any development i.e. building of the application (no matter if the building is done for dev or production environment).
