### ISSUE TITLE
Cannot use instance of Swiper when accessing element

### ISSUE THREAD

**Issue by Saerdn** [zefoy/ngx-swiper-wrapper#26]
Hello,

I try to access the Swiper instance by defining my property like you mentioned: `ViewChild(SwiperComponent) swiperView: SwiperComponent;`

I set my config when getting data via an API (images etc.):
` this.apiService.contentTransmitter.subscribe(data => {
            this.sliderOptions = {
                pagination: '.swiper-pagination',
                nextButton: '.swiper-button-next',
                prevButton: '.swiper-button-prev',
                keyboardControl: true,
            };
        });`

Template:
`<div #swiperView [swiper]="sliderOptions" class="stage-carousel"> <div class="swiper-wrapper"> ...</div> </div>`

However, when doing console.log(this.swiperView) the console says this.swiperView is undefined.
When directly accessing the element (instead of writing "SwiperComponent") this.swiper is defined, but I can't use the methods like update() or "slideNext()"

Thank you in advanced,
Säerin

**Comment by sconix** [comment]
You need to study Angular bit more. You are using directive not component so thats why you wont get anything with defining SwiperComponent since there simply isn't such component. Anyway ViewChild usage is more of an Angular question than related to this library.
