### ISSUE TITLE
Error: Failed to find 'swiper/dist/css/swiper.min.css'

### ISSUE THREAD

**Issue by muk-ai** [zefoy/ngx-swiper-wrapper#262]
```
ERROR in ./src/app/path/to.scss
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find 'swiper/dist/css/swiper.min.css'
```
I faced the error but,
```
@import '~swiper/dist/css/swiper.min.css';
```
↓
```
@import '~swiper/css/swiper.min.css';
```
This changes fixed the error.

I'm using the version of the NPM package below.
`@angular/core`: `9.0.7`
`ngx-swiper-wrapper`: `9.0.1`
`swiper`: `5.3.6`

---
https://github.com/zefoy/ngx-swiper-wrapper/blob/master/README.md

```
> DIRECTIVE USAGE
> When using only the directive you need to provide your own theming or import the default theme:
> @import '~swiper/dist/css/swiper.min.css';
```

I guess this description is wrong, or output path of swiper's css is wrong.

**Comment by sconix** [comment]
Thanks, I have updated the readme.

**Comment by muk-ai** [comment]
Thank you for improving.
