### ISSUE TITLE
Access params.control in the component

### ISSUE THREAD

**Issue by mmirzaee** [zefoy/ngx-swiper-wrapper#27]
Hi, 
Is it possible to change swipers config in the component by ChildView for setting the "control" parameter.
I want to make a slider with thumbs. see [this example](https://github.com/nolimits4web/Swiper/blob/master/demos/23-thumbs-gallery.html).

Thank you.

**Comment by sconix** [comment]
Not sure what do you mean exactly.  I don't see any problems making that, the component will notice any changes to the Swiper configuration.

**Comment by BearandYoon** [comment]
@mmirzaee , did you succeed to building thumbs slider?
