### ISSUE TITLE
Can't manipulate pagination's css class.

### ISSUE THREAD

**Issue by lautarojgarcia177** [zefoy/ngx-swiper-wrapper#273]
bulletClass and bulletActiveClass properties don't work in configuration object.

Here's the API of those properties, they change the pagination css class.
https://swiperjs.com/api/#pagination

**Comment by sconix** [comment]
You can use the directive, the component has its own bullets implementation. I will add a fix for later versions so that component also uses those configurations.

**Comment by lautarojgarcia177** [comment]
Thanks for the replay, i can't use it with the directive neither. The only workarounds i found were to add the classes: "swiper-pagination-white" or "swiper-pagination-white".

**Comment by sconix** [comment]
I can not replicate this, the bulletClass and bulletActiveClass works as they should.

**Comment by lautarojgarcia177** [comment]
Already fixed it, i think it was because of angular, what i did was to set the class in the styles.css file
