### ISSUE TITLE
github and npm README mismatch

### ISSUE THREAD

**Issue by omrirz** [zefoy/ngx-swiper-wrapper#274]
Just wanted to let you know.

![npm](https://user-images.githubusercontent.com/13974474/86398094-be856a00-bcad-11ea-8bd2-ec9ada8ecab6.png)
![github](https://user-images.githubusercontent.com/13974474/86398101-c0e7c400-bcad-11ea-9e18-84e9f5c1b43d.png)

**Comment by sconix** [comment]
Npm only updates the readme on new releases so will get "fixed" when there is a next release.
