### ISSUE TITLE
angular-cli throws error on (breakpoints parameter)

### ISSUE THREAD

**Issue by kweheliye** [zefoy/ngx-swiper-wrapper#29]
Hi,

angular-cli throws error  when (breakpoints parameter) used in SWIPER_CONFIG.

> ERROR in Error encountered resolving symbol values statically. Name expected (po
sition 43:9 in the original .ts file), resolving symbol SWIPER_CONFIG

Please see attached image for my Swiper configuration

![swiper-config](https://user-images.githubusercontent.com/8476360/27260030-0badc150-542a-11e7-8f79-826714603beb.PNG)

**Comment by sconix** [comment]
I added similar breakpoints configuration to my angular-cli project and there are no errors. So with this information I can not replicate this and I have no idea what could cause error in that config.

**Comment by kweheliye** [comment]
Please can you share your swiper configuration ? Thanks

**Comment by sconix** [comment]
Sorry what I meant to say was that I used the exactly the same configuration not similar.

**Comment by eliasws** [comment]
In case anyone else gets this problem: 
I resovled it by replacing the 'numbers' (eg. 380, 640, 1000) with 'strings' ('380', '640', '1000').
