### ISSUE TITLE
Images do not lazy load:

### ISSUE THREAD

**Issue by calbear47** [zefoy/ngx-swiper-wrapper#30]
Love this nice wrapper for swiper. 

Everything works as expected, except lazy loading. Here is my config: 

```
  slider_config = {
    direction: 'horizontal',
    slidesPerView: 'auto',
    spaceBetween: 15,
    keyboardControl: true,
    preloadImages: false,
    lazyLoading: true,
    lazyLoadingInPrevNext: true,
  };

```

And here is my template, can you see anything that stands out, or notice what I'm doing wrong? 

```
    <swiper [config]="slider_config">
      <div *ngFor="let slide of (facility | async)?.facility.images">
        <img class="full-image swiper-lazy" [src]="'https://facilityzimmer.imgix.net/'+slide+'?auto=format&w=800&h=auto&q=70'" [alt]="(facility | async)?.facility.name">
      </div>
    </swiper>
```

I tried to keep it super basic, but even still, it loads all the images right up front on page load. This is very evident when I throttle the network for 3G speed...page takes a bit to load...hence the purpose of lazy loading. 

Any ideas would be super fantastic. Thanks!

UPDATE

I realized I was binding to the wrong properties on the img tag. I believe this is right:

```
    <swiper [config]="slider_config">
      <div *ngFor="let slide of (facility | async)?.facility.images">
        <img class="full-image swiper-lazy" [data-src]="'https://facilityzimmer.imgix.net/'+slide+'?auto=format&w=800&h=auto&q=10&blur=50'" [data-srcset]="'https://facilityzimmer.imgix.net/'+slide+'?auto=format&w=800&h=auto&q=70'" [alt]="(facility | async)?.facility.name">
      </div>
    </swiper>
```
But now I get a error that `data-src` isn't a known property of img, so angular can't bind to it. Any idea? Thanks

**Comment by sconix** [comment]
Use it as normal attribute like data-src="<url>".

**Comment by calbear47** [comment]
Thanks for your response! Yea that works fine with a static img src string, but I have dynamic variables that I would like to pass to the img src. How can I accomplish that?

**Comment by calbear47** [comment]
I ended up binding to them like so:

`[attr.data-src]`

Thanks for your help!
