### ISSUE TITLE
Support for Angular 4 

### ISSUE THREAD

**Issue by Faris-AH** [zefoy/ngx-swiper-wrapper#31]
Facing Issue:
Error in building with ng build --prod (using angular cli)
Description:
The Angular team will move to full AoT eventually and considers templates as separate entities from the component which means no private variables can be accessed from them. 
Reference :
https://github.com/angular/angular-cli/issues/5621

**Comment by sconix** [comment]
This library is fully compatible with AOT. The example app has an AOT example and we use this library in angular-cli project and there are no problems with AOT nor production build.

**Comment by Faris-AH** [comment]
Yep .My mistake.Sorry for that 
Thanks man
