### ISSUE TITLE
Compatibility with extract-text-webpack-plugin

### ISSUE THREAD

**Issue by SathishMattaparti** [zefoy/ngx-swiper-wrapper#32]
Hi,

When I try to use this ngx-swiper-wrapper module in my current project where  extract-text-webpack-plugin is currently configured to extract CSS , I am getting the below error.

Error: Child compilation failed:
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer
to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (C:\Angular2Apps\SPC\node_modules\extract-text-webpack-plugin\loader.js:27:9):

The error comes up the moment I import the ngx-swiper-wrapper into the module file.

If I remove the import statement for ngx-swiper-wrapper, my current code compiles properly without any errors. 

Any idea what I should do to get this error resolved?

**Comment by sconix** [comment]
There should not be anything that libraries need to do to be compatible with extract text plugin. The CSS file provided by this library is pure CSS and has no errors. So really hard to say what could be the problem specially since the error message does not say anything about the actual error.
