### ISSUE TITLE
Error when using swiper in ionic

### ISSUE THREAD

**Issue by mbakker96** [zefoy/ngx-swiper-wrapper#35]
Hi,

I use ionic 3 (angular 4) but there is a bug importing it into the app. When I import it (Ngmodule) and added into my HTML then my app crasht and shows the following angular error.
```
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'swiper'. ("ekNumbers, 'week-view': user?.weekView, 'month-view': !user?.weekView}">
    <swiper #swiperWrapper [ERROR ->][config]="swiperConfig">
        <div *ngFor="let month of months">
            <div class="header">
"): ng:///ComponentsModule/FlexCalendar.html@1:27
'swiper' is not a known element:
1. If 'swiper' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("week-numbers': user?.weekNumbers, 'week-view': user?.weekView, 'month-view': !user?.weekView}">
    [ERROR ->]<swiper #swiperWrapper [config]="swiperConfig">
        <div *ngFor="let month of months">
          "): ng:///ComponentsModule/FlexCalendar.html@1:4
syntaxError@http://localhost:8100/build/main.js:130834:39
parse@http://localhost:8100/build/main.js:141325:30
_compileTemplate@http://localhost:8100/build/main.js:155076:44
forEach@[native code]
_compileComponents@http://localhost:8100/build/main.js:155000:26
createResult@http://localhost:8100/build/main.js:154885:37
run@http://localhost:8100/build/polyfills.js:3:4458
http://localhost:8100/build/polyfills.js:3:14079
runTask@http://localhost:8100/build/polyfills.js:3:5153
o@http://localhost:8100/build/polyfills.js:3:2210
promiseReactionJob@[native code] — 
```
Calendar.html
```
 <swiper #swiperWrapper [config]="swiperConfig">

</swiper>
```

**Comment by sconix** [comment]
Thats not specific to this library, it sound like a normal module import / export miss configuration. Are you exporting the module so that its available for that piece of code?

**Comment by mbakker96** [comment]
I have it in the same module as were I 'import' the page. I added the `Swipermodule` into the module like it was set in the documentation. But I think it is not a bug of this library

**Comment by muralidharan9** [comment]
@mbakker96 Did you get any solution for this. Even I am struck with same error in Ionic2. Any help would be appreciated.

**Comment by mbakker96** [comment]
@muralidharan9 nope, I switched back to the ionic slides (what is still buggy)

**Comment by muralidharan9** [comment]
Ok, I was looking to implement coverflow effect which is not possible with ionic-slides. So I thought to implement the customized Swiper. 
Let me know if you have come across anything which implements Coveflow effect in ionic2.

**Comment by mharrisn** [comment]
@mbakker96 @muralidharan9 I also use Ionic and was able to get this going. If the IonicPage you're using is being lazy loaded (It probably is if you also have a .module.ts file in your page's folder?) You need to add the SwiperModule to that page's .module.ts for it to be available in that page

So if your Ionic page is  MyPage, then in the my-page.module.ts file, you would add `SwiperModule ` to the imports section of that module. Note that it should NOT be `SwiperModule .forRoot()`

**Comment by medbz** [comment]
You have just to add KSSwiperModule to @NgModule imports at the .module.ts :D dont forget to import it

**Comment by pandabamboo90** [comment]
@mharrisn Thank you, your suggestion worked, I'm using Ionic 3. 🍰

**Comment by vanschroeder** [comment]
Tried using this lib with Ionic4 and Angular 8 and no luck. While including in the chid module did resolve the directive scope issue, I am getting a Null Injector error, which is a whole other can of worms

```
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[SwiperDirective -> InjectionToken Platform ID]: 
```

Sadly, I don't have time for sorting this out, and now looking for other solution for this project. Which sucks, this lib looked nice, but seems to have incompatibilities with ionic. Hopefully in the future this lib will work with ionic
