### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by daxiazilong** [zefoy/ngx-swiper-wrapper#36]
If i use Swiper in sub-module with 'forRoot(config)' , when my route change and back to this Module again,console show me 
   " Application called SwiperModule.forRoot() twice.
      For submodules use SwiperModule.forChild() instead."
but when i change my code  according to the tip ,then console  show me this:
  "Supplied parameters do not match any signature of call target"
give me a solution, please!!!

**Comment by sconix** [comment]
The forChild function does not take any parameters. You can give the global configuration only once from the root module.

**Comment by daxiazilong** [comment]
thanks!!!
