### ISSUE TITLE
Can't use multiple swiper components on same page

### ISSUE THREAD

**Issue by uzumakinaruto123** [zefoy/ngx-swiper-wrapper#37]
**Platform**: Ionic 3
**Angular**: 4.1.3

**Relevant code**:

```
<div [swiper]="config" #featuredView [runInsideAngular]="true" class="swiper-container">
        <div class="swiper-wrapper">
          <div class="swiper-slide" *ngFor="let i of [0,1,2,3,4]" style="background-color: green">
            <h2>Featured {{i}}</h2>
          </div>
        </div>
      </div>
<div [swiper]="config" #allView [runInsideAngular]="true" class="swiper-container">
          <div class="swiper-wrapper">
            <div class="swiper-slide" *ngFor="let i of [0,1,2,3,4]" style="background-color: green">
              <h2>All {{i}}</h2>
            </div>
          </div>
        </div>
```

**Without [runInsideAngular]**
*ngFor loop does not loop slides 

**With [runInsideAngular]**
Can't swipe slides and touch events occurs on all swiper components

**Comment by sconix** [comment]
When not running inside angular zone the Swiper initialization does not cause any change detection to be run, so if your application is not doing anything that would cause change detection then you need to run it manually which in turn would check those ngFor:s. Normally there should be no need for that in any case, but I am not familiar with the Ionic platform so maybe that causes the need for manual running.

Swiper itself uses the classes to recognize the slides so have you tried using different slide/wrapper class for the other swiper component. The used class names can be provided in the config with slideClass / wrapperClass.

We use multiple swipers in our app without any problems, but never in the same container, so I suspect that when multiple swiper are inside same container the classes may need to be different for the Swiper to work properly.

Let me know if that does not help then I can try to replicate the problem.

**Comment by uzumakinaruto123** [comment]
I will try `slideClass / wrapperClass` and confirm. Currently, to make it work I am using angular2-useful-swiper, where it's working without any tweaks. But I want to give this one a try again.  Do I need to override any css with the classname I provide for `slideClass / wrapperClass`?

**Comment by sconix** [comment]
There should be no need. If you can make a small plunker example then I can look into this more easily. Like I said we are using multiple swiper components without the class config without any problems.

I am back from my holiday on monday, i can then look into fixing this if there is something to fix.

**Comment by BearandYoon** [comment]
@sconix 

First of all thanks for your amazing module.
I am using `ngx-swiper` for my project and I succeed placing two swiper on one page. I am trying to implement thumb slider `Thumbs Gallery With Two-way Control` this one from Swaper demo.

Problem is connect two swipers. Like this.

```
    galleryTop.params.control = galleryThumbs;
    galleryThumbs.params.control = galleryTop;
```

I tried to use `SwiperConfigInterface.control` but it does not works.
Is there any way to connect two swipers so I can implement Thumbs Gallery?

**Comment by webcat12345** [comment]
Here is solution.

You need to get handle of swiper using `ViewChild` or `ViewChildren`.
Consider you can not use `ViewChild` multiple times inside one component.

Follow this instruction.

* **Get handles of Swipers using `ViewChildren`**
```  @ViewChild(SwiperComponent) swiperView: QueryList<SwiperComponent>;```

* **Set index of swiper using `setIndex` Method**
```
onIndexTopChange(index: number) {
    this.swiperView['_results'][1].setIndex(index);
  }

onIndexThumbsChange(index: number) {
    this.swiperView['_results'][0].setIndex(index);
  }
```

There is no document about available methods. I will make pull request when I have time.

**Comment by BearandYoon** [comment]
Amazing! It works! Thanks @webcat12345

**Comment by sconix** [comment]
I am going to update the documentation to be more precise on next update.

**Comment by BearandYoon** [comment]
I am trying to set initial image index on `Thumbs Gallery With Two-way Control`
For ex, my gallery has 20 photos and I am going to set focus on 10th image.
So I used `this.swiperView['_results'][0].setIndex(10);` but it doesn't work for me.

**Comment by sconix** [comment]
Are you calling it before the Swiper has initialized, i.e. before afterViewInit? Swiper has a configuration option called initialSlide which you can also set for setting the initialSlide index.

**Comment by BearandYoon** [comment]
Hi @sconix 
Thanks for your help.
InitSlide is working now but swiper shows firstImage(index = 0) at first then it slide to selected image(index: 10).
It takes about 0.3s.

**Comment by sconix** [comment]
Not sure what your exact setup is, but you will always see the first slide briefly since all slides needs to be rendered first before Swiper can move to wanted slide. Although the 0.3s sounds a bit long for that, but I am not sure if Swiper offers any means to go to the initial slide without showing the first. You of course can always set visibility to hidden while things are "initializing".

**Comment by webcat12345** [comment]
I recommend @sconix suggestion : set visibility to hidden while things are "initializing" or Just display spinner/loader while loading.

**Comment by nchetankumar** [comment]
Is there any way to handle nested swipers?
<swiper>
<div class="parent">
    <swiper>
        <div class="child"></div>
    </swiper>
</div>
</swiper>

In this case, I want to swipe the parent container using pagination and child container using the navigation arrows if there is an example it will be helpfull?

**Comment by ahmedkhairydev** [comment]
add it in your config

```
nextButton: `.button-next-s1`, // s2, s3, etc
prevButton: `.button-prev-s1`, // s2, s3, etc
```
