### ISSUE TITLE
Swiper doesn't resize properly

### ISSUE THREAD

**Issue by calbear47** [zefoy/ngx-swiper-wrapper#38]
I am having issues on  multiple different versions of safari and chrome on iOS.  Everything works fine on Android. My issue is that when the user changes orientation from portrait to landscape, swiper doesn't resize the width of each slide...so multiple slides show on the screen like so:

![realios_iphone_6s](https://user-images.githubusercontent.com/16049160/28333761-dad92330-6bad-11e7-9d1e-67f93dffb127.jpg)

I saw [this answer on stackoverflow](https://stackoverflow.com/questions/37847974/swiper-slider-gallery-and-changing-orientation-on-iphones), but I don't have access to onResize method, but I used update instead like this:

```
    this.window.nativeWindow.addEventListener('orientationchange', ()=>{
      console.log("orientation fired");
      setTimeout(()=>{this.swiper.update()}, 50);
    })
```

This unfortunately didn't solve the issue. 

I'm trying to achieve this: 

![realios_iphone_6s 2](https://user-images.githubusercontent.com/16049160/28333895-427a6026-6bae-11e7-9df0-29063fd81279.jpg)

Which works just fine on Android. Do you have any suggestions? Thanks in advance

**Comment by calbear47** [comment]
I will try that. However, I wasn't having a problem getting the orientation event firing. The orientation event was firing property, but `setTimeout(()=>{this.swiper.update()}, 50);` didn't resize the swiper instance. 

Let me get back to you on this later today. Thanks for your reply.

**Comment by calbear47** [comment]
So, I followed your suggestion. But this did solve the problem. This definitely seems to be a change detection issue though because if I touch the screen the right way to scroll, swiper resizes. This is my code....

```
@ViewChild('gallery') swiper:SwiperComponent;

  @HostListener('window:resize')
  onWindowResize() {

    console.log("Swiper Updated");// Logs out as expected on orientation change
    setTimeout(()=>{this.swiper.update(true);},0);
  }
```

**Comment by sconix** [comment]
Yes that sound like a change detection issue. Have you tried adding markForCheck call after that update? If you are using onPush then that call is usually needed after things in timeout has been executed.
