### ISSUE TITLE
Getting warning when Compile the project

### ISSUE THREAD

**Issue by satyathefighter** [zefoy/ngx-swiper-wrapper#39]
WARNING in ..swiper/dist/js/swiper.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'maps/swiper.js.map': Error: Can't resolve './maps/swiper.js.map' in 'node_modules\swiper\dist\js'
 @../ ngx-swiper-wrapper/dist/lib/swiper.component.js 2:13-30
 @ ../ngx-swiper-wrapper/dist/lib/index.js
 @ ../~/ngx-swiper-wrapper/dist/index.js
 @ ../build/vdp.module.js
 @ ./src/main/angular/$$_gendir/app/test/test.module.ngfactory.ts
 @ ./src/main/angular/$$_gendir async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main/angular/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main/angular/main.ts

The above error i am getting and below my config details
node: 6.10.2
os: win32 x64
 angular/cli: 1.1.2
 angular/common: 4.2.3
 angular/compiler: 4.2.3
 angular/compiler-cli: 4.2.3
 angular/core: 4.2.3
 angular/forms: 4.2.3
angular/http: 4.2.3
 angular/platform-browser: 4.2.3
 angular/platform-browser-dynamic: 4.2.3
 angular/router: 4.2.3

**Comment by sconix** [comment]
Something wrong with your build setup, the error comes from the swiper itself and not from this library. So that lets me believe that the fault is in your build configuration.

**Comment by sconix** [comment]
I noticed that I got this error when using npm linked version of the package. Not sure why, but there is no error when I am using normally installed package.
