### ISSUE TITLE
Installing using npm

### ISSUE THREAD

**Issue by hassanasad** [zefoy/ngx-swiper-wrapper#40]
Hi - Seems like a good and actively maintained wrapper for Swiper!

Keep up the good work guys!

Just wanted to point out (or know), In README.md it says:
`npm install ngx-swiper-wrapper --save-dev`

Shouldn't it be:
`npm install ngx-swiper-wrapper --save`

(instead of --save-dev > --save) ?

**Comment by sconix** [comment]
Normally no, you only need the library when developing. Usually you compile your app into one or multiple js files. Of course there can be situation when its needed as normal dependency, but when it comes to Angular apps I think the normal case is that this is only needed as dev dependency.

Thanks for the comment, I plan to maintain this actively at least as long as I either make a pure Angular version of the Swiper or something better than Swiper comes along. I will release soon 4.5.0 which brings small breaking changes, just as a heads up. The component has been re-written to use the directive and some events have been renamed to avoid problems with native DOM events.

**Comment by hassanasad** [comment]
Thanks @sconix - I learned something new :)

I will see if other packages i am using can be moved to devDependencies - looking forward to 4.5.0!
Appreciate your hardwork :)
