### ISSUE TITLE
some of configuration is not working nextButton, prevButton, paginationBulletRender 

### ISSUE THREAD

**Issue by almothafar** [zefoy/ngx-swiper-wrapper#44]
I got the following configuration is working with version 4, but completely broken in version 4.5.x, with the following config, I was getting correct buttons and was working and clickable, with new version only icon shown and above the new blue icons, my custom buttons, and nothing is working at all, pagination is now shown or working, everything in mess about those actions.

Also, styling is not working anyway.

Autoplay and speed, also swiping with touch are still working.

```
public swiperConfig: SwiperConfigInterface = {
    autoplay: 10000,
    autoplayDisableOnInteraction: false,
    speed: 1000,
    direction: 'horizontal',
    slidesPerView: 1,
    keyboardControl: true,
    nextButton: '.slider-next-button',
    prevButton: '.slider-prev-button',
    pagination: '.slider-pagination',
    paginationBulletRender: (swiper, index, className) => {
      return `<li style="z-index: 10" class="slick-active ${className}"><button ></button></li>`;
    },
    paginationClickable: true,
    loop: true,
    zoomToggle: false,
    setWrapperSize: true
  };
```
HTML:
```
<div class="banner-slider" style="position: relative;overflow-x: hidden">
  <div class="slick-list draggable">
    <swiper [config]="swiperConfig">
      <div class="banner swiper-element-override">
        <div class="container">
          <div class="row">
            <div class="seven">
              <div class="banner-content">
                <h1>Slide 1</h1>
              </div> <!-- /banner-content -->
            </div> <!-- /seven -->
          </div> <!-- /row -->
        </div> <!-- /container -->
      </div> <!-- /banner -->

      <div class="banner swiper-element-override">
        <div class="container">
          <div class="row">
            <div class="eight">
              <div class="banner-content">
                <h1>Slide 2</h1>
              </div> <!-- /banner-content -->
            </div> <!-- /seven -->
          </div> <!-- /row -->
        </div> <!-- /container -->
      </div> <!-- /banner -->

      <div class="banner swiper-element-override">
        <div class="container">
          <div class="row">
            <div class="seven">
              <div class="banner-content">
                <h1>Slide 3</h1>
              </div> <!-- /banner-content -->
            </div> <!-- /seven -->
          </div> <!-- /row -->
        </div> <!-- /container -->
      </div> <!-- /banner -->
    </swiper>
  </div>
  <button class="slick-prev slick-arrow slider-prev-button"></button>
  <button class="slick-next slick-arrow slider-next-button"></button>
  <ul class="slick-dots slider-pagination"></ul>
</div>
```

Some custom styling:
```
.swiper {
  .swiper-container {
    .swiper-wrapper {
      .swiper-slide.swiper-element-override {
        background-size: cover;
        min-height: 1px;
        height: 90vh !important;
        max-height: 800px !important;
        width: 100%;

        @media (#{$larger-than-phablet}) {
          background-position: top center;
          height: 100vh !important;
        }
      }
    }
  }
}
```

**Comment by sconix** [comment]
The 4.5.x release should have only cause breaking changes for styles as said in the other issue. Of course its possible that there is some bug that its triggering since the 4.5 update was pretty much complete re-write due to combining the component/directive code.

But looking at your setup I think the problem is that you are trying to provide your own component by using the component, so that is the most likely reason why you have troubles. I am surprised that it worked with older component, but with this latest version if you want to use custom buttons / paginations etc. then you either need to use none standard class names or use the directive.

Since the component provides its own elements which it uses if nextButton/etc. is set to true / standard class name (slider-next-button). So to use custom components you need to use custom class names or the directive and it should have been like this with the older versions as well, but maybe they had a bug.

So try to switch to directive and see if it helps. I think I should add a note about this into the README.

**Comment by wangwanzhong** [comment]
Hi, seems like the configuration of autoplay dosen't work in directive or component, is there any example for autoplay. thank u.

`

<swiper [config]="config" [(index)]="index">
  <div *ngFor="let slideImage of slideImages">
    <img src="{{ slideImage }}">
  </div>
</swiper>

# banner.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

import { SwiperConfigInterface } from 'ngx-swiper-wrapper';


@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.scss']
})
export class BannerComponent implements OnInit, OnDestroy {

  index: number = 1;
  intervalEvent: any;

  config: SwiperConfigInterface = {
    direction: 'horizontal',
    initialSlide: 0,
    // autoplay: 1000, 发现不生效
    speed: 500,
    effect: "fade",
    loop: true,
    centeredSlides: true,
    pagination: '.swiper-pagination',
    paginationClickable: true
  };

  slideImages: string[] = [
    '../assets/imgs/ban0.jpg',
    '../assets/imgs/ban1.jpg',
    '../assets/imgs/ban2.jpg'
  ];

  constructor() { }

  ngOnInit() {
    this.intervalEvent = setInterval(() => {
      if (this.index >= this.slideImages.length - 1) {
        this.index = 0;
      } else {
        this.index = this.index + 1;
      }
    }, 2000);
  }

  ngOnDestroy() {
    clearInterval(this.intervalEvent);
  }

}
`

**Comment by sconix** [comment]
The configuration is passed as it is to the Swiper so you need to refer to Swiper documentation. I guess autoplay just sets the delay and you still need to call startAutoplay to start it.

**Comment by almothafar** [comment]
Just for your information, I make it run correctly with the latest version, have to do some "restructure" for HTML and CSS.

**Comment by dbarochia** [comment]
I also was facing the same issue. Custom pagination button was showing but event were not get binded. After spending 5 to 6 hour when I analyze swiper component I found they have additional added condition which required your configuration must have navigation:true in SwiperConfigInterface

Try to add like below
public swiperConfig: SwiperConfigInterface = {
     navigation:true,
};
