### ISSUE TITLE
[question] how to use events like onTouchEnd by binding?

### ISSUE THREAD

**Issue by wyshmily** [zefoy/ngx-swiper-wrapper#47]
thank you !

**Comment by sconix** [comment]
Just add (swiperTouchEnd)="functionToRun($event)". All the Swiper callbacks are available as events without the 'on' prefix  just like with Swiper documentation says. For events that conflict with dom events such as touchEnd I have added swiper prefix, hence they are swiperTouchEnd etc.

**Comment by wyshmily** [comment]
I tried this, but the event does not fire. 
Is there anything need to care?

**Comment by sconix** [comment]
If I add that event listening to the example app it does fire always on mouseup/touchend (tried both directive and component). So the event is send by this library if event is received from the Swiper. Regarding this library there is nothing special to take into account, but from the Swiper side I am not sure if some configuration effects the sending of that event. At least it works with the example app.

**Comment by wyshmily** [comment]
I updated all my npm packages, and it worked, thanks!
