### ISSUE TITLE
Bootstrap viewport size M causes slide calculate to enormous width

### ISSUE THREAD

**Issue by shooby83** [zefoy/ngx-swiper-wrapper#49]
As soon, as I change to medium viewport size the swiper basically explodes to eternity. In size small it comes back to normal.

Any suggestions, what could cause this effect and how to fix it?

Thanks for the support

**Comment by sconix** [comment]
Do you mean that you are changing the size dynamically, if yes then you need to call the update function for Swiper to resize itself.

**Comment by shooby83** [comment]
No, even if I reload the page in this viewport size this behaviour is happening.

**Comment by sconix** [comment]
Without Plunker example really hard to say if its a Swiper issue or issue with this library or something else.
