### ISSUE TITLE
[Feature] Universal Support 

### ISSUE THREAD

**Issue by MarkPieszak** [zefoy/ngx-swiper-wrapper#50]
We need to get some Dependency Injection in here to use a `window` service, instead of using the `window` / `document` or anything of that nature, as it breaks on the server (since they don't exist there). Any level of abstraction to simply check for it's existence and then `return` if it's not there would make it work well with Universal.

**Comment by MarkPieszak** [comment]
Nevermind if this is a wrapper for swiper, it won't work in general. Scratch that!

**Comment by sconix** [comment]
There is a PR for Swiper that would make it work nicely with server side rendering. So hopefully it gets merged at some point. Although I am most likely going to write pure angular Swiper type of library soon if such thing does not already exist since this wrapper wont serve our needs much longer.

**Comment by picosam** [comment]
That would be the greatest thing since ice cream! 👍

**Comment by MarkPieszak** [comment]
Yeah the problem seems to be that swiper-JS is the culprit, it of course goes crazy over document/window/everything else under the sun 🙈
