### ISSUE TITLE
SwiperDirective.ngOnCheck Exception

### ISSUE THREAD

**Issue by jkbreunig** [zefoy/ngx-swiper-wrapper#51]
v4.6.1
Error:
vendor.bundle.js:75878 ERROR TypeError: Cannot read property 'diff' of undefined
    at SwiperDirective.webpackJsonp.../../../../ngx-swiper-wrapper/dist/lib/swiper.directive.js.SwiperDirective.ngDoCheck 

SwiperDirective.prototype.ngDoCheck = function () {
        var _this = this;
        **var changes = this.configDiff.diff(this.config || {});**
        if (changes) {
            this.initialIndex = this.getIndex();
            changes.forEachAddedItem(function (changed) {
                if (changed.key === 'initialSlide') {
                    _this.initialIndex = _this.config.initialSlide;
                }
            });
            this.ngOnDestroy();
            // Timeout is needed for the styles to update properly
            setTimeout(function () {
                _this.ngOnInit();
            }, 0);
        }
    };

**Comment by sconix** [comment]
That can only happen if ngDoCheck is called before ngOnInit. Afaik it should not happen normally and usually the fault is somewhere else, but I will add checks for next release that at least this library wont give an error.
