### ISSUE TITLE
Swiper panning not working when zoomed in on a slide

### ISSUE THREAD

**Issue by elgervb** [zefoy/ngx-swiper-wrapper#52]
When I set `Swiper` config option `zoom` to `true`, zooming is possible, but there is no padding support.
In the Swiper [demo](http://idangero.us/swiper/demos/39-zoom.html) you can zoom in on an image and pan to move the image's focus. 

This is not woking in the `ngx-swiper-swapper`.

**Template:**
```
<swiper [config]="config" *ngIf="images.length > 0">
<div style="height:100%;" *ngFor="let image of images">
  <div class="swiper-zoom-container" >
      <img [src]="imageDataUri(image)" class="image-panel__image" />
  </div>
</div>
</swiper>
```

I figured out that I manually need to add `<div class="swiper-zoom-container" >` to make zooming work. It would be nice that this library would add this automatically when setting the `config.zoom` option to `true`.

**Config in component.ts:**
```
config: SwiperConfigInterface = {
    direction: 'horizontal',
    slidesPerView: 2,
    zoom: true,
    zoomMax: 2
  };
```

Swiper API: http://idangero.us/swiper/api (search for zoom)
Swiper Demo: http://idangero.us/swiper/demos/39-zoom.html
Swiper Source Code: https://github.com/nolimits4web/Swiper/blob/master/demos/39-zoom.html

**Comment by sconix** [comment]
Swiper api / docs are rather clear that you need to wrap it in container with that class. So if Swiper is not adding the class automatically I am thinking that this library shouldn't neither. Since I guess there is a reason for it, maybe that you might want it in different element depending on the use case. So then I would need extra config option to tell weather to add the class or not.

**Comment by elgervb** [comment]
OK, tnx for your reply. The `swiper-zoom-container` class is not really the issue here, I can solve it myself ;-)

To demonstrate the issue, I've created an example on my fork https://github.com/elgervb/ngx-swiper-wrapper. 
I've added some amazing cat pictures to visualize zooming ;-)

Zooming is possible by double clicking on a slide, but then you cannot pan. Please not that this is possible in the [swiper demo](http://idangero.us/swiper/demos/39-zoom.html).

Commit: https://github.com/elgervb/ngx-swiper-wrapper/commit/b258c33d8ceae5721eac2ce3ae9805192f325fa7

**Comment by sconix** [comment]
I did test the zoom in the example app and it did work properly, but I can have a look at your test code tomorrow.

**Comment by elgervb** [comment]
@sconix like zooming is indeed possible. Seems to be working like a charm. But you cannot pan when zoomed in in a slide.

For clarity, I've changed the issue title to: _Swiper panning not working when zoomed in on a slide_

**Comment by sconix** [comment]
Panning also worked with correct styling. Have you made sure that the swiper-zoom-container is correctly placed / sized?

**Comment by elgervb** [comment]
it is now.. but still to no avail

**Comment by sconix** [comment]
Ok, I will check your code tomorrow to see if there is a problem with this library or not. If you figure it out before that please post here.

**Comment by sconix** [comment]
Checked your code and you have the template wrong. If you look at the Swiper documentation the img needs to be the only element inside the swiper-zoom-container. Now you have a div with swiper-slide-content within the zoom container so just remove that div and panning works.

**Comment by elgervb** [comment]
@sconix Tnx for the update. I've made some adjustments to my template and zooming in and panning is possible now. So, tnx for the update.

The only problem I'm facing now, is that (once zoomed in) I cannot zoom out. Both in component as in directive. In the Swiper demo, you can zoom out by double clicking once again on an image.

Can you take a look at this? Tnx

Btw. I've updated my fork with this example

**Comment by sconix** [comment]
For me it works in you example, double tap zooms in and another double tap zooms out.

**Comment by AmirMehr** [comment]
In my case was:
   I didn't add <div class="swiper-zoom-container"> after <div class="swiper-slide">
