### ISSUE TITLE
Swiper Directive index not updating after swiping to last slide

### ISSUE THREAD

**Issue by jkbreunig** [zefoy/ngx-swiper-wrapper#53]
v4.6.1

Swiper Directive index doesn't always update after swiping to last slide. After swiping to the last slide and then swiping again in direction of last slide then the index property sometimes updates. swiper.isEnd also returns false after swiping to the last slide.

**Comment by sconix** [comment]
If you are checking the isEnd and index from the Swiper instance then the problem should be in the Swiper and not in this library. I haven't seen such behavior though so have you tried with default configuration etc. to see if its some configuration option that is causing it. Also on which event are you checking the Swiper index / isEnd?

**Comment by jkbreunig** [comment]
I'm checking the Swiper index on the indexChange event.

**Comment by sconix** [comment]
Ok can you get that problem happen on the example app? It logs the index in console. Also are you using any special configuration?

**Comment by jkbreunig** [comment]
I fixed this issue by removing slidesPerView: 'auto' on Swiper config. Thanks

**Comment by sconix** [comment]
Ok so its Swiper bug then with that option.
