### ISSUE TITLE
Uncaught TypeError: Cannot read property 'zoom' of null

### ISSUE THREAD

**Issue by p-nagendra** [zefoy/ngx-swiper-wrapper#54]
First of all Thanks for the wrapper, 

However  when  I try implementing the component  I am getting  the following Runtime errors  on  GestureStart to End  

Here is my Code : 

**Config :** 
`
public config: SwiperConfigInterface = {
    scrollbar: null,
    direction: 'horizontal',
    slidesPerView: 1,
    scrollbarHide: false,
    keyboardControl: true,
    mousewheelControl: true,
    scrollbarDraggable: true,
    scrollbarSnapOnRelease: true,
    pagination: '.swiper-pagination',
    paginationClickable: true,
    noSwiping: false,
    zoom: true,
    loop: true,
  }
`
**HTML Code :**
` <swiper [config]="config">
      <div class="swiper-slide" *ngFor="let image of images; let i = index">
        <div class="swiper-zoom-container">
          <img [src]="image" class="product-image">
        </div>
      </div>
    </swiper>
`

**Errors I am seeing :**

`Uncaught TypeError: Cannot read property 'zoom' of null
    at HTMLDivElement.onGestureStart (swiper.js:3850)
    `

`Uncaught TypeError: Cannot read property 'params' of null
    at HTMLDivElement.Swiper.s.onTouchStart (swiper.js:1549)
    `
These  Errors  are panning all  events i.e,  Start -> Change->End

**Comment by sconix** [comment]
That sounds like a problem in Swiper, but I have seen this error with older zone.js which had a bug. So are you using latest version of zone.js?

**Comment by sconix** [comment]
At least I am unable to reproduce this with the example app, perhaps you can make a Plunker demonstrating the problem.

**Comment by p-nagendra** [comment]
This  continues  with latest Zone.js as well ...  I am using  the plugin  with  Angular2

**Comment by sconix** [comment]
Ok since you are using that old version of Angular it could be that.
