### ISSUE TITLE
Updating to recent version(4.6.2) breaks existing code 

### ISSUE THREAD

**Issue by anil100nair** [zefoy/ngx-swiper-wrapper#56]
I did npm install in my project that uses ngx-swiper-wrapper. npm installed the latest version which is breaking the build and not compiling. Below are the error logs.

```ERROR in /home/Projects/node_modules/ngx-swiper-wrapper/dist/lib/swiper.module.d.ts (1,31): Module '"/home/Projects/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
ERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol SWIPER_GUARD in /home/Projects/node_modules/ngx-swiper-wrapper/dist/lib/swiper.module.d.ts, resolving symbol SwiperModule.forRoot in /home/Projects/node_modules/ngx-swiper-wrapper/dist/lib/swiper.module.d.ts, resolving symbol AppModule in /home/Projects/src/app/app.module.ts, resolving symbol AppModule in /home/Projects/src/app/app.module.ts
```

What am I missing here?

**Comment by sconix** [comment]
What angular version are you using?

**Comment by anil100nair** [comment]
I am using angular 4.

**Comment by sconix** [comment]
Then I have no idea what the problem could be, it works with the example app and also in our project with angular-cli. The InjectionToken has been there from the beginning of Angular 4 afaik.

**Comment by sconix** [comment]
The only change with the latest release is that OpaqueToken was changed to InjectionToken which was introduced with Angular 4 and is required with Angular 5.

**Comment by anil100nair** [comment]
It is working fine when I switch back to 4.6.1. How do you think I should go about it then?

**Comment by sconix** [comment]
My guess is that there is something wrong with your packages / versions. The error would only make sense if you would be on Angular 2. I guess you have tried re-installing your node_modules folder.
