### ISSUE TITLE
Thumbs Gallery With Two-way Control

### ISSUE THREAD

**Issue by irvjc82** [zefoy/ngx-swiper-wrapper#57]
Hello, i've been trying to create a Thumbs Gallery based on the one from the DEMO ( http://idangero.us/swiper/demos/23-thumbs-gallery.html ) but i'm not able to make it work. Don´t even know if this is possible. Any help would be appreciated.

**Comment by byounathan** [comment]
+1

**Comment by sconix** [comment]
You just use the correct config options. There is no special coding needed to achieve that.

**Comment by irvjc82** [comment]
i realize that for you this must be simple, but i've been trying different configuration options with no luck.

**Comment by sconix** [comment]
But to help I would need to know what your exact problem is. The example app pretty much has everything that you should need. The previous comment was more of an answer to the if its possible.

**Comment by irvjc82** [comment]
My problem is, the sliders work as two separated sliders. 
This is my TS code: 
`	public getConfigInicializado(): SwiperConfig {
		if ( this.config == null ) {
			this.config = new SwiperConfig();
			this.config.control = this.getConfigThumbsInicializado();
			this.config.nextButton = '.swiper-noticias-siguiente';
			this.config.prevButton = '.swiper-noticias-anterior';
			this.config.spaceBetween = 10;
		}
		return this.config;
	}

	public getConfigThumbsInicializado(): SwiperConfig {
		if ( this.configMiniaturas == null ) {
			this.configMiniaturas  = new SwiperConfig();
			this.configMiniaturas.control = this.getConfigInicializado();
			this.configMiniaturas.spaceBetween = 10;
			this.configMiniaturas.centeredSlides = true;
			this.configMiniaturas.slidesPerView = 6;
			this.configMiniaturas.touchRatio = 0.2;
			this.configMiniaturas.slideToClickedSlide = true;
		}
		return this.configMiniaturas;
	}`
This is mi HTML code:
`<div class="swiper-container slider-galeria" [swiper]="getConfigInicializado()">
	<div class="swiper-wrapper">
		<div class="swiper-slide" *ngFor="let imagen of getImagenesNG()">
			<article class="tarjeta-con-sombra">
				<div class="contenedor-de-imagen">
					<img class="img-responsive" src="{{ imagen | obtenerURLDeImagen }}">
				</div>
			</article>
		</div>
	</div>
</div>
<div class="swiper-noticias-siguiente" (click)="siguiente()">
	<i class="fa fa-angle-right" aria-hidden="true"></i>
</div>
<div class="swiper-noticias-anterior" (click)="anterior()">
	<i class="fa fa-angle-left" aria-hidden="true"></i>
</div>

<div class="swiper-container slider-thumbs" [swiper]="getConfigThumbsInicializado()">
	<div class="swiper-wrapper">
		<div class="swiper-slide" *ngFor="let imagen of getImagenesNG()">
			<img class="img-responsive" src="{{ imagen | obtenerURLDeImagen }}">
		</div>
	</div>
</div>`

**Comment by sconix** [comment]
You are passing a SwiperConfig as the control even though if you look at the demo source code you need to pass the Swiper instance. Swiper instance is created by this library and exposed as 'swiper' so you can access it via the directive reference which you can get using ViewChild.

**Comment by byounathan** [comment]
Thanks for the info!

The swiper reference in the directive is null.. am I missing something?

  ```
@ViewChild(SwiperDirective) swiperDirective: SwiperDirective;

  ngAfterViewInit() {
    this.thumbsConfig.control = this.swiperDirective.swiper; // <--- this.swiperDirective.swiper === null
```

Where this.thumsConfig is of the type SwiperConfigInterface.

Thanks!

**Comment by sconix** [comment]
Hard to say with that info. It looks ok to me, but are you sure that the swiperDirective is referencing the correct swiper? The swiper reference in the directive should not be null in that phase since it is intialized on ngOnInit. Since don't you have two swipers in your component so not sure if thats the correct way to get the reference. If you can make a Plunker example it would make it easier to see whats wrong. At least now you are on the correct track.

**Comment by AlicePrincess** [comment]
I would like to know finally how to solve

**Comment by AlicePrincess** [comment]
galleryTop.params.control = galleryThumbs;
galleryThumbs.params.control = galleryTop;  
how to write in ngx-swiper

**Comment by SaraVasseli** [comment]
I managed to control 2 ngx-swipers in this way:
@ViewChild('topSwiper')  topSwiper: SwiperComponent;
@ViewChild('bottomSwiper')  bottomSwiper: SwiperComponent;
then in 
ngAfterViewInit() {
        this.topSwiper.indexChange.subscribe(index => {
        this.bottomSwiper.directiveRef.setIndex(index, 10, true);
      });
  }

**Comment by ajaykrishna1123** [comment]
Can anyone share code how to develop using thumbs
