### ISSUE TITLE
Reload of Child-Objects does not work right

### ISSUE THREAD

**Issue by SerdarN92** [zefoy/ngx-swiper-wrapper#58]
Hi Guys,

with a click on a button iam loading new items in the slider. On the first load, everything works right. It looks like this:

![grafik](https://user-images.githubusercontent.com/7069847/30902448-9d064ba0-a36b-11e7-8e64-aa0300c072b2.png)

But when i click again on the button, to reload the items in the slider it looks like this:

![grafik](https://user-images.githubusercontent.com/7069847/30902480-b867b4ce-a36b-11e7-9a20-fcb7d513e0ac.png)

My configuration for the swiper:
```
config: SwiperConfigInterface = {
    scrollbar: null,
    direction: 'horizontal',
    mousewheelControl: true,
    scrollbarDraggable: true,
    scrollbarSnapOnRelease: true,
    pagination: '.swiper-pagination',
    paginationType: 'bullets',
    paginationClickable: true,
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    breakpoints: {
      480: {
        slidesPerView: 1
      },
      800: {
        slidesPerView: 2
      }
    }
  };
```
The HTML-Code:
```
<div class="row" id="search-result-row">
  <div class="swiper-container result-slider">
    <swiper class="swiper-slide" [config]="config" fxFlex>
      <div class="col s12 m4 l3" style="width: 100%;" *ngFor="let result of results;">
        <div class="card result-card z-depth-2" (click)="showEmployeeInformation(result)">
          <a>
            <div class="card-image" [ngStyle]="{'background': 'url('+result.img+')', 'background-repeat': 'no-repeat'}" >
              <div>
                <span class="card-score card-title grey-text text-darken-4" >{{result.score}}</span>
              </div>
            </div>
            <div class="card-content">
                                <span class="card-title grey-text text-darken-4 truncate">
                                    {{result.name}}
                                    <div class="right chip hide-on-med-and-up">{{result.score}}</div>
                                </span>
            </div>
          </a>
        </div>
      </div>
    </swiper>
  </div>
  <div class="swiper-pagination"></div>
</div>
```

Can you tell me, whats wrong with my code? "results" is just an array of objects.

**Comment by SerdarN92** [comment]
Okay i´ve found that the div class "col s12 m4 13" changes when i click the button again.

First it looks like this:
![grafik](https://user-images.githubusercontent.com/7069847/30903987-d2abb844-a370-11e7-952f-b257870685f4.png)

After clicking again it changes:
![grafik](https://user-images.githubusercontent.com/7069847/30904001-df002a30-a370-11e7-96e7-68d9690ae188.png)


Someone has an idea, why it changes?

**Comment by sconix** [comment]
If you update the contents you might need to call the update function of the swiper to make it refresh the container styles. You can access the update functions through directiveRef. If that does not help then I guess its a styling issue.

**Comment by SerdarN92** [comment]
Hi @sconix  thanks for your answer.

I tried this:
```
<swiper #swiper class="swiper-slide" [config]="config" fxFlex>
```
```
@ViewChild('swiper') swiper;
```
and called this function when button is clicked:
```
this.swiper.update(true);
```

and the result is still the same

**Comment by sconix** [comment]
Could you try to wrap your slide contents within a div, i.e. not to make the for loop in the very first div. Since swiper adds those slide classes on the very first div and now when you run the loop those classes are not reapplied. But by moving the loop inside a div then the main slide div is always there and therefore those slide classes should stay.

**Comment by sconix** [comment]
Since the component only adds the classes if the number of childs changes. So in you case I guess the number stays the same so those classes are not re-added.

**Comment by SerdarN92** [comment]
I always show 5 Children. Not more. 

Can u give me an example how u mean that? Where should i put the loop in?

**Comment by sconix** [comment]
Like just wrap it in extra div:

<div>
<div *ngFor....>
...
</div>
</div>

Or just add the swiper-slide class for the div where you have the ngFor.

**Comment by SerdarN92** [comment]
Adding the swiper-slide class for the div where the ngFor is was the solution!

Thanks @sconix  !!!

**Comment by sconix** [comment]
I leave this open so that I can check if there is some simple check for auto detecting the slide changes.

**Comment by sconix** [comment]
The upcoming release should add the class automatically even in this kind of situation i.e. where number of childs is the same.
