### ISSUE TITLE
Next/Previous on swiper component not working in IE.

### ISSUE THREAD

**Issue by hspier** [zefoy/ngx-swiper-wrapper#59]
Using the examples page in IE11, clicking on the next or previous arrow doesn't change the slide. However, using the wrapper as a directive in the examples page makes it work.

**Comment by sconix** [comment]
I think my example html is missing the doctype which makes IE to run in compatibility mode. I will add the doctype tomorrow and then the example should work in IE as well.

**Comment by sconix** [comment]
It could be also something else, will check tomorrow, but I am pretty sure that the fault is in the example not the library.

**Comment by sconix** [comment]
Seems to be actually bug in the component. Will soon release a fix.

**Comment by tsega** [comment]
@sconix  any updates on this? Currently I'm facing issues when having only two slides in IE11.

**Comment by sconix** [comment]
As you can see this was closed over year a go so fix has been released. And its still working in IE11 for me.

**Comment by tsega** [comment]
Had a custom CSS hiding all slides but the active one; it was interfering with visibility of the first slide only on IE11. Thanks for the quick response! 💨
