### ISSUE TITLE
Glitch at initialization when slidesPerView>1

### ISSUE THREAD

**Issue by cvaliere** [zefoy/ngx-swiper-wrapper#61]
hi

I'm trying to use the plugin with several slides per view
`SwiperConfigInterface = {
    direction: 'horizontal',
    slidesPerView: 4
  }`

and then a very simple HTML
```
<swiper [config]="config">
  <div>
    <div style="background-color:black; height:400px;">toto</div>
  </div>
  <div>
    <div style="background-color:red; height:400px;">toto</div>
  </div>
  <div>
    <div style="background-color:blue; height:400px;">toto</div>
  </div>

</swiper>
```

and there is a short glitch at initialization, where the first div (the black one) has 100% width
it's only a fraction of second, but it's enough to hurt eyes :)

any idea where this comes from?

**Comment by sconix** [comment]
You could try adding swiper-slide class to the div's. It could also be Swipers initialization which is not the fastest since this is just a wrapper and using JS libraries is not optimal when it comes to the rendering. You can always add style visibility hidden and change it on init or some other event such as indexChange (not sure which event is optimal) event when everything should be ready.

**Comment by sconix** [comment]
I might also add some optimizations to this library in near future that help with this. We are close to releasing our app which heavily relies to this library and we have similar "clitches" and depending on the fixes we make in the finalization process if the fix makes more sense in the library it will go there.

**Comment by cvaliere** [comment]
hi, thank you for your answers

we found out that the glitch was because the HTML element is rendered before its width is calculated by Swiper, so it's 100% width for a fraction of second before it gets it "final" width

we managed to get rid of the glitches by setting an initial width to the divs; that width will be overriden by the component after initialisation, but if we give the same width as the final one, it works well

of course, it requires some calculation, and it would be better if the component calculated the width of the divs *before* rendering them

**Comment by sconix** [comment]
The upcoming release uses Swiper 4.x which should also solve many glitches etc. since it has build in mutation observer and other cool stuff to help with these so I will close this issue now since this wont be relevant to the next release which should be out tomorrow.
