### ISSUE TITLE
problem with  async  data 

### ISSUE THREAD

**Issue by reza-mazarlou** [zefoy/ngx-swiper-wrapper#62]
hi
my template :  

```
<div   class="swiper-container" [swiper]="config" >
  <div class="swiper-wrapper">
    
    <div class="swiper-slide"   *ngFor="let Tile of topRateLocations">
      <img [src]="baseUrl+'/'+Tile.bigImage"    >
      <span>{{Tile.name}}</span>
    </div>
  </div>


  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>
```

and my config obj :  
```
  config = {
    lazyLoading: true,
    loop: true,
    slidesPerView: 3,
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    onClick: ( swiper, event) => {
      console.log(event.target.accessKey);
    }
```
**Problem :**  
ngx-swiper-wrapper work very well , but when get async data from rest api and fill it in swipper with *ngFor , ngx-swipper is crashed and show single swipr-slide and missing size and so not working prev button and ...

I try with async pipe like this  :  

```
<div   class="swiper-container" [swiper]="config" >
  <div class="swiper-wrapper">

    <div class="swiper-slide" accessKey="234342"  *ngFor="let Tile of topRateLocations | async">
      <img [src]="baseUrl+'/'+Tile.bigImage"  style="width: 50%"  >
      <span>{{Tile.name}}</span>
    </div>
  </div>


  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>
```
but swiper not working ;

how can I work with ngx-swiper-wrapper with async data ?

**Comment by sconix** [comment]
What do you mean by crash? Whats the error? There should not be no issues with ngFor loop and your code looks correct.

**Comment by reza-mazarlou** [comment]
when I use local Array Object ,  swiper-wrapper work very well but when give data from rest api (async data) swiper-wrapper slider show 1 slide per page and perv button not worked and when I try to resize browser swiper-wrapper slider show 3 slide per page but prev button not worked

**Comment by sconix** [comment]
In most async cases you need to call the update function after Swiper content changes.

**Comment by Max-Lev** [comment]
Can you please add example how to update component in this case: using @Input() binding for *ngFor directive?

**Comment by sconix** [comment]
If it comes from input you need to add set function for the input so that you can call the update after the input changes. So something like this should work:

`
@Input()
set slides(slides) {
  this.swiperSlides = slides;
  this.swiperRef.directiveRef.update(); 
}
`

I am going to add automatic update calling using MutationObserver when the slides change for the next release. I don't know when I have time to do it, but I am hopeful that at the latest during next week. With that release you should not need to call the update after the content changes.

**Comment by sconix** [comment]
So it seems that the latest Swiper 4.x has built in support for mutation observer. I will try to make a new @next release tomorrow which brings Swiper 4 and therefore the manual call for update is not anymore needed if the provided observer option is used. I will notify here once the new release is out.

**Comment by sconix** [comment]
At least with the latest pre-release 5.0.0-5 the observer: true configuration works so the Swiper will update itself if the slides changes asynchronously.
