### ISSUE TITLE
Pagination does not work when slides per group > 1

### ISSUE THREAD

**Issue by ziacik** [zefoy/ngx-swiper-wrapper#63]
There is a calculation that calculates 'real index' from index by multiplying with number of slides per group, but the `realIndex` variable is actually never used.

See https://github.com/zefoy/ngx-swiper-wrapper/blob/master/src/lib/swiper.directive.ts#L281

**Comment by sconix** [comment]
That might be a bug left by some cleanup. I will release a new version which uses the realIndex instead of index.
