### ISSUE TITLE
Using uglify-es instead of uglify-js

### ISSUE THREAD

**Issue by guenam** [zefoy/ngx-swiper-wrapper#65]
Some people (me included) meet a blocking issue when using the ngx-swiper-wrapper npm package in a project with AOT activated. The compilation just hangs (with high CPU and memory being used) and no error at all. So it's difficult to debug.

I had a similar issue months ago where I had to use a specific version of uglify-js to get AOT working, so I investigated into that direction. It appears that:

[UglifyJS github page](https://github.com/mishoo/UglifyJS2) states that:
- _uglify-js only supports ECMAScript 5 (ES5)._
- _Those wishing to minify ES2015+ (ES6+) should use the npm package uglify-es._

The ngx-swiper-wrapper-4.6.6\src\tsconfig.json file mentions "lib": ["dom", "**es2015**"].
And webpack.config.js refers to the UglifyJS plugin.

I'm an amateur dev so I quickly reach my limits. I tried hacking this hypothesis myself but to no success. :-/

I discussed this point with @sconix in the closed issue #46 where someone described having the bug. @sconix says that the hypothesis has some merit.

So, is there someone here skilled enough to make this replacement? I'd make myself super available to make super quick feedback about it.

**Comment by guenam** [comment]
Great, I'll try it as soon as tomorrow! :-)

**Comment by sconix** [comment]
You havent yet resolved this issue? If not can you tell which build system you have?
