### ISSUE TITLE
Can't make Multi Row (& Nested) Layout functionnal

### ISSUE THREAD

**Issue by C-V-K-D** [zefoy/ngx-swiper-wrapper#67]
Hi !
I am working with Ionic and it's been a week that I found out Swiper and this library and it was a relief since they are exactly what I need ! But my problem is that I can't find out how to make things work :disappointed: 
Swiper and ngx-swiper-wrapper are working well since I can see the rendering of some simple layouts, but when I want to make a multi-row layout, it just becomes crazy (my goal is to mix multi-row with nested layouts)

Right now I have put my code aside just to try with really simple code, here it is:

**My .ts file :**
```
import { Component } from '@angular/core';
import { SwiperConfigInterface } from 'ngx-swiper-wrapper';

@Component({
  selector: 'swiper',
  templateUrl: 'swiper.component.html'
})
export class SwiperPage {
  constructor() {  }

  public configTestColumn: SwiperConfigInterface = {
    slidesPerView: 3,
    slidesPerColumn: 2,
    spaceBetween: 30,
    
    pagination: '.swiper-pagination',
    paginationClickable: true,
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev'
  };
}
```

**My .html file :**
```
<ion-header>
    <ion-navbar>
        <ion-title>
            Ionic Blank
        </ion-title>
    </ion-navbar>
</ion-header>
<ion-content padding>
    <div class="swiper-container" [swiper]="configTestColumn">
        <div class="swiper-wrapper">

            <div class="swiper-slide">Slide 1</div>
            <div class="swiper-slide">Slide 2</div>
            <div class="swiper-slide">Slide 3</div>
            <div class="swiper-slide">Slide 4</div>
            <div class="swiper-slide">Slide 5</div>
            <div class="swiper-slide">Slide 6</div>
            <div class="swiper-slide">Slide 7</div>
            <div class="swiper-slide">Slide 8</div>
            <div class="swiper-slide">Slide 9</div>
            <div class="swiper-slide">Slide 10</div>

        </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-scrollbar"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</ion-content>
```
**Result of this code :**
![issue](https://user-images.githubusercontent.com/16120699/31624558-6553c592-b2a3-11e7-9d49-a78aca5b1b3d.png)

I have also added those line in my **_index.html_** file because I saw on the Swiper website that it was required [http://idangero.us/swiper/get-started/#.WeTbOXW0OV4](url) :
```
  <link href="../node_modules/swiper/dist/css/swiper.min.css" rel="stylesheet">
  <script src="../node_modules/swiper/dist/js/swiper.min.js"></script>

```

If anyone could help me I would be so grateful, thank you in advance. I would give you more details if needed !

Thanks,

Cyrille

**Comment by sconix** [comment]
I'll have a quick look later today or tomorrow that if there is some problem with the library styles etc.

**Comment by sconix** [comment]
Sorry that it took this long, but I quickly tried this setup and seems that you need to define the height for the swiper-slide via css. At least I did not see Swiper adjusting it automatically and its styles have default height as 100% hence the slide 1 is pushing the slide 2 out of the view.

**Comment by C-V-K-D** [comment]
Thank you for your answer !
I tried to explore the height of swiper-slide and swiper-container and I obtained those weird results about the position of the slides (I added a background color for clarity) :
**Settings : 2 slides per view & 2 slides per column & direction horizontal**

**swiper-container : no height
swiper-slide : no height**
![no-height](https://user-images.githubusercontent.com/16120699/32167035-fcf28c70-bd67-11e7-8fb8-239327e43830.png)
_______________________________
**swiper-container : height = auto
swiper-slide : no height**
![container-auto-height](https://user-images.githubusercontent.com/16120699/32167033-fcbf6232-bd67-11e7-8506-6dc5d18c7080.png)
_______________________________
**swiper-container : height = auto
swiper-slide : height = 0px
==> nothing displayed**
_______________________________
**swiper-container : height = auto
swiper-slide : height = 100px**
![container-auto-slide-100px-height](https://user-images.githubusercontent.com/16120699/32167034-fcd98752-bd67-11e7-91aa-3236c3f8810d.png)
_______________________________
**swiper-container : height = auto
swiper-slide : height = auto
(this is the same rendering as container height auto & slide no height)**
![container-auto-height](https://user-images.githubusercontent.com/16120699/32167731-1b4000de-bd6a-11e7-9994-16c87a28a619.png)
_______________________________
**swiper-container : no height
swiper-slide : height = 0px**
![slide-0px-height](https://user-images.githubusercontent.com/16120699/32167036-fd0b3c98-bd67-11e7-8393-aabb240735ac.png)
_______________________________
**swiper-container : no height
swiper-slide : height = 10px**
![slide-10px](https://user-images.githubusercontent.com/16120699/32167816-79b7a57c-bd6a-11e7-8ffa-cc39d7fad4e6.png)
_______________________________
_______________________________

I'm okay with the height of the slides, but about the positionning I don't understand what is going on (why do we have this order, for instance slide 2 is not right after slide 1 horizontally neither vertically)

**Comment by sconix** [comment]
What version are you using of this library? Since that looks odd and it should not be this library which causes that. So I am guessing that it might be a bug in Swiper 3.x. The latest @next (5.0.0-5) release usese the new Swiper 4.x so it might be worth the shot.

**Comment by C-V-K-D** [comment]
I'm using version 4.6.6 of this library (the latest i got from npm).
But concerning Swiper I have version 3.4.2
I tried to install Swiper 4.x but the dependency is not what I expected :

![tmp](https://user-images.githubusercontent.com/16120699/32177324-543fe708-bd8a-11e7-85d9-36232a5cf7ad.png)

Do you know when will this new release be available ? As you said, it might be worth the shot !

**Comment by sconix** [comment]
You can install the next release which uses Swiper 4.x by installing ngx-swiper-wrapper@next.

**Comment by C-V-K-D** [comment]
Hi again !
I've been working on something else these days so I just tried that new version this previous couple of days only. The result is that it still doesn't work unfortunately. But the good news is that I have been able to identify some issues about the behaviour of the slides, being clues about the part of the code that may be affected. My tests will complete a very long message though, since I have almost 20 screenshots :s 
Here are my tests :

_________________________________________________
First of all, every bugs that I found involved _**slidesPerColumn**_ option

**1st bug :** Last column mentioned by _slidesPerView_ has a display issue
- **When:** It appears when _slidesPerView_ > 1 and _slidesPerColumn_ > 1 and _spaceBetween_ > 0
- **Why:** I think this problem comes from spaceBetween option because it takes some width that is initially required for the widths of the slides, so the slide of the last column at the screen has no more space to display, thus it goes at the next line
- **Screenshots:** Here are some screenshots to describe it better :
  
**with _spaceBetween_ = 0**
<img width="964" alt="2-2-0-col-3s" src="https://user-images.githubusercontent.com/16120699/32809608-b800a534-c997-11e7-93c0-b5aad21f858b.png">

  **with _spaceBetween_ = 1**
<img width="963" alt="2-2-1-col-3s" src="https://user-images.githubusercontent.com/16120699/32809615-bcb5267c-c997-11e7-9c4e-bf94c4c39fe4.png">

And it's the same result when I set _slidesPerColumnFill_ to _'row'_ :
<img width="964" alt="2-2-0-row-3s" src="https://user-images.githubusercontent.com/16120699/32809690-14cc045c-c998-11e7-9746-8b3b9ffc298d.png">
<img width="957" alt="2-2-1-row-3s" src="https://user-images.githubusercontent.com/16120699/32809691-15034e44-c998-11e7-8d09-fce4070e3fa3.png">

- **More:** I don't know if this is done on purpose but the only way I see it usable is by mentioning an extra slide per view (let’s say you want slidesPerView = 3, you’ll then mention slidesPerView = 4), and using that extra width for spaceBetween and padding left and right option to adjust the display of your slides

_________________________________________________

**2nd bug :** _slidesPerColumn_ "almost inactive when used with _slidesPerColumnFill = 'row'_
- **Why:** My guess is that it has to deal with the code probably ?
- **Screenshots:** 

**_slidesPerColumnFill: 'row' & slidesPerColumn: 2_**
**(In the following I increase the number of slides to see the difference)**
<img width="964" alt="2-2-0-row-3s copy" src="https://user-images.githubusercontent.com/16120699/32811980-f45e12fe-c9a2-11e7-9e09-64cdd601093f.png">
<img width="963" alt="2-2-0-row-4s" src="https://user-images.githubusercontent.com/16120699/32811981-f472b3e4-c9a2-11e7-83f0-491969b554b8.png">
<img width="967" alt="2-2-0-row-5s" src="https://user-images.githubusercontent.com/16120699/32811982-f48ba930-c9a2-11e7-90b6-eac7b8446553.png">
<img width="965" alt="2-2-0-row-6s" src="https://user-images.githubusercontent.com/16120699/32811983-f4a71738-c9a2-11e7-8983-e073740491ac.png">
<img width="967" alt="2-2-0-row-8s" src="https://user-images.githubusercontent.com/16120699/32811984-f4bdd9b4-c9a2-11e7-9de5-a8593bf52014.png">
<img width="964" alt="2-2-0-row-20s" src="https://user-images.githubusercontent.com/16120699/32811985-f4d31716-c9a2-11e7-8eae-088f1f4ee0d0.png">

**_slidesPerColumnFill: 'row' & slidesPerColumn: 20_**
<img width="964" alt="2-20-0-row-20s" src="https://user-images.githubusercontent.com/16120699/32812012-2a2c0d50-c9a3-11e7-81e2-a98b36fbd7be.png">

**_slidesPerColumnFill: 'row' & slidesPerColumn: 56_**
<img width="965" alt="2-56-0-row-20s" src="https://user-images.githubusercontent.com/16120699/32812024-32c0c96a-c9a3-11e7-9c74-2f2d159d2f32.png">


**_slidesPerColumnFill: 'COLUMN' & slidesPerColumn: 56_**
<img width="965" alt="2-56-0-col-20s" src="https://user-images.githubusercontent.com/16120699/32812079-701f1f78-c9a3-11e7-8c1f-bf08482702ea.png">

**_slidesPerColumnFill: 'COLUMN' & slidesPerColumn: 20_**
<img width="964" alt="2-20-0-col-20s" src="https://user-images.githubusercontent.com/16120699/32812797-27589734-c9a7-11e7-8521-38a501ab537e.png">

**_slidesPerColumnFill: 'COLUMN' & slidesPerColumn: 19_**
**(do not give attention to the specific position of each slide separately, only the global disposition is the matter here, I’ll come back later about the specific position of each slide)**
<img width="964" alt="2-19-0-col-20s" src="https://user-images.githubusercontent.com/16120699/32812816-393576e8-c9a7-11e7-942f-86aecf5ea5d6.png">

**_slidesPerColumnFill: 'COLUMN' & slidesPerColumn: 2_**
<img width="962" alt="2-2-0-col-20s" src="https://user-images.githubusercontent.com/16120699/32812822-43863268-c9a7-11e7-9670-7cb6404fa788.png">

**_slidesPerColumnFill: 'COLUMN' & slidesPerColumn: 1_**
<img width="966" alt="2-1-0-col-20s" src="https://user-images.githubusercontent.com/16120699/32812827-4bf0b572-c9a7-11e7-8750-1d1a76777eca.png">

- **More:**
- Clearly there is no difference to set the slidesPerColumn option to 2, 20, or 56 when the slidesPerColumnFill option is set to ‘row’, it’s like there are only 2 options possible :
**==> first option** triggered when _slidesPerColumn_ **equals 1 (or 0**, both give the same result), resulting in a single row,
**==> second option** triggered when **_slidesPerColumn_  > 1** (in the examples I gave: 2, 20, 56)
- In the opposite, we can see the difference when the _slidesPerColumnFill_ option is set to ‘column’, even though this case has also a problem :
**==> If slidesPerColumn >= number of slides** : then it behaves the way it has to do
**==> If 2 <= slidesPerColumn < number of slides** : then all slides are displayed into two columns, with a number of slides per column different from the parameter slidesPerColumn
**==> If slidesPerColumn = 1 (or slidesPerColumn = 0)** : then it behaves as it should, displaying slides on a single row (giving the possibility to actually slide through the slides)

_________________________________________________

**3rd bug :** _slidesPerColumn_ working strangely when used with _slidesPerColumnFill = ‘column’_, slides that should be “displayed" outside the screen are actually being displayed on the screen, below their previous slides, and thus, not following the _slidesPerColumn: number_ parameter
- **Why:** My guess is that there may also be some mistakes in the code ?
- **Screenshots:**
<img width="964" alt="2-2-0-col-3s copy" src="https://user-images.githubusercontent.com/16120699/32814354-fe1f1b7e-c9ae-11e7-8a9d-21736fcccf31.png">
<img width="967" alt="2-2-0-col-4s" src="https://user-images.githubusercontent.com/16120699/32814355-fe35a10a-c9ae-11e7-9afc-df1f898c9da7.png">
<img width="964" alt="2-2-0-col-5s" src="https://user-images.githubusercontent.com/16120699/32814356-fe4b30f6-c9ae-11e7-8f1f-cec0ae2761d8.png">
<img width="966" alt="2-2-0-col-6s" src="https://user-images.githubusercontent.com/16120699/32814357-fe624976-c9ae-11e7-935d-c46f12fb7108.png">
<img width="964" alt="2-2-0-col-7s" src="https://user-images.githubusercontent.com/16120699/32814358-fe7c5fd2-c9ae-11e7-9d9a-abf668015c84.png">
<img width="962" alt="2-2-0-col-8s" src="https://user-images.githubusercontent.com/16120699/32814359-fe92e77a-c9ae-11e7-9b99-386a8335044a.png">
<img width="963" alt="2-2-0-col-9s" src="https://user-images.githubusercontent.com/16120699/32814360-fea8d4a4-c9ae-11e7-8f49-10f5102e652a.png">
<img width="969" alt="2-2-0-col-10s" src="https://user-images.githubusercontent.com/16120699/32814361-febf2060-c9ae-11e7-9d41-91b4f3d9c911.png">
<img width="966" alt="2-2-0-col-11s" src="https://user-images.githubusercontent.com/16120699/32814362-fed72a16-c9ae-11e7-9acb-e4bf30f24ca3.png">
<img width="964" alt="2-2-0-col-12s" src="https://user-images.githubusercontent.com/16120699/32814363-feed01b0-c9ae-11e7-8597-ed21af920c4c.png">

- **More:** As you can notice, when a slide should be placed in a new column, it is actually appearing somewhere else, but that “somewhere else” isn’t random. If you pick Slide 5, it is supposed to be placed at the right of the Slide 3, but instead it is placed juste below Slide 1. But maybe this presents no contradiction in the code depending of the structure of the swiper-container, leading to this question : is it an one-dimensional array or a two-dimensional array ? If it is an one-dimensional array, then the position below Slide 1 corresponds to the next position of Slide 3.


I hope I have been clear on those points.

Actually my whole trouble comes from MultiRow Slider, with the parameter _slidesPerColumn_ 

Don't hesitate to tell me if I'm wrong anywhere !

**Comment by sconix** [comment]
So you are now using the version 5 of this library i.e. Swiper 4.x? It definitely looks like a bug and I am 99% sure that its not due to this wrapper so maybe you could make this report in Swiper issues. At least I don't have a clue that how Angular or this library could be effecting.

**Comment by C-V-K-D** [comment]
Thank you for your very fast reply !
Yep I'm using those version
<img width="212" alt="version_swiper_ngx-swiper-wrapper" src="https://user-images.githubusercontent.com/16120699/32837039-385051ca-ca0c-11e7-8009-3ca8abc5a52b.png">

I'm going to follow your advice and report this in Swiper issues, I'll let the "tag" here or the link to the new issue I will create (I don't know very well how this works, it's like the first time I'm posting an issue) and will close this issue then !

**Comment by sconix** [comment]
Yes please do link it here so in the case that Swiper developer can't find a bug or can give some insights what could be causing the problem. And you can leave this issue open until resolved in either Swiper's end or here.

**Comment by C-V-K-D** [comment]
Thank you very much for your help, let's do that this way then !

- spaceBetween bug : https://github.com/nolimits4web/Swiper/issues/2330
- slidesPerColumn + slidesPerColumnFill = 'row' : https://github.com/nolimits4web/Swiper/issues/2331
- slidesPerColumn + slidesPerColumnFill = 'column' : https://github.com/nolimits4web/Swiper/issues/2332
