### ISSUE TITLE
directiveRef.setIndex(index) is not changing the active swiper

### ISSUE THREAD

**Issue by OpenSourceName** [zefoy/ngx-swiper-wrapper#68]
I need to change the active swiper, so i referenced the swiper using
`<swiper #swiperView ... >
` in the html and i called it in the component   
`@ViewChild('swiperView') swiperView: SwiperComponent;
`
But when i call the function 
`          this.swiperView.directiveRef.setIndex(initialSlide);
`
nothing occured in my swiper.
Finally, the expected is that the swiper change its active component.

Thank you

**Comment by sconix** [comment]
Are you using some special config like loop etc? At least the setIndex is working just fine in our app.

**Comment by OpenSourceName** [comment]
this is my swip config
```
{
    scrollbar: null,
    spaceBetween: 30,
    direction: 'horizontal',
    slidesPerView: 3,
    scrollbarHide: false,
    keyboardControl: true,
    mousewheelControl: true,
    scrollbarDraggable: true,
    scrollbarSnapOnRelease: true,
    paginationClickable: true,
    loop: false,
    slideToClickedSlide: true,
    initialSlide: 0
  }
```

**Comment by sconix** [comment]
Are you sure that you are calling the setIndex after the Swiper has been initializef (i.e. after ngAfterViewInit).

**Comment by OpenSourceName** [comment]
I am calling it in ngOnInit

**Comment by sconix** [comment]
Can you try calling it in AfterViewInit? Since you have the initialSlide: 0 in the config so I am guessing that causes your setIndex on ngOnInit being ignored.

**Comment by OpenSourceName** [comment]
There is a problem, when i call it inside ngAfterViewInit it is working well, but when i call it outside , it is always setting the last index

**Comment by sconix** [comment]
As long as it called after view init it should work. Otherwise I would need a way to reproduce it, we dont have any issues with setIndex and there really should not be a way for it to not work. The only thing that could have an effect is the initialSlide config, have you tried without it.

With the component there is also another way to control the index the index input.
