### ISSUE TITLE
Angular 2 - Not able to compile

### ISSUE THREAD

**Issue by deepanshu203** [zefoy/ngx-swiper-wrapper#69]
Hi,

I am getting the below error when trying to compile:

ERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exporte d function, resolving symbol SWIPER_GUARD in <Location>

Is it a know issue for Angular 2?

**Comment by sconix** [comment]
The latest versions of this library wont anymore support Angular 2. You really should upgrade to Angular 4 since 5 is almost out already and support for Angular 2 will be stopped.

**Comment by deepanshu203** [comment]
Thanks for confirming. Appreciate your quick reply.
Actually it is not up to me to decide the angular version we use for our project.
