### ISSUE TITLE
How can i  pass  pagination parameter to swiper config ?

### ISSUE THREAD

**Issue by paullauyc** [zefoy/ngx-swiper-wrapper#70]
public config: SwiperConfigInterface = {
    scrollbar: null,
    direction: 'horizontal',
    slidesPerView: 1,
    scrollbarHide: false,
    keyboardControl: true,
    mousewheelControl: true,
    scrollbarDraggable: true,
    scrollbarSnapOnRelease: true,
    _**pagination: {el:'.swiper-pagination', dynamicBullets: true},**_
    paginationClickable: true,
  };

**Comment by sconix** [comment]
This library uses 3.x version of Swiper, that format is for Swiper 4.x. I will be releasing new version that uses Swiper 4.x during next week.

**Comment by paullauyc** [comment]
Thanks you
