### ISSUE TITLE
Any way to put the navigation arrows outside the slider?

### ISSUE THREAD

**Issue by dalvarezr** [zefoy/ngx-swiper-wrapper#71]
Been looking for a work around this, but when ever I try to put the navigation arrows outside the <swiper> element and bind it to the configuration in my TS code it won't work. I asume because it needs to be inside the wrapper...
Also couldn't achieve this with pure CSS. 
Any help for a newbie? :(

*Also waiting for server side rendering updates*

Example of what I need:
https://medium.com/@networkaaron/swiper-relocating-previous-and-next-buttons-1ae792f22ef
(credits for that codePen example are not mine, just used as an example)

**Comment by sconix** [comment]
No control needs to be inside this element. I am not sure how Swiper searches for the elements if you just give an class, but if you pass in directly the HTMLElement in the config then it should be possible to be anywhere. And of course even if they would be inside the element you can always position them to be outside with CSS and absolute positioning.

**Comment by sconix** [comment]
The upcoming release will use Swiper 4.x which should have server side rendering support although I already bumped into an Swiper issue saying that there still was some feature that broke server side rendering, but I believe fix is coming if it not already in the latest Swiper release.

**Comment by sconix** [comment]
I just made a new pre-release 5.0.0-5 which uses Swiper 4.x. I haven't tested if the server side rendering issues have been fixed, but if some found then I suggest to report them in the Swiper issues so those will get fixed. At least the server side rendering support for mentioned in the 4.x changelog.
