### ISSUE TITLE
vertical layout / directive

### ISSUE THREAD

**Issue by laclac777** [zefoy/ngx-swiper-wrapper#72]
I have the directive approach:
`<div class="swiper-container" [swiper]="swiperConfig">`
if I set the direction to ‘vertical’ the swiper-button-prev, swiper-button-next still follow the horizontal layout. How can I flip these buttons to vertical with the directive approach?

**Comment by sconix** [comment]
Swiper does not support the buttons in vertical layout, i.e. it does not have styles for them. You can copy the styles from the component for example.

**Comment by laclac777** [comment]
Strange but with the “Component” mode the buttons vertical layout well supported and the demo itself reflects the same.

**Comment by sconix** [comment]
Yes since I have added the styles for vertical buttons for the component. For directive I can't add styles so its "pure" Swiper.
