### ISSUE TITLE
How can I get slide index in on-change?

### ISSUE THREAD

**Issue by sijithc40** [zefoy/ngx-swiper-wrapper#73]
This is the code I am using.

`<swiper [config]="adslide" class="ad-slider" #adSlider (indexChange)="onIndexChange($event)" [initialize]="isBannerLoaded">
                <div class="swiper-wrapper">
                    <div class="swiper-slide" *ngFor="let bnr of displayBanners">
                        <img *ngIf="bnr.button_title" src="{{bnr.image}}" alt="" class="responsive-img">
                    </div>
                </div>
                <div class="swiper-pagination">
                    <span>
                        <a class="pagination" [ngClass]="{active:activeindex==i}" *ngFor="let bnr of displayBanners; let i = index" (click)="adSlider.swiper.slideTo(i); activeindex=i" >
                        </a>
                    </span>
                </div>
                 <a class="swiper-button-next" data-test-id="ad-slider-next" (click)="adSlider.swiper.slideNext()"><i class="material-icons">keyboard_arrow_right</i></a>
                <a class="swiper-button-prev" data-test-id="ad-slider-prev" (click)="adSlider.swiper.slidePrev()"><i class="material-icons">keyboard_arrow_left</i></a> 
            </swiper>`

adslide: SwiperOptions = {
    pagination: '.swiper-pagination',
    autoHeight:true,
    preventClicks: false,
    preventClicksPropagation: false,
    spaceBetween: 0,
    speed: 600,
  };

**Comment by sconix** [comment]
Not sure I understand the question you already have the (indexChange) which is the way.

**Comment by sijithc40** [comment]
it was not working in angular2-useful-slide , Now I updated to ngx-swiper-wrapper and it is working. Thanks for the quick reply. :) 

I have another doubt, I want to loop swiper for multiple swiper in one page. But next and previous button working only for first slider. Can you help me to sort out it ? Thanks

**Comment by sconix** [comment]
You need to either use different classes or give the HTMLElement directly since the logic how Swiper searches those components with class is bit inaccurate.

**Comment by sijithc40** [comment]
but the swipers coming from loop (*ng-for) how can I give multiple classes and how do I manage it in ts file ?

**Comment by sconix** [comment]
You can define the used classes in the config object. So you just use different config for each swiper and then use different class names for the components.

**Comment by sijithc40** [comment]
So I should loop the config in the ts file right?

**Comment by sconix** [comment]
If you generate the swipers with ngFor loop you can use the index, so something like:

`
<ng-container *ngFor="......; let i">
<swiper [config]="{nextButton: 'swiper-button-next-' + i}">
...
<div class="swiper-button-next swiper-button-next-{{i}}"></div>
</swiper>
`

I will be soon releasing new version that uses Swiper 4.x and I am trying to fix this need for different class names so that everything would just work. But the above should work in the mean while.

**Comment by sconix** [comment]
I just released new pre-release 5.0.0-5 which uses Swiper 4.x and at least with that I did not need to use different classes when using multiple swipers.

**Comment by sijithc40** [comment]
Thank you sconix
