### ISSUE TITLE
feature-request: get the number of indices

### ISSUE THREAD

**Issue by Oliver-Piorun** [zefoy/ngx-swiper-wrapper#75]
Hey! First of all: Good job! I really like this swiper and the ongoing rewrite.

However, I am craving for a feature. In our project we have to the set the swiper index to a specific value. The problem is that we can't tell if this index is in bounds because "getIndex()" only returns the current index. Do you have something in mind regarding this issue?

Greetings

**Comment by sconix** [comment]
So do you mean that you want to know how many slides there is? I am just wondering that how you don't know that since don't you have some array that you use to generate the slides or have a fixed amount of them, So if you could describe the problem bit more it would help.

**Comment by Oliver-Piorun** [comment]
Yes, exactly. I have an array but when using breakpoints (with different number of slides per breakpoint) there is no reliable way for me to get the current number of slides.

**Comment by sconix** [comment]
Swiper has means to get the slides array. So check Swiper documentation how to get the slides.

**Comment by Oliver-Piorun** [comment]
I see. Thanks! This can be closed :)
