### ISSUE TITLE
ng build --prod causes error

### ISSUE THREAD

**Issue by apoorvakorde-tcs** [zefoy/ngx-swiper-wrapper#76]
running "ng build --prod" in a downstream project causes following error:

ERROR in vendor.e9420a50e0e6f49babb7.bundle.js from UglifyJs
Unexpected token: name (Dom7)  [vendor.e9420a50e0e6f49babb7.bundle.js:17387,6]

**Comment by benjackson84** [comment]
Looks related to https://github.com/nolimits4web/Swiper/issues/2263, seemingly an issue with the latest version of Swiper, current solution is to downgrade to 3.x.x.

**Comment by sconix** [comment]
You need to use the latest angular-cli (1.5.0-rc.8). New Swiper uses ES6 and the ES6 uglify support was added just recently.
