### ISSUE TITLE
after upgrading to ngx-swiper-wrapper v5 my slides are not initializing correctly

### ISSUE THREAD

**Issue by zurie** [zefoy/ngx-swiper-wrapper#78]
I originally had a component of the ngx-swiper-wrapper.  I was using         playSwiper.stopAutoplay(); but with v5 it no longer worked.  I switched from the component to the directive.

Now using the directive I cannot get the swiper to properly initialize when the view loads, I have to run 
      playSwiper.update();
on ngInit

secondly.  The index says this in console.log  Even though I have 5 slides... 

play.component.ts:64 Swiper index:  1
play.component.ts:64 Swiper index:  0
play.component.ts:64 Swiper index:  1
play.component.ts:64 Swiper index:  0
play.component.ts:64 Swiper index:  1
play.component.ts:64 Swiper index:  0
play.component.ts:64 Swiper index:  1
play.component.ts:64 Swiper index:  0
play.component.ts:64 Swiper index:  1

as soon as i RESIZE my view to one of the 3 breakpoints, the swiper realizes it needs to have more than 2 slides and it starts working. but on init on any of the 3 breakpoints it only shows a index of two slides. 

this was working perfectly in v4 but going to 5 something is off.  Maybe you see something strange in my template and code?  Again, using v4 and using a component <swiper></swiper> it was working fine and the only reason I went to the directive was to get start and stop to work when I used my scrollspy and scrolled into view (start) and scroll out (stop) etc.

```
import {Animations} from '../../../animations';
import {AfterViewInit, Component, OnDestroy, OnInit, ViewChild} from '@angular/core';
import { SwiperDirective
} from 'ngx-swiper-wrapper';


@Component({
  selector: 'app-about-play',
  templateUrl: './play.component.html',
  styleUrls: ['./play.component.scss'],
  animations: Animations.page
})
export class AboutPlayComponent implements AfterViewInit, OnDestroy {

  private smSC = new ScrollMagic.Controller({container: '#content'});
  @ViewChild(SwiperDirective) swiperView: SwiperDirective;

  public onIndexChange(index: number) {
    console.log('Swiper index: ', index);
  }

  ngOnDestroy(): void {
    this.smSC.destroy();
  }

  ngAfterViewInit(): void {
    this.swiperView.update();
    this.swiperView.stopAutoplay();
  }

}
```

and my module
```
import { NgModule } from '@angular/core';
import { SharedModule } from '../shared.module';
import { UIRouterModule} from '@uirouter/angular';
import { ABOUT_STATES } from './about.states';
import { AboutComponent } from './about.component';
import {
  SWIPER_CONFIG,
  SwiperAutoplayInterface, SwiperBreakpointsInterface, SwiperConfigInterface, SwiperModule,
  SwiperPaginationInterface, SwiperScrollbarInterface
} from 'ngx-swiper-wrapper';
import { SpacerComponent } from '../spacer/spacer.component';
import { AboutHeaderComponent } from './header/header.component';
import { AboutFooterComponent } from './footer/footer.component';
import { AboutContentComponent } from './content/content.component';
import { AboutBgComponent } from './bg/bg.component';
import { AboutPlayComponent } from './play/play.component';
import {RoundNumberPipe} from '../shared/pipes/round';
import {AboutMusicModule} from './music/music.module';

const breakpoints: SwiperBreakpointsInterface = {
  1024: {
    slidesPerView: 4,
    spaceBetween: 40,
  },
  767: {
    slidesPerView: 3,
    spaceBetween: 20,
  },
  479: {
    slidesPerView: 2,
    spaceBetween: 10

  }
};

const autoplay: SwiperAutoplayInterface = {
  delay: 2000,
  stopOnLast: false
};

const config: SwiperConfigInterface = {
  direction: 'horizontal',
  slidesPerView: 4,
  spaceBetween: 40,
  breakpoints: breakpoints,
  centeredSlides: true,
  keyboard: true,
  mousewheel: false,
  freeMode: false,
  speed: 1000,
  autoplay: autoplay,
  effect: 'slide',
  grabCursor: true,
  loop: true,

};

@NgModule({
  imports: [
    SharedModule,
    AboutMusicModule,
    UIRouterModule.forChild({ states: ABOUT_STATES }),
    SwiperModule
  ],
  providers: [
    {
      provide: SWIPER_CONFIG,
      useValue: config
    }
  ],
  declarations: [
    AboutComponent,
    AboutBgComponent,
    RoundNumberPipe,
    AboutFooterComponent,
    AboutHeaderComponent,
    SpacerComponent,
    AboutContentComponent,
    AboutPlayComponent,

  ]
})
export class AboutModule { }

```

and my HTML

```
<div class="slide-wrapper" id="play">
  <div class="stats-header">Since I started coding this website...</div>
  <div [swiper] class="swiper-container"  (indexChange)="onIndexChange($event)">
    <div class="swiper-wrapper">
      <div *ngFor="let slide of aboutSlides" ngClass="{{slide.id}}" class="swiper-slide">
            <i class="material-icons">{{slide.icon}}</i>
            <h1>{{slide.amount}}</h1>
            <p>{{slide.title}}</p>
      </div>
    </div>
  </div>
</div>
```

**Comment by sconix** [comment]
I'll test this today, most likely its a bug from upgrading to Swiper 4.x, but lets see. I'll get back to you once I have figured what the problem is.

**Comment by zurie** [comment]
observer: true   has no effect.  same issue.

I stared using your "component" version <swiper></swiper>   When I upgraded to v5 it threw an error saying   something about stopAutoplay() not being available and did i mean S_AUTOPLAY instead?  etc.  So i didnt know exactly what to do to fix that so i just swapped from Component <swiper> to directive <div class="swiper-container" [swiper]=config> </div>  Using a DIV with the directive instead of a component (element).    thats what i did when i said i had to swap.

its not initializing the swiper correctly in my app,   yes it looks correct because it use to work before v5, I think there is something thats happening when you resize and hit a new breakpoint, like the config loads correctly, etc.   even on the first load the slides don't "loop" graphically, they are just from LEFT to right with a big gap on the left.  as soon as i resize to a new breakpoint the slides FILL in and correctly loop both to the LEFT edge to the RIGHT edge of my screen and they correctly index from 0 to the end, instead of just 0, 1, 0 1 etc.    I think it might be some sort of like change detection or something where the view needs a second or needs more info to correcly load swiper, otherwise, i don't know what to tell you, its just not the same as v4  i can roll back and call it a day but i just don't know why this would be perfect on v4 and not right on v5 unless its something I did refactoring it to v5 or something in the code internally

**Comment by sconix** [comment]
If you are trying to call the the stopAutoplay through the component reference then thats the issue. The directive api is now available through the directiveRef, so you need to call it componentRef.directiveRef.stopAutoplay(). I removed the duplicate code from the component. Or if you are trying to call it through Swiper instance then that call has changed to swiper.autoplay.stop().

I copied your template and settings from your post to the example app and it works properly. It looks correct and works as it should and I don't need to resize nor make an update call. So atm I am not able to replicate your problem. If you can make Plunkr example where the problem occurs I can have a look.

Swiper 4.x has changed a lot so its possible that you have bumped into Swiper bug as well.

**Comment by zurie** [comment]
can you zip up what you have or post a stack blitz for me, maybe I can see something else from it.  I swapped to the directive to use stopAutoplay thats why i used directiveRef,  etc.   Another thing is that I am using angular animations, :enter and :leave for my view, perhaps there is something with the view itself still animating and the swiper is not loaded, if you can show me a http://stackblitz.com of it working maybe i can add in some animations and see if it stops working, I am going to try to pull some animations out of my current project and see if that helps, but again i was doing this with v4 including the animations, so ill have to see.  
ill keep testing and see if i can find the issue.

**Comment by zurie** [comment]
also using "Augury" this is what i see when I first load up the page  note the "isBeginning: true" isEnd "true" and the slide index.  its just not loaded up right.   of course if i add update() afterviewinit or on NgInit then it kicks in and does index 0 1 0 1 until I resize to a new break point  etc

```
instance:
Swiper
 el:
null
 wrapperEl:
null
 isHorizontal:
function isHorizontal() {}
 isVertical:
function isVertical() {}
 rtl:
false
 wrongRTL:
false
 activeIndex:
0
 realIndex:
0
 isBeginning:
true
 isEnd:
true
 translate:
0
 progress:
0
 velocity:
0
 animating:
false
 allowSlideNext:
true
 allowSlidePrev:
true
 allowClick:
true
 allowTouchMove:
true
 imagesLoaded:
0
 currentBreakpoint:
767
 width:
568
 height:
0
 size:
568
 virtualSize:
568
 snapIndex:
0
 previousIndex:
3
 onTouchStart:
function bound_onTouchStart() {}
 onTouchMove:
function bound_onTouchMove() {}
 onTouchEnd:
function bound_onTouchEnd() {}
 onClick:
function bound_onClick() {}
 initialized:
true
```

this is what i see after i resize and hit a new break point 
```
instance:
Swiper
 el:
null
 wrapperEl:
null
 isHorizontal:
function isHorizontal() {}
 isVertical:
function isVertical() {}
 rtl:
false
 wrongRTL:
false
 activeIndex:
1
 realIndex:
1
 isBeginning:
false
 isEnd:
false
 translate:
0
 progress:
0.25
 velocity:
0
 animating:
false
 allowSlideNext:
true
 allowSlidePrev:
true
 allowClick:
true
 allowTouchMove:
true
 imagesLoaded:
0
 currentBreakpoint:
767
 width:
568
 height:
205
 size:
568
 virtualSize:
960
 snapIndex:
1
 previousIndex:
0
 onTouchStart:
function bound_onTouchStart() {}
 onTouchMove:
function bound_onTouchMove() {}
 onTouchEnd:
function bound_onTouchEnd() {}
 onClick:
function bound_onClick() {}
 initialized:
true
 swipeDirection:
next
 clickedSlide:
undefined
 clickedIndex:
undefined
```

**Comment by zurie** [comment]
ok sorry for blowing you up! :)  here is what I have.   Using the below config, inculding observer: true, I do not have to use update() on ngInit, it correctly works right off the bat,  you are 100% on that thanks!.   BUT.  the issue is

loop: true,

as soon as i remove loop: true, it works 100% (minus it looping in a circle) as soon as i turn loop: true on, it starts to incorrectly index and it goes from 0 1 0 1 0 1.

maybe that might be something?  thoughts?

```
const breakpoints: SwiperBreakpointsInterface = {
  1024: {
    slidesPerView: 4,
    spaceBetween: 40,
  },
  767: {
    slidesPerView: 3,
    spaceBetween: 20,
  },
  479: {
    slidesPerView: 2,
    spaceBetween: 10
  }
};

const autoplay: SwiperAutoplayInterface = {
  delay: 2000,
  stopOnLast: false
};

const config: SwiperConfigInterface = {
  runCallbacksOnInit: true,
  normalizeSlideIndex: true,
  initialSlide: 2,
  direction: 'horizontal',
  slidesPerView: 4,
  spaceBetween: 40,
  breakpoints: breakpoints,
  centeredSlides: true,
  keyboard: true,
  mousewheel: false,
  freeMode: false,
  speed: 1000,
  autoplay: autoplay,
  effect: 'slide',
  grabCursor: true,
  observer: true
};
```

**Comment by sconix** [comment]
For me the index did run correctly, 0 1 2 3 4  etc. What is the exact version of the swiper you have installed? I just want to be sure that we are using same version.

**Comment by zurie** [comment]
```
    "ngx-swiper-wrapper": {
      "version": "5.0.0",
      "resolved": "https://registry.npmjs.org/ngx-swiper-wrapper/-/ngx-swiper-wrapper-5.0.0.tgz",
      "integrity": "sha512-3KCICmSAdYmPXXjyyXko1h4U5zqMOYutCShzgjGHwVKDDOF+3Nxu2x/FD2x97WPB/8Y7PXlL5xk64wGqsy8PbQ==",
      "requires": {
        "swiper": "4.0.5"
      }
    },

and for swiper

/**
 * Swiper 4.0.5
 * Released on: November 7, 2017
 */
```

**Comment by sconix** [comment]
I seem to be running bit older (4.0.2) I will test with the latest to see if it has any effect.

**Comment by zurie** [comment]
I downgraded to 4.0.2 same thing, 4.0.0 same thing, but this fixed it.

setting ```loop: false``` in my main config.

then 

```
  ngAfterViewInit(): void {
    this.swiperView.config = { loop: true };
  }
```

It has to be some sort of timing issue with either my environment or some other 3rd party library, or something thats changed from 4.0 to 5.0 or something thats changed from swiper 3.4.2 to 4.0.0

I was on swiper 3.4.2 and Angular 4.4.6  when I started this project and recently I upgraded to 5.0.0 no problems.  But yesterday I went from Swiper 3.4.2 to 4.0.5 so it might be something significant in there thats changed? not sure, but setting loop:false and then after init setting loop true works, as well as changing the breakpoint.  So those two things trigger something similar probably in the swiper core.  for now I am good with my hack but if you want me to test out some stuff for you I am willing, if you want me to zip my project up I have no problem doing that either although its large but its angular-cli so its easy to fire up.

**Comment by sconix** [comment]
Thanks for the info, I'll see if I can replicate with that additional information to verify that there is no bug in this library that its either Swiper or some weird combination of libraries.

**Comment by zurie** [comment]
cool thanks!  you can see it working at https://zadesigns.com/about down at the bottom.  when you scroll into view it starts when you scroll out it stops, and if you resize it, it swaps around via the breakpoints.  I actually didn't have to do loop:false, all i had to do was set  loop:true in the ngafterviewinit

**Comment by sconix** [comment]
The only difference in my testing was that I used the custom config not global like you. So I will test it tomorrow if I can replicate it with the global config, but I must say that afaik there should not be difference if its from global config or its set in custom config, the initialization process should be the same. So my current guess is that you / this library just triggered some sort of race condition i.e. bug in Swiper. So I will try to replicate this tomorrow so I could narrow it down that what caused it. I'll let you know in this thread if I find the cause, if not then I guess we just have to wait until more info comes along through another issue for this lib or Swiper.

**Comment by hitandyrun** [comment]
Sorry to dig up an old issue. But I had the same thing happen to me. The solution i found was to set loop: false and then change loop to true after the slider has been initialized.
Same, or at least very similar behavior as described above. After a resize (I wasn't using any breakpoints) the slider would work properly. Setting observer to true had no effect either.
Tried creating the slides both using the async pipe and without. 
Also changing any aspect of the directive (I'm using the directive, not the component) via Augury caused the directive to perform normally, the bug disappeared.

When loading Swiper from a cdn and initializing it manually works without a problem as well.

This issue didn't happen with version 4 of this package and Swiper 3. I wish I could provide more information.

**Comment by sconix** [comment]
I believe that there is some bug in the Swiper 4.x regarding the update function that it does not set all values correctly which effect the loop parameter specially. When I have time I will look into it more closely, but until that we need to hope that the Swiper releases will fix the issue.
