### ISSUE TITLE
Slide prev/next transition is not working

### ISSUE THREAD

**Issue by lares83** [zefoy/ngx-swiper-wrapper#80]
In swiper directive after invoking `nextSlide()` or `prevSlide()` transition is not working.

What I noticed in source code that parameters are switched.

In `swiper.directive.ts` `silent` parameter is first parameter and `speed` is second

```this.instance.slideNext(!silent, speed);```

but according to the swiper spec `speed` should be first

```mySwiper.slideNext(speed, runCallbacks);```

**Comment by sconix** [comment]
So it seems that there is a small typo :) Thanks, will fix and release a new version.

**Comment by lares83** [comment]
Thanks :)
