### ISSUE TITLE
Script performance issue in IE11

### ISSUE THREAD

**Issue by shridharkurhade** [zefoy/ngx-swiper-wrapper#82]
I am using the swiper control to  bind async data, so I am setting observer flag as true. Also, I have other angular components on the same page/module. Everything works fine in chrome, but if anything is clicked in other components, the swiper control re-binds the data again and the scripts says not responding in IE11.
I think its because of observer, so I removed the this flag, the async data binding and window re-size doesn't work properly.
Please suggest solution to improve the performance in IE.

**Comment by sconix** [comment]
You might want to ask this in Swiper issues that if there is a bug in the observer code when running in IE. With this wrapper I don't think you can do anything else than disable observer and call update manualyl when ever the view is updated / resized.

**Comment by sconix** [comment]
I can also have test to see if I can reproduce this when I have time so that I could verify that its not the wrapper causing the problems, but I doubt it.
