### ISSUE TITLE
Upgraded to material 5, swiper doesn't work

### ISSUE THREAD

**Issue by sefo** [zefoy/ngx-swiper-wrapper#83]
After upgrading to angular 5 / material 5 a style on the swiper-wrapper is not set correctly.

![image](https://user-images.githubusercontent.com/437441/33216632-e93fd7c4-d134-11e7-9c90-3bd09d3d689a.png)

The top part is from our old material version, the transform style is set correctly.

At the bottom is the behaviour after upgrading.

Note, we have 2 swipers on the same page.

Any idea how to force the animation to work?

**Comment by sconix** [comment]
We don't have any issues with the Angular 5 / material 5 with the Swiper. So its something specific to your setup.
