### ISSUE TITLE
Used Loop after update when filtering the slides

### ISSUE THREAD

**Issue by orphen92** [zefoy/ngx-swiper-wrapper#84]
Hello, I did a function to filter the contents of the swipper.
The Swipper gets up to date after using my function combined with the update method.

However, I would like to use the carousel loop option and it does not work properly.

If my loop option is enabled when i loading the page, the Swipper duplicates the content.
I use my filter to delete elements, however the old duplicate elements are still present in the DOM.
Suddenly the old content appears when I comming to the end of the Swipper

Can you help me?

Another post talk about this problem
https://stackoverflow.com/questions/35601972/idangerous-swiper-duplicates

**Comment by sconix** [comment]
My guess is that you are not calling update at correct time. Have you tried using observer: true instead of calling update manually?

**Comment by orphen92** [comment]
I use the update methode when i launch my function and after updating the data.

```Javascript
  public filterChange(test) {
    this.SystemsItemsFiltered = this.SystemsItems.filter(function(val){
      return val.developer === test;
    });
    this.usefulSwiper.swiper.update();
    console.log('this.SystemsItemsFiltered', this.SystemsItemsFiltered); // Good value
  }
```

i have already try observer: true but i have the same result :(

**Comment by sconix** [comment]
If you don't call the update from timeout the data has not been updated to DOM yet. So you are basically calling the update before the change not after.

**Comment by orphen92** [comment]
Thanks for you help.
i have try this with the same issue i dont understand :( ````javascript
    setTimeout(() => {
      console.log('coucou');
      this.usefulSwiper.swiper.update(true);
    },1000);
````

**Comment by sconix** [comment]
Then I am guessing its a limitation or bug of Swiper.

**Comment by orphen92** [comment]
Okay,
Do you think i am on the right place for the developper see my message an add a fix?

**Comment by sconix** [comment]
Well no, you should report it to Swiper issues. But I suspect that dynamic slide changing might not be in the main interest of the Swiper developer, but who know. So you might still end up doing it manually.

If you end up doing it by application code, one thing to try could be to force reset of the Swiper instance when ever the slides changes (any wrapper configuration change should do that). So if Swipers shutdown will cleanup the duplicated slides then this "hack" could work rather easily.
