### ISSUE TITLE
Breakpoints properties reduced in version 4.0.0+

### ISSUE THREAD

**Issue by hassanasad** [zefoy/ngx-swiper-wrapper#85]
I want to ask a question

* Swiper Version: ^4.0.0
* Platform/Target and Browser Versions: macOS Chrome

In earlier version we could specify control in "breakpoints" property such as:
```
breakpoints            : {
	1024: {
		slidesPerView: 4,
		spaceBetween: 0
	},
	767: {
		slidesPerView         : 1,
		spaceBetween          : 0,
		freeMode              : false,
		freeModeSticky        : true,
		freeModeMomentum      : false,
		freeModeMomentumBounce: false,
		pagination            : { el: '.swiper-pagination', clickable: true },
		scrollbar             : null,
		mousewheel            : { sensitivity : 0.75 },
	}
}
```

However, in the newer Swipe version (^4.0.0) we cannot specify breakpoint properties other than "slidesPerView", "spaceBetween" and "sliderPerGroup". Is this intentional?

**Comment by sconix** [comment]
I don't see why you could not specify those.

**Comment by sconix** [comment]
They don't need to be part of the interface. Swiper documentation does not specify exactly what configuration options work so I only included those that I am 100% sure work with breakpoints in the interface, but the interface does not limit what you can put in the object.

**Comment by hassanasad** [comment]
Angular cli gives error when compiling :)

**Comment by sconix** [comment]
Hmm, I wonder if it has changed at some point. I guess I have to test, the interface documentation still says that there wont be error from addition attributes.

**Comment by sconix** [comment]
I don't get any errors, what is the error you are getting? I wonder if its some really strict typescript rule that you have one and I don't.

**Comment by sconix** [comment]
I made 5.0.3 release that does not have the breakpoint interface, instead the swiper config interface should be used. This way its more "accurate" documentation than with the incomplete breakpoint interface.

But I doubt that this will fix your problem, I am guessing that the error is about something else.

**Comment by hassanasad** [comment]
This is the error i get (for the properties mentioned in my first post):

```
ERROR in src/app/catalog/catalog/catalog.component.ts(123,5): error TS2322: Type '{ pagination: null; direction: string; slidesPerView: 4; mousewheel: { forceToAxis: true; invert:...' is not assignable to type 'SwiperConfigInterface'.
  Types of property 'breakpoints' are incompatible.
    Type '{ 1024: { slidesPerView: number; spaceBetween: number; }; 991: { slidesPerView: number; spaceBetw...' is not assignable to type 'SwiperBreakpointsInterface'.
      Property '767' is incompatible with index signature.
        Type '{ slidesPerView: number; spaceBetween: number; freeMode: boolean; freeModeSticky: boolean; freeMo...' is not assignable to type 'SwiperBreakpointInterface'.
          Object literal may only specify known properties, and 'freeMode' does not exist in type 'SwiperBreakpointInterface'.
```

**Comment by sconix** [comment]
Ah but if you read it carefully the problem is that property '767' is incompatible. You are trying to have the size as string not a number and thats the actual problem.

**Comment by hassanasad** [comment]
Well its not actually a string (as in the code in my first post). I think its giving error because 767 breakpoint contains properties that are not part of that interface.

**Comment by sconix** [comment]
Ah ok, so its just bad way to represent the error :) Anyway 5.0.3 should fix that.

**Comment by hassanasad** [comment]
With version 5.0.3 its fixed :) So i guess it was the same issue - Thanks man for your awesome support.
