### ISSUE TITLE
How to add thumbnails as navigation

### ISSUE THREAD

**Issue by agitator** [zefoy/ngx-swiper-wrapper#87]
I've got swiper working in my angular (5) app, via directive. Works great, thanx!
Now I'd like to extend it to show thumbnails for navigation as in this example https://github.com/nolimits4web/Swiper/blob/master/demos/300-thumbs-gallery.html

Not sure where/how to put the additional config in there, any advice?
Thanx
Peter

**Comment by sconix** [comment]
Configuration format is exactly same than with Swiper itself. README has all the relevant information how to pass config to the Swiper.

Github issues are for bugs not getting help with programming problems. There are other forums to seek help such as Stackoverflow so closing this as none issue.

**Comment by psinegmatic** [comment]
@agitator Did you solve your issue? I have the same, but can't find any solution.

**Comment by agitator** [comment]
yes, it's quite easy in the end...
Just add a second slider with your thumb scales and two configurations, one for the main slider one for the thumbs.
```
  public swp =  {
    observer: true,
     slidesPerView: 1,
     centeredSlides: true,
  };

  public thumbs =  {
    observer: true,
    initialSlide: 0,
    slidesPerView: 'auto',
    spaceBetween: 20,
    centeredSlides: true,
    slideToClickedSlide: true,
  };
```
The part I (angular newbie) was missing first is that config in `<swiper [config]="config" [(index)]="index">` is the name of your default config and you have to replace it with your more specific swiper configuration. Also if you keep the index as it is, they will be synced because they use the same index.
