### ISSUE TITLE
Pagination dosnt work, always hidden.

### ISSUE THREAD

**Issue by hdegues** [zefoy/ngx-swiper-wrapper#88]
const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
    observer: true,
    pagination: {
        el: '.swiper-pagination',
        type: 'bullets',
        clickable: true,
    },
    navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
    },
    slidesPerView: 'auto',
    watchSlidesVisibility: true,
    loopedSlides: 0,
    centeredSlides: true,
    spaceBetween: 30,
    loop: false,
    autoplay: {
        delay: 800,
        disableOnInteraction: false,
    },
};

element .swiper-pagination always empty and hidden.

**Comment by sconix** [comment]
There seems to be a bug with global config. I will fix this and release a new version, for now you should be able to get it working to just passing that configuration as custom config to the component.

**Comment by sconix** [comment]
Fixed in 5.0.4.
