### ISSUE TITLE
Why not Lazy Loading?

### ISSUE THREAD

**Issue by kairovisk** [zefoy/ngx-swiper-wrapper#89]
Hello, im trying to develop a example of Lazy Loading using your wrapper, but i dont know why its not working, the spinning icon never go away, it still running for forever.

Angular = 2;

MY HTML

    <div [swiper]="options" class="swiper-container">
          <div class="swiper-wrapper">
                <div class="swiper-slide" *ngFor="let slide of items_a">
                      <ion-card style="max-width:200px;">
                            <img data-src="{{slide.gameImage}}" class="swiper-lazy" />
                            <div class="swiper-lazy-preloader swiper-lazy-preloader-white">
                            </div>
                            <p>
                                   {{ slide.gameTitle }}
                            </p>
                       </ion-card>
               </div>
           </div>
      </div>
          
 
MY OPTIONS
`
this.options = {
    slidesPerView: 3,
    autoplay: 2000,
    speed: 500,
    preloadImages: false,
    lazy: {
         lazyLoadingInPrevNext: true,
         loadPrevNextAmount: 3,
         loadOnTransitionStart: true
    }
};
`

Variables.scss (i've downloaded the css);
`@import "scss/swiper"; `

![spin](https://user-images.githubusercontent.com/9329535/33572810-d10d2f40-d912-11e7-838c-ae021179d0e9.png)

**Comment by sconix** [comment]
It should work exactly like with Swiper, so double check the Swiper docs. If no luck I can have a try and verify that its not the wrapper (which is very unlikely) during the weekend.

**Comment by sconix** [comment]
Did you get this to work? Since at least if I look at you config its not like the API docs say.

**Comment by kairovisk** [comment]
Nah, the spinner still running forever above my images =/

i've fixed the "lazyLoadingInPrevNext", now is "loadPrevNext".

            this.options = {
                slidesPerView: 3,
                autoplay: 2000,
                speed: 500,
                preloadImages: false,
                lazy: {
                    loadPrevNext: true,
                    loadPrevNextAmount: 3,
                    loadOnTransitionStart: true
                }
            }

I've read again the docs about the Lazy Loading, it acceps a object as param and i verified the classes and divs in the layout, it seems fine. In my case, the difference is that i have a ion-card and a *ngFor.

**Comment by kairovisk** [comment]
this.options = {
                slidesPerView: 3,
                autoplay: 2000,
                speed: 500,
                preloadImages: false,
                observer: true,
                lazy: {
                    loadPrevNext: true,
                    loadPrevNextAmount: 3,
                    loadOnTransitionStart: true
                }
            };
The spinner still running forever above the images =/.
This could be a problem with the css or it is just about theming?

            @import '~swiper/dist/css/swiper.min.css';

 I mean, i have to import this to everything works fine, right?

**Comment by sconix** [comment]
My guess is that the problem is the ngFor, but you could easily verify if it is. Just test it with couple static elements. Swiper is not designed to be used with dynamically generated elements (afaik) and often you need to call the update manually after slides changes.

**Comment by kairovisk** [comment]
I've made a test with static images but they aren't appearing, i think im doing something wrong here. Look:
![lazy](https://user-images.githubusercontent.com/9329535/33956258-c6feeb7c-e01c-11e7-81c6-e66d6f3273b6.png)
(forget the black lines, they're just specifying what is happening)
1 - The First slide has just the static image;
2 - The second slide has  a card with a static image;
3 - The third slide has a P tag with a static image;

And the HTML:

        <div [swiper]="options" class="swiper-container">
            <div class="swiper-wrapper">
             
              <div class="swiper-slide">
                <img data-src="http://via.placeholder.com/200x200" class="swiper-lazy">
                <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
              </div>

              <div class="swiper-slide">
                <ion-card style="max-width:200px;">
                  <img data-src="http://via.placeholder.com/200x200" class="swiper-lazy" />
                  <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
                </ion-card>
              </div>

              <div class="swiper-slide">
                  <img data-src="http://via.placeholder.com/200x200" class="swiper-lazy" />
                  <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
                  <p>
                    Title 1
                  </p>
              </div>
           </div>
        </div>

**Comment by sconix** [comment]
At least I tested the lazy loading with the above non ionic-card slide in the example app and it works perfectly. One thing I notice that you have autoplay: 2000 in your config and thats not proper format of Swiper. So that raises one question, which version of this library you are using? Since 4.x version uses Swiper 3 and 5.x Swiper 4. Both have different configuration format so maybe you are just using wrong configuration format.

**Comment by kairovisk** [comment]
I'm using this one https://github.com/zefoy/ngx-swiper-wrapper/tree/2.x.x
                 `npm install angular2-swiper-wrapper --save-dev`
Now i'll reinstall to make sure. Also, i didnt noticed the error in Autoplay.

**Comment by kairovisk** [comment]
I've updated my angular and now its working perfectly with the 5.x.x, thank you! You can close the topic.

**Comment by madumal7** [comment]
There was no fix I could find for this. I achieved this by manually calling the lazy.loadInSlide(index: number) method in swiper as follows.
`@ViewChild('swiper', { static: false }) swiper: SwiperComponent;

onImgLoad(index: number) {
    this.swiper.swiper.lazy.loadInSlide(index);
  }`

html component looks like this.

`<swiper [config]="config" #swiper>
  <div class="swiper-wrapper">
    <div *ngFor="let item of data; index as i" class="swiper-slide">
        <img (load)="onImgLoad(i)" data-src="{{ item.link }}" alt="" class="swiper-lazy">
        <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
        <span>{{ item.title }}</span>
    </div>
  </div>
  
  <div class="swiper-button-next"></div>
  <div class="swiper-button-prev"></div>
</swiper>`

**Comment by madumal7** [comment]
I managed to get this done by manually calling the lazy.loadInSlide() function with the index of the loaded slide.
My component looks like this.

```
export class SubCarouselComponent implements OnInit {
  @ViewChild('swiper', { static: false }) swiper: SwiperComponent;

  onImgLoad(index: number) {
      this.swiper.swiper.lazy.loadInSlide(index);
    }
}
```

```
<swiper [config]="config" #swiper>
  <div class="swiper-wrapper">
    <div *ngFor="let item of data; index as i" class="swiper-slide">
        <img (load)="onImgLoad(i)" data-src="{{ item.imgUrl}}" alt="" class="swiper-lazy">
        <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
        <span>{{ item.title }}</span>
    </div>
  </div>
  <!-- Add Arrows -->
  <div class="swiper-button-next"></div>
  <div class="swiper-button-prev"></div>
</swiper>
```

I googling. but no other solution found that works for my angular project.
