### ISSUE TITLE
There is no directive with "exportAs" set to "ngxSwiper"

### ISSUE THREAD

**Issue by renandiett** [zefoy/ngx-swiper-wrapper#90]
I've been started with your swiper component and now I need to filter the slider based on selected category on the screen: 

![sem titulo](https://user-images.githubusercontent.com/8188365/33635001-682c438a-d9fd-11e7-9d63-9d1f97a2c536.png)

The code that's causing the error is `<swiper #mySwiper="ngxSwiper">`

And the component has been configured as:

```js
import { SwiperModule } from 'ngx-swiper-wrapper';
import { SWIPER_CONFIG } from 'ngx-swiper-wrapper';
import { SwiperConfigInterface } from 'ngx-swiper-wrapper';

const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
  direction: 'horizontal',
  slidesPerView: 'auto',
  keyboard: true
};
```

Also I've imported the module at:

```js
@NgModule({
  declarations: [
    AppComponent,
    ...
  ],
  imports: [
    ...
    SwiperModule
  ],
  providers: [
    {
      provide: SWIPER_CONFIG,
      useValue: DEFAULT_SWIPER_CONFIG
    }
  ],
  bootstrap: [AppComponent]
})
```

I just need to call the `setIndex()` method from directive but I can't do that.

**Comment by sconix** [comment]
Check the example app if you are not familiar how to get the needed reference with Angular.

**Comment by renandiett** [comment]
oh, my bad! sorry! I just looked at your example and then its working like a charm! Thank you!

**Comment by renandiett** [comment]
The code below is now working!

```js
@ViewChild(SwiperComponent) componentRef: SwiperComponent;
@ViewChild(SwiperDirective) directiveRef: SwiperDirective;
```

```js
public nextSlide() {
  this.componentRef.directiveRef.nextSlide();
}

public prevSlide() {
  this.componentRef.directiveRef.prevSlide();
}
```

**Comment by renandiett** [comment]
After doing some changes the component is now working perfectly!

See the GIF:

![ngx-swiper-wrapper](https://user-images.githubusercontent.com/8188365/33671268-4c34ece0-da8e-11e7-9dc1-5379c51fa8fc.gif)
