### ISSUE TITLE
Slide arrows not working for dynamic slides

### ISSUE THREAD

**Issue by hassanasad** [zefoy/ngx-swiper-wrapper#94]
For some reason the slide arrows are hidden away when using the following:

**Markup:**
```
<swiper [config]="swiperConfig">
	<ng-container *ngIf="product?.imageUrls && product?.imageUrls?.length" async>
		<div *ngFor="let imageUrl of product?.imageUrls" async>
			<div class="img slider-img" [ngStyle]="{'background-image' : 'url(' + imageUrl + ')'}"></div>
		</div>
	</ng-container>
</swiper>
```

**Config:**
```
swiperConfig: SwiperConfigInterface = {
	direction     : 'horizontal',
	slidesPerView : 1,
	scrollbar     : false,
	keyboard      : true,
	mousewheel    : false,
	pagination    : { el: '.swiper-pagination', clickable: true },
	slideNextClass: '.swiper-button-next',
	slidePrevClass: '.swiper-button-prev',
	preloadImages : true,
	lazy          : false,
};
```

Even if i manually remove the `hidden` attribute from the arrows (from developer tools) - it doesn't work. Can it be because the slide elements are loaded dynamically and not when the swipe was initiated? (It used to work fine in previous versions though)

**Version Details:**
Angular: 5.1.0
CLI: 1.6.0
Swipe: 5.0.5
OS: MacOS High Sierra
Browser: Chrome

**Comment by sconix** [comment]
I am not seeing any configuration for navigation. If you want the navigation arrows you have to set navigation: true (or object with element etc.). See the Swiper documentation, lot have changed from the 3.x Swiper in the configuration format.
