### ISSUE TITLE
click/tap event not firing when loop is set to true

### ISSUE THREAD

**Issue by henryhe1993** [zefoy/ngx-swiper-wrapper#95]
Seems this issue was fixed about a month ago (https://github.com/nolimits4web/Swiper/issues/2140). Not quite sure about the Swiper version this wrapper is currently using (3.4.2?). Is it possible to update it to Swiper version 4? Or do you have any other repo that is based on Swiper version 4? 
Many thanks.

**Comment by sconix** [comment]
5.x version of this library uses the latest Swiper (4.x).

**Comment by henryhe1993** [comment]
Thanks for your reply. I'll definitely try that.
