### ISSUE TITLE
Get slider instance in two different sliders

### ISSUE THREAD

**Issue by psinegmatic** [zefoy/ngx-swiper-wrapper#96]
I have an issue with two sliders, when i use them as SwiperDirective. 

I have #slider1, and #slider2 for example, how can i get instance of these sliders using ViewChild?
Actually, I want to create gallery with thumbnails and use slider1 control for slider2 like in this example: 

` galleryTop.controller.control = galleryThumbs;
    galleryThumbs.controller.control = galleryTop;`

There's no exapmle for getting instance of two different SwiperDirective. 

Could you help, please?

**Comment by sconix** [comment]
Check angular documantation, you can name the component in the template and use the name with the viewchild.

**Comment by psinegmatic** [comment]
And then we have ElementRef, but not the swiper insatnce.

**Comment by sconix** [comment]
Yes you can tell the type with the name just check the Angular documentation :) Like #mySwiper="ngxSwiper".

**Comment by sconix** [comment]
Atm you need to use directive though, the component is missing the exportAs. I will add it for next release.

**Comment by psinegmatic** [comment]
Do you mean component instead of directive?

**Comment by sconix** [comment]
No, I mean that only the directive has the exportAs which is needed for you to be able to target the directive reference with the name. So you need to use the swiper directive for now. Next 5.1.0 release will have the exportAs in the component as well so then its possible to use the same way to get the component references.

Of course you can already use ViewChildren for component as well. Anyway all this is basic Angular stuff not related to this library or this library usage. You just need to check the Angular documentation about ViewChild and ViewChildren.
