### ISSUE TITLE
Pagination with Component approach not working

### ISSUE THREAD

**Issue by seanmavley** [zefoy/ngx-swiper-wrapper#97]
This is my module where I use the swiper

```
import { SwiperModule, SwiperConfigInterface, SWIPER_CONFIG } from 'ngx-swiper-wrapper';

const DEFAULT_SWIPER_CONFIG: SwiperConfigInterface = {
  observer: true,
  direction: 'horizontal',
  slidesPerView: 'auto',
  keyboardControl: true,
  loop: true,
  // navigation: true, <-- this no longer works (nor exists)
  pagination: {
    el: '.swiper-pagination',
    clickable: 'true',
    type: 'bullets'
  },
};

@NgModule({
  imports: [
    // imports here
    SwiperModule,
  ],
  declarations: [
    // delcarations here
  ],
  providers: [{
    provide: SWIPER_CONFIG,
    useValue: DEFAULT_SWIPER_CONFIG
  }]
})
export class MyModule { }
```

Then in template:
```
 <swiper *ngIf="deck"> 
    <div *ngFor="let card of cards; let i=index;">
       <-- HTML here-->
     </div>
</swiper>
```

The above renders fine, except pagination doesn't show nor anything.

Does enabling the configuration module-wide not apply to individual components? What am I missing?

**Comment by sconix** [comment]
You are not saying what version you are using? Navigation exists and works, but if you are using 4.x version then it does not exist and your pagination configuration is wrong. The 5.x version of this library uses Swiper 4.x and 4.x version uses Swiper 3.x so there is big difference between the version for the configuration format.

**Comment by seanmavley** [comment]
I am using "ngx-swiper-wrapper": "^4.8.0". 

> but if you are using 4.x version then it does not exist and your pagination configuration is wrong.

How do I make the configuration right then?

**Comment by sconix** [comment]
You need to check Swiper 3.x api documentation.

**Comment by sconix** [comment]
I will update the 4.x readme to point to the correct place which is:

https://github.com/nolimits4web/Swiper/blob/Swiper3/API.md

**Comment by seanmavley** [comment]
I know the below works, considering the `loop` and `keyboardControl` works.

Yet, pagination still doesn't

```
const SWIPER_CONFIG: SwiperConfigInterface = {
  observer: true,
  direction: 'horizontal',
  slidesPerView: 'auto',
  keyboardControl: true,
  pagination: '.swiper-pagination',
  paginationType: 'bullets',
  paginationClickable: true,
  paginationHide: false,
};
```

```
@NgModule({
  imports: [
 ...
    SwiperModule.forRoot(SWIPER_CONFIG),
  ],
  declarations: [
  ...
  ],
})
```

It is easier to dismiss and point to docs whatever, however if it works I wouldn't be back. Heck, I had to point to the https://github.com/zefoy/ngx-swiper-wrapper/tree/4.x.x to see the 4x readme, which isn't pointed on the master. By default, you're showing 2.x via master. Without saying it isn't the 4.x how on earth would I know right out of the box?

My html isn't anything customized. just the usual workflow

```
  <swiper *ngIf="deck">
    <div *ngFor="let card of cards; let i=index;">
      <div class="container">
         <!-- content here -->
      </div>
    </div>
    <div class="swiper-pagination"></div>
  </swiper>
```

I see a lot of pagination-related code generated in the render, however nothing shows in the view actually. No bullets shown. nothing.

I add the next prev html and reference in the SWIPE_CONFIG. Nope. nothing shows.

I might be doing something wrong, well thanks to the limited info this wrapper gives.

**Comment by sconix** [comment]
You can see it working in the example app so check from that how to do it. Github issues are for bugs, its not a support forum. And this is not a bug since we use the pagination as well and it works perfectly. 

I will usually give some support in the github issues, but not for old legacy versions.

**Comment by sconix** [comment]
What do you mean by the documentation is not pointed correctly in the master? As far as I can see the documentation link points to the latest Swiper documentation.

Having the wrong link to in 4.x.x branch was a "bug" which I already fixed.

**Comment by seanmavley** [comment]
> This documentation is for the latest 5.x.x version which requires Angular 5. For Angular 4 you need to use the latest 4.x.x version. Documentation for the 4.x.x can be found from here.

Meanwhile, [installation step just below it](https://github.com/zefoy/ngx-swiper-wrapper#installing-and-usage) says:
> npm install ngx-swiper-wrapper@4.7.0 --save

...as per master: https://github.com/zefoy/ngx-swiper-wrapper

I guess it is an oversight, no?

**Comment by sconix** [comment]
Thanks for pointing that out, its an error from merging changes from 4.x, will fix.
