### ISSUE TITLE
SwiperModule  'undefined' in app.module.ts

### ISSUE THREAD

**Issue by andreagdev** [zefoy/ngx-swiper-wrapper#98]
I have imported in app.module.ts SwiperModule:

```
@NgModule({
  ...
  imports: [
    ...
    SwiperModule
  ],
  providers: [
    {
      provide: SWIPER_CONFIG,
      useValue: DEFAULT_SWIPER_CONFIG
    }
  ]
})
```

But the imports SwiperModule is undefined; when launch application, follow this error:
Unexpected value 'undefined' imported by the module 'AppModule'

**Comment by seanmavley** [comment]
Your error sounds like one of these: https://stackoverflow.com/questions/39265561/error-unexpected-value-undefined-imported-by-the-module and might not be swiper module related.
