### ISSUE TITLE
Number of slides issue with directive approach

### ISSUE THREAD

**Issue by hassanasad** [zefoy/ngx-swiper-wrapper#99]
After one of the updates to latest version, my directive based swiper has stopped working.
It only counts all the slides as one slide so Arrows and Scrollbars/navigation are all disabled.
If i grab the slide and manually slide it from left to right - it works but then as soon as i let to, it reverts back.

I am testing with a very basic code and yet its not working:

Markup:
```
<div class="swiper-container" [swiper]="config">
	<div class="swiper-wrapper">
		<div *ngFor="let i of [1,2,3,4,5,6,7,8,9,10,11,12,13]" class="swiper-slide" style="height: 40px; background: #ddd">
			{{ i }}
		</div>
	</div>

	<div class="swiper-scrollbar"></div>
	<div class="swiper-pagination" ></div>

	<div class="swiper-button-prev"></div>
	<div class="swiper-button-next"></div>
</div>
```

Typescript:
```
private scrollbar = {
	el: '.swiper-scrollbar',
	hide: false,
	draggable: true
 };

private pagination = {
	el: '.swiper-pagination',
	clickable: true,
	hideOnClick: false
};

public config: SwiperConfigInterface = {
	direction: 'horizontal',
	slidesPerView: 1,
	keyboard: true,
	mousewheel: true,
	scrollbar: this.scrollbar,
	navigation: true,
	pagination: this.pagination
};
```

Versions:
Node: 9.3.0
Npm: 5.6.0
Swiper Wrapper: 5.1.0

P.S: The non-directive approach is still working fine

**Comment by sconix** [comment]
Since you are using ngFor you need to either use observe: true in config or call update manually once slides are rendered.

**Comment by hassanasad** [comment]
Sorry - i dont follow. Update what manually?
(I dont see Observer: true in one of your examples)

**Comment by sconix** [comment]
When ever slides changes dynamically you need to call update method of the Swiper. The observer option will call it automatically when elements changes (see Swiper docs for more info).  The update method is in the Readme.

**Comment by hassanasad** [comment]
I added `observer: true` and it still doesn't work initially. I have to swipe it from left to right manually trigger it into working

**Comment by sconix** [comment]
Then its hard to say what could be the problem. Can you try to replicate it in Plunker?

**Comment by hassanasad** [comment]
I tried - i dont know how to import swiper package.
This is what i have https://plnkr.co/edit/NPBKA3nCgExJW2RCOxzA?p=preview

**Comment by sconix** [comment]
There seems to be a problem with the umd bundle library and thats why its not possible to import this library in Plunker (i.e. systemjs setup). I will soon release a new version and then the Plunker example should work and I can check it then.

**Comment by sconix** [comment]
With the new release I was able to replicate the issue with your Plunker example. This is kind of weird since there is no difference to the example app and it works correctly. I will study this bit more and let you know when I find the reason for this behavior.

**Comment by sconix** [comment]
Ok so the issue in your Plunker and most likely in your app is that you are not loading the swiper styles.

**Comment by hassanasad** [comment]
Actually i do have the style imported. It was working fine before one of the later updates.

```
"styles": [
        "../node_modules/swiper/dist/css/swiper.min.css",
      ],
```
Above code is part of my .angular-cli.json file (i am using Angular-cli 1.6.1)

**Comment by sconix** [comment]
So maybe you need to look into your angular-cli setup if something has changed. At least the fault in the Plunker was due to not having the styles files imported and the miss behavior did match your problem. Adding the loading of the swiper style file did fix the issue in the Plunker example.

**Comment by hassanasad** [comment]
I double checked and the stylesheet is getting imported in my project. The arrows are showing correctly and the scrollbar and transitions also work fine. However the pagination is not working with directive. It works with the `<swiper>` component though.

Its very weird.

**Comment by sconix** [comment]
So you did find the fix for the original issue? If you mean that only one pagination dot is showing then you haven't added the observer: true. As I said earlier you need to have it or call update manually after the slides changes.

With the style file loaded and observer: true I don't see any issues in your Plunker example.

**Comment by hassanasad** [comment]
I have used the 'update' method for now. 'observer' is also set to true but
that's not working (if i comment out update it stops working).

The pagination is not showing any dots. It just becomes an empty div.

**Comment by sconix** [comment]
Hard to say what you are doing wrong without way to replicate the issue. If you can replicate it in the Plunker let me know. To get the Plunker work you need to just add 'swiper': 'npm:swiper', to the systemjs config and the loading of theme into index.html. At least the previous Plunker you did is working perfectly for me with the addition of observer: true.

**Comment by hassanasad** [comment]
I have updated the plunker slightly to use most of the configurations that i have. In my case i have the pagination at breakpoints 767 but for now i have also added it in the main config. In the plunker i link, scrollbar isn't working and throwing tons of errors (in console). However `observer:true` is working just fine.
It slightly mind boggling.

https://plnkr.co/edit/NPBKA3nCgExJW2RCOxzA?p=preview

**Comment by sconix** [comment]
For me that Plunker works perfectly with no errors in the console at least with Chrome. So if you are using some other browser maybe you have found a bug in Swiper.

**Comment by hassanasad** [comment]
Man this is so weird - i too am using Chrome (63.0.3239.84) on macOS High Sierra.

For me the scrollbar isn't working in that plunker

**Comment by sconix** [comment]
For me its disabled if the preview is less than 768 like you have configured and if the view is larger then scrollbar works. One thing to notice is that it seems like if you go from <768 to bigger the scrollbar does not seem to start working and I am guessing that is because there is no scrollbar configuration in the other breakpoints so Swiper wont "re-apply" the "common" config and it just sets the breakpoint configuration when ever breakpoint changes. So to work with resize you need to add the wanted scrollbar config to all of the breakpoints.

**Comment by hassanasad** [comment]
Yeah - the pagination is working now that i have it in base configurations and hiding it using CSS.

The Swiper 4.0.7 came with lots of issues. :(

**Comment by sconix** [comment]
I still think it could be your configuration as well since as said to me the Plunker works exactly like its configured. That said its of course possible that its a bug since 4.x Swiper is still relatively young. I will anyway close this issue now since at least this is not issue in this wrapper.
